### ISSUE TITLE
UX question: How to handle all these admin links?

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1001]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
We're about to unleash a bunch of admin-only routes, such as:
* accounting
* reporting
* user management
* clinic management

This is four new links on the top dashboard, which probably is not going to fit. Where in the app should we put this list of stuff?

* **What feature or behavior is this required for?**
Clean dashboard up top!

* **How could we solve this issue? (Not knowing is okay!)**
UX's choice!

**Comment by mebates** [comment]
We need some dropdowns! Let's try to use the behavior from the USWDS Basic Header, minus the search bar and 'This is a govt website' bar: https://standards.usa.gov/components/headers/#basic

![fullsizerender](https://cloud.githubusercontent.com/assets/6223901/25599181/12225020-2ea8-11e7-9805-fdc40b265d21.jpg)

* Remove links to 'Dashboard' and make the name in the left corner to link to the Dashboard
* "DC Call Line" is simply display text in GRAY, not purple. (purple means action)
* 3 menu items at the top level: CM Resources, Admin, and [user name]
* Admin and [user name] have menu dropdowns
* "Create User" becomes "User Management". Does anything else live there at this time?

@colinxfleming what happened to the reports page that we wanted available to all users? We'll want to link to that at the top level too.

**Comment by ashlynnpai** [comment]
I'll take this.

**Comment by colinxfleming** [comment]
Resolved by @ashlynnpai 's great work in #1036 !
