### ISSUE TITLE
Order clinics on index page alphabetically

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1007]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
At `/clinics`, the list of clinics currently does not come back alphabetized, which makes finding a particular clinic a real pain in the neck. We're trying to sort that in a reasonable way -- let's go with alphabetically.

* **What feature or behavior is this required for?**
Making maintaining clinic data less obnoxious.

* **How could we solve this issue? (Not knowing is okay!)**
Throw in a sort by name on the `Clinic.all` in `ClinicsController#index`. Piece of cake! No tests necessary for this.

**Comment by lwaldsc** [comment]
Just to clarify on this, can we alphabetize by state (DC/VA/MD/Other)?

**Comment by colinxfleming** [comment]
@lwaldsc this one's for the admin panel that deals with clinics so I'm not sure the utility is the same, but would this be helpful at the point where CMs are selecting clinics from the dropdown?

**Comment by lwaldsc** [comment]
Yeah. I still think it would be useful for the admins to be able to sort
that list by state, but I defer to their preference.

As for the CM side dropdown, I think it would also be useful there. Are we
breaking out the PP clinics as well?

**Comment by pbkappa** [comment]
hey there, I'm new! If it's cool I'll take this one

**Comment by colinxfleming** [comment]
Totally cool! Let me know if you run into any issues, and welcome!

**Comment by nickrobinson** [comment]
Grabbing this one
