### ISSUE TITLE
Stop incrementing LMP after a certain point

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1008]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
One of the most useful features in the app is our `LMP counter`, which given a date of initial call and another date will tell you how many weeks since someone's last menstrual period. However, we don't have it stop ever, so as we reconcile we're starting to see some people who are, like, 60 weeks pregnant, which, yikes. 

We should make it so this stops incrementing at either the date of appointment, or at 35 weeks 0 days. 

* **What feature or behavior is this required for?**
Reducing the cringe factor for our data entry team.

* **How could we solve this issue? (Not knowing is okay!)**
The code for this is in `app/helpers/last_menstrual_period_helper.rb`. Probably it involves adding some special case handling to the methods in there. You can see an example of how we're using it in practice at `app/views/patients/_patient_dashboard.html.erb`.

* **Anything else?**
Stems from #864

**Comment by NerdyGirl537** [comment]
Also a thought is that at 40 weeks (full term) is a key to archive the patient.

**Comment by KatSDC** [comment]
Let me take a shot at this ticket! I'll be at Monday's meetup too in case I get stuck.
