### ISSUE TITLE
Add optional county field

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1016]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Add a `county` field (string) on `Patient` object, and then add it to the form in `app/views/patients/_patient_information` if an env var for `TRACK_COUNTY` is present.

* **What feature or behavior is this required for?**
Baltimore Abortion Fund tracks county as a business need. We should

* **How could we solve this issue? (Not knowing is okay!)**
Nice and straightforward -- add a line to the appropriate place in `app/models/patient.rb`

* **Anything else?**
Needed for BAF deployment. 

There's probably an additional ticket as we generalize to allow toggling particular fields but I think we should wait until that crystalizes a little more (e.g. wait for another fund to give us a sense of what their particular business needs are)

**Comment by electricflannel** [comment]
I'll take this one
