### ISSUE TITLE
Set up gemnasium

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1020]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Set up gemnasium to monitor dependency vulnerabilities

* **What feature or behavior is this required for?**
~ security ~

Tagging in @DarthHater - can you handle?

**Comment by colinxfleming** [comment]
Come to think of it, DCAF proper should have the creds here, and we should see if we can set up some secondary emails. I'll set up account stuff.

**Comment by colinxfleming** [comment]
@DarthHater - regged a DCAF account and invited you. Let me know if you hit a roadblock!

**Comment by DarthHater** [comment]
Tagging in. I believe I need some elevated permissions on the DCAF org on gh and maybe even on this repo to get it setup. Expect emails.
