### ISSUE TITLE
Log of tests that need wwriting

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1039]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Maintain high test coverage for our app by logging corners we cut, so we can add tests for them later.

* **What feature or behavior is this required for?**
Not accidentally breaking things as move into production

WIth that, the log: 

* <strike>updateBalance function in patients.coffee (should be an integration test confirming that the math in abortion information fires and is accurate)</strike> ( #1045 , thanks @tingaloo )

**Comment by colinxfleming** [comment]
Integration test for the functionality in #986 (clicking 'NAF clinics only' disables non-NAF clinics from the select box)

**Comment by tingaloo** [comment]
[WIP test for #986 ](https://github.com/tingaloo/dcaf_case_management/blob/cefe9aa5463b86c1a886ea5399841653c77b19ed/test/integration/update_patient_info_test.rb#L87-L107) for whoever wants to pick it up.

**Comment by colinxfleming** [comment]
@tingaloo I picked that thread up in #1048 , would love your thoughts on that

**Comment by colinxfleming** [comment]
There are like

**Comment by colinxfleming** [comment]
Effectively resolved, let's move any further tests to an issue thread.
