### ISSUE TITLE
Include timestamp of pledge in fulfillment verification

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1043]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
While dogfooding pledge fulfillments, I saw a pledge of two with 'this is a resent pledge' -- would be helpful to have some sort of confirmation that the last pledge sent date matches that.

* **What feature or behavior is this required for?**
Fulfillment data entry validation

* **How could we solve this issue? (Not knowing is okay!)**
We should add a 'pledge sent on' date to the information confirmation in the pledge partial that draws from the `pledge_sent_at` field (or whatever it's called). 

* **Anything else?**

**Comment by itroman** [comment]
Happy to start working on this.

**Comment by tedlayea** [comment]
Happy to work on it.
