### ISSUE TITLE
What should the buttons say in the cancel pledge workflow?

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1046]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
If you go to cancel a pledge now, here's what you're going to see:

![screen shot 2017-05-05 at 5 58 27 pm](https://cloud.githubusercontent.com/assets/3866868/25765734/77aec222-31bc-11e7-8669-488470b4810c.png)
![screen shot 2017-05-05 at 5 58 16 pm](https://cloud.githubusercontent.com/assets/3866868/25765733/77a996bc-31bc-11e7-914e-4e9d0d101d1b.png)

@mebates rightly pointed out that this veribiage is confusing in #925 -- " If my primary goal is to cancel, it's odd that the word "Cancel" is in the lower left corner of the modal, but that won't make it happen for me. I know that's the standard, but maybe we can use different words or just do an 'are you sure?'"

* **What feature or behavior is this required for?**
Clear, unambiguous direction if we have to cancel a pledge.

* **How could we solve this issue? (Not knowing is okay!)**
Two steps here: First, UX team should decide what we should change the copy to, then make a frontend change to the copy. 

* **Anything else?**
nope!

**Comment by mebates** [comment]
I would suggest a simple dialog box like this (wireframe, use standards for other dialog boxes):

<img width="422" alt="screen shot 2017-06-05 at 7 39 47 pm" src="https://cloud.githubusercontent.com/assets/6223901/26807822/c5e5ab2c-4a26-11e7-90de-2748cf84e0c3.png">

**Comment by colinxfleming** [comment]
@SamuelLangenfeld let me know if you need a hand figuring this out here -- iirc the next/cancel verbiage is set in a kind of complicated way.

**Comment by SamuelLangenfeld** [comment]
@colinxfleming are we keeping the two step modal process for cancelling the pledge? Or would we rather just have a one step dialog box?

**Comment by colinxfleming** [comment]
@SamuelLangenfeld gotta defer to @mebates on what the right call here is, I'm not sure.

**Comment by SamuelLangenfeld** [comment]
@mebates I have a couple of choices for you for the styling on this issue and I was just wondering which you'd prefer. Here's the basic modal style for cancelling a pledge based on your design:
![screenshot from 2017-08-25 15-41-40](https://user-images.githubusercontent.com/22413614/29730792-c0015940-89af-11e7-8e25-6f4afc9bc3e1.png)

Or I could make it more in line with the styling from the modal that pops up when you submit a new pledge. Something like this:
![screenshot from 2017-08-25 16-06-31](https://user-images.githubusercontent.com/22413614/29730828-f49a7b14-89af-11e7-97e8-076c5ef7447a.png)

And last but not least, a more bootstrappy design that I'm partial to. I like that the buttons are farther apart, and that the yes button is styled with a different color.

![screenshot from 2017-08-25 16-16-15](https://user-images.githubusercontent.com/22413614/29731056-ec82dd3a-89b0-11e7-95cf-fc2823059485.png)


Which design would work best?

**Comment by colinxfleming** [comment]
@SamuelLangenfeld let's go with the middle one -- closest and most consistent to what we're doing now. Thanks for doing the legwork on this!
