### ISSUE TITLE
Add Patient#pledge_generated_by field

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1051]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Track what user last generated a pledge, in addition to timestamps.

* **What feature or behavior is this required for?**
Auditing/Verifying who generated the last pledge

* **How could we solve this issue? (Not knowing is okay!)**
<strike>Three</strike>Four steps:
* Add field `pledge_generated_by` to Patient, as a user id
* Display on `_fulfillment` partial, below pledge amount
* Add to PatientsController#download update statement, to set `pledge_generated_by` as `current_user`
* Add to PatientsController test to confirm that the action is triggering

* **Anything else?**
nope!

**Comment by itroman** [comment]
Would like to work on this...but may have a question or two along the way.

**Comment by colinxfleming** [comment]
hey @itroman ! Sounds good, let me know what snags you hit. I bumped the ticket to reflect an edit to the `PatientsController` in there too. 

Getting the `pledge_generated_by` thing in the patient model cleanly is probably the trickiest part of this, and I think you can wire that up with something like `has_one :pledge_generated_by, class: User` or something like that. I forget the exact syntax, should be in the ActiveRecord or mongoid docs somewhere. 

Thanks a ton for tackling this, really appreciate it!
