### ISSUE TITLE
Remove zip code

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1053]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
We don't really need to track zip code in this app, so let's take it out.

* **What feature or behavior is this required for?**
Patient information security, not keeping extra stuff around.

* **How could we solve this issue? (Not knowing is okay!)**
Remove the field from the model in `app/models/patient.rb`!

* **Anything else?**
See discussion in #306

**Comment by itroman** [comment]
Happy to do this if it still needs doing :)

**Comment by colinxfleming** [comment]
Yes please, go for it!
