### ISSUE TITLE
Handle non-english, non-spanish speakers

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1075]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
BAF has a common use case of logging languages other than english, which mashes up against our current language model. 

* **What feature or behavior is this required for?**
Accurately tracking language of callers

* **How could we solve this issue? (Not knowing is okay!)**
UX research!

* **Anything else?**
Popped up during baltimore rubber hitting the road

**Comment by mebates** [comment]
@NerdyGirl537 suggests we loop back with @vtmeghan to see how the 'Spanish Only' checkbox is being used now. The intention was that if the box was checked, the 'Spanish Only' cases would be diverted to Spanish-speaking CMs. I'm not sure that we have anything very helpful in the UI that facilitates it (for example, it doesn't move to a spanish queue, or something).

If that functionality is not really helping much, we can just move this to a language dropdown. We can just replace the checkbox with Language: [Dropdown]. List can include English (Default), Spanish, French, Korean. (Per Annie's email. Any others?) 

![screen shot 2017-06-05 at 7 21 57 pm](https://cloud.githubusercontent.com/assets/6223901/26807752/51986b56-4a26-11e7-9194-de44f026f9ed.png)

**Comment by vtmeghan** [comment]
I don't know that it's really being used at all, given, as you say, there's no way to separate out Spanish-only PTs currently. I think a drop-down might be better, especially as we expand our outreach and get (hopefully) more non-English/Spanish patients.

**Comment by colinxfleming** [comment]
Language workflow is unlikely to materialize at this point and it doesn't seem to be a problem.

I'd say let's start with a dropdown with the Baltimore language set (defined by a helper) and move language to either an enum or a string. (Basically we can pretty much make this look like the insurance dropdown but with language.)

**Comment by colinxfleming** [comment]
Long term we can then explore whether or not we can chuck this in a config a la #1072 and #1074 (see also #1092 ).

**Comment by colinxfleming** [comment]
This is shovel ready. Instructions are: 

* define a helper function in `patients_helper` that returns an array of languages -- Spanish, French, Korean to start
* alter the patient model such that language is a string rather than a boolean
* take out the spanish language checkbox in the patient information partial and replace it with a dropdown, populated by that helper
* write a test for the new helper function
* adjust integration tests to confirm that this new dropdown saves okay by adjusting the code in `test/integration/update_patient_information_test.rb`

**Comment by colinmcglynn** [comment]
I'll grab this one
