### ISSUE TITLE
Don't add patient to call list when working in data entry mode 

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1076]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Not add patients to a call list when entering them through data entry mode.

* **What feature or behavior is this required for?**
Not bogging down call lists on dashboard when entering ~100+ patients into the system at a time

* **How could we solve this issue? (Not knowing is okay!)**
Pop into PatientsController#data_entry_create and remove the line that adds them to the current user's call list

* **Anything else?**
nope!

**Comment by itroman** [comment]
I went ahead with a PR for this as it looked like something in active development I could knock out fast.
