### ISSUE TITLE
Add medicaid coverage to clinic data?

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1077]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Baltimore is interested in tracking medicaid info for clinics. We should figure out how to implement and what they're hoping to get out of it.

* **What feature or behavior is this required for?**
???

* **How could we solve this issue? (Not knowing is okay!)**
Probs start by talking to the baltimore folks about how they use this up the road!

* **Anything else?**
not yet!

**Comment by mebates** [comment]
@lwaldsc or @nerdygirl537  - can you follow up on the user requirements for Baltimore and medicaid, please? This issue doesn't have enough info to do any UX work yet

**Comment by lwaldsc** [comment]
Re: Annie at BAF

"So I think what we'd like is the ability to, in DARIA, put in info re:
which clinics take Maryland Medicaid and to what gestational age (similar
to how you can fill in costs now). Colin mentioned something about creating
a clinic lookup tool, so I just wanted to make sure that if/when that is
built, it also includes information for Medicaid patients so our CMs can
steer them to the best clinic for them."

Pretty simple ask here, I think.

**Comment by colinxfleming** [comment]
Based on the above from Annie I think there are two enhancements here: 

* deal with Medicaid clinics in #978 
* implement something similar to the 'Show only clinics that accept NAF funds' checkbox for Medicaid clinics

Either way, the route to both of these is slapping an extra boolean field for `accepts_medicaid` on the clinic object, and then adjusting the form and tests. Retagging as backend for now, and we can take advantage of the benefits down the road.

**Comment by rudietuesdays** [comment]
I'll work on this tonight!
