### ISSUE TITLE
Stupidtable Sort does not work after Search

### ISSUE THREAD

**Issue by tingaloo** [DCAFEngineering/dcaf_case_management#1099]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
In ```users/index.html.erb```, stupidtable sort does not work after search

* **What feature or behavior is this required for?**
It's a bug.

* **How could we solve this issue? (Not knowing is okay!)**
Something about javascript and turbolinks?

* **Anything else?**
See #1073

**Comment by colinxfleming** [comment]
Tagging hacktoberfest. Probably this involves wrenching around in `app/views/users/index.html.erb`, the associated search render `app/views/users/search.js.erb`, and maybe the stupidtable invocation in `app/assets/javascripts/table_sorting.coffee`.
