### ISSUE TITLE
front end - lines should extend to bottom of content

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#1101]
The vertical line dividing space on the patient screens should extend to the bottom of the content. 

![screen shot 2017-06-05 at 7 21 32 pm](https://cloud.githubusercontent.com/assets/6223901/26808126/cbde8736-4a28-11e7-9bd0-791b9312c917.png)

**Comment by colinxfleming** [comment]
I think the path forward here is probably moving the border attribute from the left menu (id `menu`) to the right side (id `sections`). That should set it to follow whatever's in that right panel.
