### ISSUE TITLE
Increase max width of DCAF site

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#1103]
The call list is really squished. I think we should increase the max width of the DCAF website site-wide. I probably set a max width 18 months ago, and I set it too narrow. I'm not sure what it is now, but it could be set to 1600 as a max-width. After it hits max-width, content should center and margins should increase. 

LMK if you have questions!

![screen shot 2017-06-05 at 8 22 24 pm](https://cloud.githubusercontent.com/assets/6223901/26808732/f43c720c-4a2c-11e7-9f38-f732795e99a3.png)

**Comment by EricSchwartz7** [comment]
I'll take this one!
