### ISSUE TITLE
Search Functionality on Admin Panel not Working

### ISSUE THREAD

**Issue by tingaloo** [DCAFEngineering/dcaf_case_management#1104]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
We would like search functionality on the user management panel. Search button returns a POST error.

* **What feature or behavior is this required for?**
Required to search for users on the ```user_management``` panel.

* **How could we solve this issue? (Not knowing is okay!)**
Fix routes or some javascript search call needs tweaking.

* **Anything else?**
See #1073

**Comment by KatSDC** [comment]
I'll tackle this one tonight!

**Comment by tingaloo** [comment]
@KatSDC Thanks for taking the dashboard, it's been left hanging for a long time. Feel free to ping if you need clarification!

**Comment by colinxfleming** [comment]
@KatSDC let me or @tingaloo  know if you run into any walls on this!
