### ISSUE TITLE
Document behavior of features within the app

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1115]
Issue template TK, but I got an email this morning asking how the call list / completed calls worked, and I'm sure that's not the only part where the 'how it works' is squirreled away in docs and pull requests somewhere. There might be a UX thing here to make this kind of useful information a little more available to CMs in the thick of it.

**Comment by lwaldsc** [comment]
I'm a little confused by what you mean here, Colin, esp around "works." Is
this how it works on the backend or what?

Is this something that should go into the manual or something that needs to
be supplementary?

**Comment by colinxfleming** [comment]
I think probably supplementary. Like, for the completed call list (the user question that sparked this), it follows this behavior:

* Someone is in your call list
* Someone has been called within the past 8 hours
* If that call resulted in a 'reached patient', they get removed from your call list as part of the nightly cleanup job that runs; otherwise they stay in your call list and pop up again

That's pretty fine-tuned behavior, but it's not clear from looking at it, and while I think having it documented in the manual is useful, it's probably also worth plopping it in front of CMs while they're working, since nobody's going to remember it in the moment.

Another example of this might be a patient's status -- why is someone No Contact and not Needs Appointment, etc. 

Another way of asking this is: What are our users asking questions about and how can we get them the right information? I figure that's one of those 'for everyone who asks there are five who don't ask' kinda things.

(Interested in team UX thoughts here.)

**Comment by mebates** [comment]
We could add tooltips to help explain things like this within the app. We could also think about an onboarding experience within the app to get people started. A great little primer: https://material.io/guidelines/growth-communications/introduction.html

**Comment by colinxfleming** [comment]
If @mebates feels good about tooltips I feel good about tooltips for sure. Here's a prelim list of things that I think would be helpful to have some explanatory text around:

* Call list
* Completed calls
* Urgent cases
* Status
* Record a new external pledge
* Resolved without assistance from DCAF

@lwaldsc can you work with @vtmeghan @deesriv to whip up some boilerplate text around these? Keep it short and sweet if you can, plan on them working like the pledge caps popup:

![screen shot 2017-08-13 at 1 51 09 am](https://user-images.githubusercontent.com/3866868/29246489-e958ae8c-7fc9-11e7-9344-9a5b6a7b9099.png)

Once we have some boilerplate text we can tag in an engineer to implement.

**Comment by lwaldsc** [comment]
On it. I'm on the line tonight, so it's a dedicated night in for DCAF'ing. Should have them shortly for review/discussion for Meghan and Dee.

**Comment by colinxfleming** [comment]
Yes please! @lwaldsc if you're taking a shift, might not hurt to take notes on any pain points or trouble spots you run into and popping them in separate issues. 

(cc @mebates about Lisa being on the line this week, not sure if there's anything that's been kicking around team design worth flagging)

**Comment by lwaldsc** [comment]
Paging @deesriv @vtmeghan @NerdyGirl537 to the red courtesy phone.

- Call list
This sortable list is used to keep track of patients to call back during your shift. Use the search to populate it.

- Completed calls
This is a list of patients you have already called tonight.

- Urgent cases
These patients have been marked urgent. This list is shared across all case managers working on a single line.

- Status

No Contact Made: No one from DCAF has spoken to the patient. 
Needs Appointment: A patient does not have a set appointment date.
Fundraising: A patient is in the process of securing their funding. 
Pledge Sent: A PT has their fundraising confirmed and DCAF has sent a pledge.
Resolved Without DCAF:  A PT has resolved the pregnancy without a DCAF pledge. 

- Record a new external pledge
To record a pledge from another abortion fund, choose the fund from the dropdown menu, enter the amount of the pledge, and click Create External Pledge.

- Resolved without assistance from DCAF
This status indicates a patient does not require our services any longer.

**Comment by deesriv** [comment]
@lwaldsc <https://github.com/lwaldsc> @vtmeghan
<https://github.com/vtmeghan> @NerdyGirl537
<https://github.com/nerdygirl537>  @alisonnjones tagging CM and data
friends!

These look awesome to me! Thank you Lisa. Are there other categories we
would want mouseover things for? Just looking, I couldn't find any, but in
the CM script we have tiny explainers for that the demo data questions can
sound like for each category. Would we want to add those here? Might help
with data entry errors. Here is what I have:

*Patient name *

(Can you spell that for me please?  I want to make sure I get it right on
this form.)

*Age*

*Gestational age *

(I got from your message that you’re about xx wks along.  Is that based on
a visit with a doctor and an ultrasound, or just off your last menstrual
period?  [if period, verify when that was])

*Race *(And your race or ethnicity, if you’re comfortable answering?)

*Patient’s City, County *(And what town/county are you living in?)

*Appt Date (if no appt skip next 3 questions)*

*Clinic  *

*Clinic location*

*Total Price*

*Insurance Status/Type *(Do you have any insurance coverage or medical
assistance?)

*Income * (If you know either on a weekly or monthly basis how much you
receive/bring in?)

*Household size *(And how many people currently live in your household?)

*Employment Status *

(And are you currently working? If so, full time, part time? Are you a
student?)

*Referral Source* (How did you find out about us?)

*Patient Contribution *

(How much do you need to be able to afford the current cost of the
procedure? Do you have anything so far?)

**Comment by alisonnjones** [comment]
wow i love everything about the mouseover tooltips. can't think of anything else to add at the moment (so comprehensive!) but i'll noodle on it more.

**Comment by colinxfleming** [comment]
Going thru email for awhile back and found a request for better information about what stuff on the clinic edit pages do, so leaving that here as well.

**Comment by colinxfleming** [comment]
Promoting to active. Most immediate task here is to add tooltips in the style of the pledge guidelines  tooltip (shows up above `Pledge Amount` under abortion information in the edit patient view) for the items @lwaldsc outlines -- Call List, Completed Calls, Urgent Cases, Status, New External Pledge, and Resolved Without Assistance.

**Comment by colinxfleming** [comment]
(Please throw as much of this stock text as you can in helper methods.)
