### ISSUE TITLE
Pledge limit tool tip needs to be changed for Baltimore

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#1119]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Change the pledge cap tool tip for Baltimore.

* **What feature or behavior is this required for?**
Changing DC's cap limit to Baltimore's:

* **How could we solve this issue? (Not knowing is okay!)**
Change some text, kay?

Baltimore:
9 weeks - 12.6 weeks gestation: $100 max
13 weeks - 19.6 weeks gestation: $200 max
20 weeks - 23.6 weeks gestation: $300 max
23.6 weeks +: $500 max

* **Anything else?**
Katmai Bear Cam is back! http://explore.org/live-cams/player/brown-bear-salmon-cam-brooks-falls

**Comment by colinxfleming** [comment]
Let's add a config for this once the config model PR gets in.

**Comment by colinxfleming** [comment]
Config PR is in, this is ready to go!

**Comment by colinmcglynn** [comment]
I can grab this
