### ISSUE TITLE
Addressing Unknown Data Fields 

### ISSUE THREAD

**Issue by alisonnjones** [DCAFEngineering/dcaf_case_management#1127]
When exporting patient data using the CSV download tool you'll see that a significant amount of the input fields are blank. What I'd like to figure out if whether these fields are blank because they are unknown at that point in the cm process, or if they are blank because of how the inputs are presenting in the download. 

I'd like to propose that we add "unknown" as an option to the following input fields in DARIA (Age; Race/Ethnicity; Employment Status; Minors in Household; Adults in Household; Income; Insurance; Referred By; Appointment Date; LMP at intake; Clinic; Abortion Cost; Patient Contribution; NAF Pledge; DCAF Pledge). The CM would need to change the "unknown" selection to the correct information whenever they finish the intake process/get the answer to those questions. Right now, it's difficult to tell whether those fields were left blank intentionally or unintentionally, and this is a major complication for any data analysis we'd like to do. If we are able to train CMs to use an "unknown" option as a placeholder, we will have a fuller picture of what patients are still in the cm process and it will help us to look at drop off rates and patterns. 

For fields like Urgent and Spanish, I'd like to find out whether there is a way for us to use binary switch so that if the cm doesn't mark them true, they automatically register as false. 

Also, I want to flag two issues that have come up when exporting the data. 

1. Although the input field in DARIA is listed as "Race/Ethnicity," the export contains two columns ("Race/Ethnicity" and "Race or Ethnicity"). For some reason, "White/Caucasian" is only present in the column labeled "Race or Ethnicity." I believe the blank fields under the Race/Ethnicity column in the export do contain White/Caucasian inputs, but there might be an issue with how it's presenting in the export. 

2. In addition to containing duplicative/split columns for ethnicity, there are also two columns for employment status. One column header presents as "Employment Status" and the other reads "Employment status". Not sure the genesis of this change in DARIA, but it would be helpful to get more context on why these fields split and appear twice in the CSV export file. 

Let me know if I can help clarify any of these points. Thank you!

**Comment by colinxfleming** [comment]
I'd like @cmgiven 's expert opinion on analysis of unknown data. Also interested in the datakind team's thoughts, though I don't know their github handles, especially since they've gone thru our data before. My assumption would be that people marked nil are effectively 'unknown' for purposes of analysis, but I don't know what the analytics appropriate action to take here is, so I defer to the experts.

A change is going to come for the language fields in #1138, which I think will render that concern moot.

The duplicates are definitely a bug (good catch!) and filed to #1139, so we can track that independently.

**Comment by alisonnjones** [comment]
Let's talk tonight! I had a good discussion with the cm team about this,
and we have some other ideas for getting at the problem.

**Comment by alisonnjones** [comment]
Hi @colinxfleming @lwaldsc  @NerdyGirl537 ! I have another set of questions/flags for you about the CSV export - 

1. The "Date of Check" field on the pledge fulfillment page in DARIA does not show up in the CSV export. Can we add this to the export on the back end so we are able to see the date of check information in the CSV pull?

2. The data fields on the pledge fulfillment page in DARIA do not match the ones exported as columns in the CSV file. For example "Weeks Along at Procedure" shows up as "Gestation at procedure in weeks" (I think). Also, the CSV file pulls a "Procedure Cost" column, but there isn't  a space on the fulfillment page on DARIA to enter that info. I think it's just a duplicate of "Abortion Cost" from the Abortion Information page in DARIA?

3. If we use the accounting tool under Admin tools in DARIA to search and find clients to input fulfillment data, is there any reason why that data wouldn't save or would be fractured? We will test this out, but I wanted to see if there was a reason we shouldn't be using the accounting tool to search clients and input fulfillment data. 

4. If the pledge fulfillment information (clinic, DCAF pledge amount, etc.) doesn't match what is on the pledge form, how do we reconcile this? Do we have to resend a pledge in the system with the correct info? (I expect this won't be much of an issue in the future since it's auto-generated from this point on.)

5. There are some profiles where the pledge has been fulfilled but the status at the top of the page says "pledge sent." Any insights here? Happy to point you to an example.

6. Is there any reason why we shouldn't put the check number in DARIA? I know this field was left blank in the past.

THANK YOU!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by colinxfleming** [comment]
Down the line:
* Weird that date of check isn't pulling. I'll take a look and see what the deal is there. It's been a null field until recently due to a surprise bug, a fix for that should deploy soon-ish.
* Yeah, it looks like there's some discrepancy there on `Gestation at procedure in weeks`, and possibly also `Procedure cost`. I'll figure out what's up and open a ticket.
* The Accounting tool isn't really set up yet, I wouldn't use it until we build out the workflow. I will disable that nav link to make sure nobody stumbles upon it accidentally. Unfortunately have to recommend entering fulfillments by individual search for the time being, though @eheintzelman spun up some great designs for that which are in the list.
* Pledge fulfillment status has an open PR that should be in production before the end of August.
* I don't think there's a reason not to enter check date but it's probably a joint call between you and accounting, recommend you confer with Crofoot on how exactly you'd like to handle that.

**Comment by colinxfleming** [comment]
@alisonnjones are there any discrete steps to take here engineering/app side? If not can we spin some stuff into the DARIA analytics repo and close this here?

**Comment by alisonnjones** [comment]
- Weird that date of check isn't pulling. I'll take a look and see what
   the deal is there. It's been a null field until recently due to a surprise
   bug, a fix for that should deploy soon-ish. *Can you confirm that this
   is pulling now?*
   - Yeah, it looks like there's some discrepancy there on Gestation at
   procedure in weeks, and possibly also Procedure cost. I'll figure out
   what's up and open a ticket. *Is the difference that procedure cost is
   what's logged during initial intake/pledge sent, and gestation is what's
   entered during pledge fulfillment?*
   - The Accounting tool isn't really set up yet, I wouldn't use it until
   we build out the workflow. I will disable that nav link to make sure nobody
   stumbles upon it accidentally. Unfortunately have to recommend entering
   fulfillments by individual search for the time being, though
   @eheintzelman <https://github.com/eheintzelman> spun up some great
   designs for that which are in the list. *What's the status on the
   accounting tool?*
   - Pledge fulfillment status has an open PR that should be in production
   before the end of August. *This is closed, right?*
   - I don't think there's a reason not to enter check date but it's
   probably a joint call between you and accounting, recommend you confer with
   Crofoot on how exactly you'd like to handle that.* I think we'd like to
   include it. Can you confirm that it's pulling this now?*

**Comment by colinxfleming** [comment]
Down the line:

* Date of check appears to be pulling. If problems persist on this please open another ticket.
* I'll be opening up an issue for procedure cost fulfillment/abortion cost pledge soon -- team braf also highlighted this as a concern. If gestation at procedure in weeks is a problem still please open up an issue for it with step by step instructions to recreate.
* Accounting tool ticket is represented in https://github.com/DCAFEngineering/dcaf_case_management/issues/858 and another issue or two. That linked one is the one to watch.
* Pledge fulfillment status is implemented.
* Check number is also pulling in the export CSV.

**Comment by colinxfleming** [comment]
@alisonnjones are there any actions to take here? Would love to be able to close this.

**Comment by alisonnjones** [comment]
Yeah sounds like we're set to close then since we're opening separate
tickets for the other outstanding issues. Thanks, Colin!

**Comment by colinxfleming** [comment]
Thanks @alisonnjones !
