### ISSUE TITLE
Patient and pledge trends

### ISSUE THREAD

**Issue by cmgiven** [DCAFEngineering/dcaf_case_management#1130]
* **What are we trying to do?**

As a DCAF board member, I would like to see trends in patients contacted, pledges sent, pledges fulfilled in order to understand when there are periods of high or low demand.

* **What feature or behavior is this required for?**

Understanding seasonality in demand is a first step toward DCAF leadership being able to adjust weekly budgets in response to that demand while ensuring they are on track for the annual budget (see #1132).

* **How could we solve this issue? (Not knowing is okay!)**

The data center currently shows patients and pledges for the current week, current month, and year to date. Perhaps we could be supplement this with charts that show data for the current year, perhaps relative to the year ago (as that information becomes available in the app's second year).

* **Anything else?**

**Comment by colinxfleming** [comment]
Moving this to the `dcaf_analytics` repo in https://github.com/DCAFEngineering/dcaf_analytics/issues/1 since this is primary an analytics team ask. (Charting / productizing we can explore once the analytics side is looking good.)
