### ISSUE TITLE
Support flexible weekly budgets

### ISSUE THREAD

**Issue by cmgiven** [DCAFEngineering/dcaf_case_management#1132]
* **What are we trying to do?**

As a DCAF board member, I would like to adjust weekly budgets in order to better accommodate periods of high demand, while understanding how these changes will affect my annual budget.

As a case manager, I would like to have flexible weekly budgets in order to better accommodate periods of high demand.

* **What feature or behavior is this required for?**

Case managers and providers have observed periods of high and low demand. DCAF leadership would like to be able to respond to fluctuating demand by adjusting budgets, ensuring a consistent experience regardless of the time of year. This can only be done, however, with a careful eye toward how mid-year decisions will affect the annual budget.

* **How could we solve this issue? (Not knowing is okay!)**

We need to analyze historical data to validate the anecdotal observation of demand fluctuation and to understand whether there is a predictable seasonality to demand.

Within the app, we would need to create an interface for adjusting weekly budgets, ideally that could help inform budget decisions by showing progress on the annual budget.

This might also affect how case managers behave and require changes to their interface.

* **Anything else?**

**Comment by mdworken** [comment]
I'd like to take ownership of this as it goes with what I'm hoping to do on the analytics side.

**Comment by colinxfleming** [comment]
@mdworken I don't know if we're ever going to implement a Real Historical Sense of this in-app, so it might behoove us to port this issue over to https://github.com/DCAFEngineering/dcaf_analytics and have any relevant code checked in there. thoughts?

**Comment by colinxfleming** [comment]
I'm gonna port this over to the analytics repo, since there will almost definitely not be a rails solution for this work.
