### ISSUE TITLE
Move checkbox to same line as label

### ISSUE THREAD

**Issue by eheintzelman** [DCAFEngineering/dcaf_case_management#1135]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Clean up design for checkboxes and labels on Abortion Information tab

* **What feature or behavior is this required for?**
Eliminates confusion over which label goes with which checkbox

* **How could we solve this issue? (Not knowing is okay!)**
Move checkbox to same line as label (checkbox on left; label on right).  See style of the checkboxes/labels on the Patient Information page for reference. 

* **Anything else?**
LMK if you need a picture!

**Comment by colinxfleming** [comment]
Looks like these:

![screen shot 2017-07-18 at 11 25 39 pm](https://user-images.githubusercontent.com/3866868/28349361-7399a27c-6c10-11e7-812c-5daebcde98e2.png)

**Comment by EricSchwartz7** [comment]
On it!
