### ISSUE TITLE
Remove duplicate fields from export

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1139]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

We rigged up a nice export for the analytics team, but it's got some duplicate fields in it that we should remove to make sure our analysts don't go crazy. 

* **What feature or behavior is this required for?**

Clean data!

* **How could we solve this issue? (Not knowing is okay!)**

Remove one of the `Race/ethnicity` duplicate fields and `employment status` duplicate fields from the `CSV_EXPORT_FIELDS` hash in `app/models/concerns/exportable.rb`. Your choice which one!

* **Anything else?**
 
Stems from @alisonnjones ' flag in #1127

**Comment by SamuelLangenfeld** [comment]
Sent in a pull request for this issue.
