### ISSUE TITLE
Update render_async gem so reports load, hopefully

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1140]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Get reports to render asynchronously, with nonces!

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**

Run `bundle update render_async` and add `nonce: content_security_policy_script_nonce` to the render_async stuff in `app/views/reports/index.html.erb`. (The nonce is required so it's whitelisted by our content security policy.)

* **Anything else?**

See #1095 , #1009

**Comment by tingaloo** [comment]
Gave this a shot. Doesn't output still.
generated JS
```
    (function($){
      $.ajax({
          url: "/reports/monthly?nonce=fZxve0IQtLq1O8WvYOgj1gomqI9SRgOPgOX%2B4BaiYM0%3D",
        })
        .done(function(response, status) {
          $("#render_async_45eedc3c471500490661").html(response);
        })
        .fail(function(response, status) {
          $("#render_async_45eedc3c471500490661").html(response);
        })
        .always(function(response, status) {
          $("#render_async_45eedc3c471500490661_spinner").hide();
        });
    }(jQuery));
  
  ```

console errors still show
```Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'nonce-fZxve0IQtLq1O8WvYOgj1gomqI9SRgOPgOX+4BaiYM0='". Either the 'unsafe-inline' keyword, a hash ('sha256-+PC+Kf6qxwFk9MeuRMDmsALBNWNX473zplWkiVYhJgY='), or a nonce ('nonce-...') is required to enable inline execution.```

The nonce values differ from each other, not sure what to make of it.

**Comment by colinxfleming** [comment]
Do me a solid and spin up a WIP PR?
