### ISSUE TITLE
Write data dictionary

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1142]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Write a data dictionary for the analysts.

* **What feature or behavior is this required for?**

Documenting common questions so the analysts can work without asking engineering!

* **How could we solve this issue? (Not knowing is okay!)**

We should document the fields in the models in a markdown document in `/docs/`. It should serve as a roadmap to the patient model and how it tracks its own information, as well as calls, ext pledges, and fulfillments.

Something like this would work:

**Field**: Description of the field. (Not/Exportable.)

so e.g.:

**Insurance**: The patient's insurance, if any. (Exportable.)
**Alt phone**: An alternate phone number at which the patient is reachable. (Not exportable.)

* **Anything else?**

nope!

**Comment by colinxfleming** [comment]
@lwaldsc can I tag you in on this? I think starting with just straight up taking an export and writing down what all the columns mean would get us a huge part of the way there.

**Comment by lwaldsc** [comment]
![](http://3.bp.blogspot.com/-qUH2sD4GWB0/UUn5xBphLjI/AAAAAAAAA2o/MMYWv7n8sNw/s1600/thumb-up-terminator+pablo+M+R.jpg)

**Comment by lwaldsc** [comment]
First attempt here. Edits and suggestions welcome @NerdyGirl537 @lomky 
https://github.com/DCAFEngineering/dcaf_case_management/blob/master/docs/DATA_DICTIONARY.md

**Comment by lomky** [comment]
I think we export an age range generated from the age, rather than the age itself. Otherwise my first pass reading, looks good! :100:

**Comment by colinxfleming** [comment]
Yeaaahhhh this is awesome. Excellent descriptions of the moving parts and I think the analytics team is going to set off fireworks in celebration. A few notes on my pass:

* I think a note somewhere about what the 'reported by' options mean might be helpful. Can definitely see someone being being not sure of the distinction between CM reported and patient reported on first glance. 
* We're currently not exporting `special circumstances`. 
* Description of the `line` field is spot on! Nicely done.
* We're exporting voicemail pref at present.

After @NerdyGirl537 checks in with her thoughts let's call this good to go. 

Thanks for the quick turnaround!

**Comment by NerdyGirl537** [comment]
Ok.  Did a quick review.  Looks great.

**Comment by colinxfleming** [comment]
@lwaldsc go ahead and close this out when you've got it up to speed. Thanks again for handling this so quick!

**Comment by lwaldsc** [comment]
![](http://2.bp.blogspot.com/-PXqkfd9uTzc/VZ-UnbLh8qI/AAAAAAAAG9E/XRJnQpWqm6I/s640/The-Terminator-Arnold-1.jpg)
