### ISSUE TITLE
Simple language change in Special Circumstances 

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#1160]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Making our language less ableist!

* **What feature or behavior is this required for?**
Change "fetal anomaly" to "fetal diagnosis" in Special Circumstances checkboxes.

* **How could we solve this issue? (Not knowing is okay!)we.
Change some text.

* **Anything else?**
https://youtu.be/lnu9vTSLMXo

**Comment by colinxfleming** [comment]
I'm pro making this but I feel like we've switched it back and forth a time or two at this point (last july/aug/sept if I remember right). Something to look at just to make sure there wasn't some other reason for it. Thanks for flagging @lwaldsc !

**Comment by lwaldsc** [comment]
@colinxfleming Huh. You're totally right. Sorry about that. 

Someone mentioned it last night at the DCAF meeting and said DARIA still said anomaly. Couldn't log in to Daria at the time, so just took their word for it.

DISREGARD THIS MISTAKE! PLEASE DO NOT SHAME ME FOR MY INACCURACY!

**Comment by colinxfleming** [comment]
My favorite kind of problem is 'one we've already fixed!' !
