### ISSUE TITLE
Upgrade omniauth-google-oauth2

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1171]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Keep our oauth libraries up to date. (See the Gemfile for the particular two.)

* **What feature or behavior is this required for?**
Google SSO

* **How could we solve this issue? (Not knowing is okay!)**
Probably run back thru the gem installation and setup, and remove any other setup.

* **Anything else?**
The oauth library bump in #1123 busted SSO. Reverted in #1170 and d440abb . This here seems to be the root of the problem: https://github.com/intridea/omniauth-oauth2/issues/81

**Comment by colinxfleming** [comment]
(While we're in here, we should probably fix the associated tests in `test/controllers/omniauth_callbacks_controller_test`.

**Comment by colinxfleming** [comment]
Marking active. We're a little out of date here and I'd love to bump this.

**Comment by colinmcglynn** [comment]
It looks like omniauth-google-oauth2 is locking down the omniauth-oauth2 version it uses so I think we can upgrade omniauth-google-oauth2 without running into the original omniauth-oauth2 issue https://github.com/zquestz/omniauth-google-oauth2/issues/204
