### ISSUE TITLE
Dates should be expressed consistently everywhere

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#1172]
We are displaying dates in different ways all over the app. (Appointment date, Procedure Date, Date of Check) They should be displayed consistently. 
Please make it consistent across the site: MM-DD-YYYY

Additionally, the date entry behavior should be the same - our preferred solution is tabbed input with the option for a calendar date picker, with structured entry. (match the behavior of "Date of Check" field in Pledge Fulfillment section)

Good catch @eheintzelman!

**Comment by colinxfleming** [comment]
@eheintzelman can I by chance get an example of what you'd like a tabbed date input with option for datepicker to look like?

**Comment by eheintzelman** [comment]
Check out the 'date of check' field on the pledge fulfillment tab. You can model this, except change the slash to a dash.

**Comment by colinxfleming** [comment]
Fixed via #1088
