### ISSUE TITLE
What's the knapsack gem's problem?

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1177]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Run tests in CI efficiently by splitting our tests onto parallel boxes in Circle. This used to be okay via something and then they started recommending the knapsack gem, but now THAT is causing some sketchy segfaults.

* **What feature or behavior is this required for?**
Running CI tests efficiently (meaningful, since we deploy to sandbox via CI)

* **How could we solve this issue? (Not knowing is okay!)**
Investigate the segfaults and come up with a solution that lets us continue splitting the test suite among boxes. Even is nice but not necessary. 

* **Anything else?**
nope!

**Comment by DarthHater** [comment]
![image](https://user-images.githubusercontent.com/5544326/29212268-7307e89c-7e52-11e7-81f2-c669bb3d88d9.png)

**Comment by colinxfleming** [comment]
This is resolved.
