### ISSUE TITLE
Add timestamp to 'patient saved' flash message

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1179]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
When PatientsController#update saves some data, it flashes a 'Patient saved!' message in green, which is nice. Let's add a timestamp to that of `MM-DD-YYYY HH:MM A/PM` to give folks a heads up about what the current status is.

* **What feature or behavior is this required for?**
Patient saving enhancements.

* **How could we solve this issue? (Not knowing is okay!)**
Pretty much just like above!

* **Anything else?**
Nope!

**Comment by SamuelLangenfeld** [comment]
I'll get on this issue.
