### ISSUE TITLE
Updated CM user guide

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#1187]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Update our CM user guide because I haven't since January and we've done a lot of cool ass shit since then.

* **What feature or behavior is this required for?**
Just a few folks looking over the updated version for anything I may have left out or that is incorrect or outdated!

https://docs.google.com/document/d/1YoSqjpIpjgHZcno2JjWq1erryNQNFyr3YPqNBEAhWhs/edit?usp=sharing

* **How could we solve this issue? (Not knowing is okay!)**
Take a second to scroll through.

* **Anything else?**
Shoutout to my coworker, [Giant Bei Bei](https://www.youtube.com/watch?v=7LM9CuEHZ3Q), for all his help and support while working on this during company time (it's a very slow Friday).
![20170811_161658](https://user-images.githubusercontent.com/10578608/29230694-0d776b0a-7eb2-11e7-88d8-686b4a7330e4.jpg)

Tagging in @colinxfleming @alisonnjones @NerdyGirl537 @vtmeghan @deesriv + anyone who wants to give it a look!

**Comment by colinxfleming** [comment]
Reviewed, looking sharp! Left comments in doc.

**Comment by colinxfleming** [comment]
@lwaldsc did you merge these comments into the master document? Can we get this closed?

**Comment by lwaldsc** [comment]
Updated and sent to CMDs.

http://www.instantrapairhorn.com

**Comment by colinxfleming** [comment]
Got notice from team CM that new guidance is out in the world, declaring victory.
