### ISSUE TITLE
Move language to a config

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1189]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Languages options should be settable by funds instead of us, so let's make this a config.

* **What feature or behavior is this required for?**

Removing engineers from day to day configuration changes

* **How could we solve this issue? (Not knowing is okay!)**

IIRC, by modding the constant in `app/model/config` and adjusting whatever helper populates the dropdown.

* **Anything else?**
nope!

**Comment by colinmcglynn** [comment]
I'll take this

**Comment by colinmcglynn** [comment]
Closed by https://github.com/DCAFEngineering/dcaf_case_management/pull/1234
