### ISSUE TITLE
Add a tooltip for 'why is this person this status'?

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1192]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Add an explanation for what our statuses mean.

* **What feature or behavior is this required for?**

Not confusing CMs about what our engineering terms mean.

* **How could we solve this issue? (Not knowing is okay!)**

In the patient dashboard at `app/views/patients/_patient_dashboard`, there's a thing that populates status. We should add a tooltip to that with some boilerplate language, similar to how the pledge limits tooltip works. The boilerplate language should go in the actual statusable concern at `app/models/concerns/statusable`.

Boilerplate language should probably read something like `This patient is marked #{status} because #{reason}.`

* **Anything else?**

nope!

**Comment by lwaldsc** [comment]
Love this idea!

**Comment by colinxfleming** [comment]
Dupe of #1115
