### ISSUE TITLE
Turn off password autocomplete

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1196]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Increase the security of our app by turning off autocomplete on our sign in form.

* **What feature or behavior is this required for?**
Keeping our app security flag free, even for minor stuff!

* **How could we solve this issue? (Not knowing is okay!)**
Pop into the devise form in `app/views/sessions/new` and add `autocomplete='off'` to the text fields.

* **Anything else?**
Raised by a ZAP scan in #394

**Comment by valeriecodes** [comment]
I got this.

**Comment by colinxfleming** [comment]
🦅

**Comment by valeriecodes** [comment]
https://github.com/DCAFEngineering/dcaf_case_management/pull/1228
