### ISSUE TITLE
Fix cache-control and pragma http header set for a few endpoints

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1197]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Prevent caching on certain controllers in the headers. Exact alert content is below:

![screen shot 2017-08-12 at 11 41 20 pm](https://user-images.githubusercontent.com/3866868/29245933-e2540bca-7fb7-11e7-9a98-7aa0601cc7e9.png)

![screen shot 2017-08-12 at 11 41 27 pm](https://user-images.githubusercontent.com/3866868/29245936-e53b8250-7fb7-11e7-8736-d67e50fdef26.png)

* **What feature or behavior is this required for?**
Removing security flags, even very scoped and small ones!

* **How could we solve this issue? (Not knowing is okay!)**
Try to adjust our caching behaviors so that we prevent caching via headers at the endpoints in the screenshot. 

* **Anything else?**
Stems from ZAP scan in #394

**Comment by valeriecodes** [comment]
I can grab this.
