### ISSUE TITLE
DARIA BRAAF rollout omnibus thread

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1200]
Starting an omnibus thread for spinning up a new instance of DARIA for our friends down the road -- want to make sure we have a place to put anything that arises as we go through this process with them.

@NerdyGirl537 if there's anything we need to get out ahead of please post in this thread! Any timeframe would also be killer. Thanks much!

**Comment by lwaldsc** [comment]
Is this for BRAAF rather than RRF or both funds? Should we edit the issue subject just to keep things clean in case RRF wants it?

**Comment by colinxfleming** [comment]
oh, yeah, this is braaf. Editing to reflect

**Comment by NerdyGirl537** [comment]
@lwaldsc @colinxfleming I just sent a note to Toby.  Last time I heard from her, she told me she was waiting for Tannis (another board member) to get back from vacation. I'll let you know when I hear from her.

**Comment by colinxfleming** [comment]
Per #1214 this is game on! @NerdyGirl537 do they have a start date? When would they like to start entering data?

**Comment by NerdyGirl537** [comment]
@colinxfleming Needing you to confirm you are good with 9/25 or if we need to push it to Oct.

**Comment by colinxfleming** [comment]
I'm good to flip the switch so they can start entering data on or around 9/25, though I might be out of pocket for much of that week due to a potential trip.

Someone who isn't me should probably spin up this server in question so that this knowledge isn't completely siloed in my head, I'll coordinate that with the rest of the team.

@alisonnjones this'll be another $7/m on our heroku bill. Are there any admin concerns or paperwork we need to handle before spinning them up a server? We should consider their official billing start-date to be 10/1 for simplicity (and because we can do data entry on the free server).

**Comment by alisonnjones** [comment]
Yes, we need them to sign a contract and speak with our legal team before anything goes live. @NerdyGirl537 please let me know when we need to send them contract so that we're good to go with the 9/25 start date/timeline. the 10/1 billing start date sounds good to me. @colinxfleming  do you remember if you connected BAF with Emily? How does that invoicing work for BAF?

**Comment by NerdyGirl537** [comment]
@alisonnjones send any time.  They are excited and ready to get started. Let's check that one off as an easy kill.

**Comment by colinxfleming** [comment]
I don't remember where the BAF process left with Emily. I assume they paid up but I was well off the board at the point at which they'd have cut a check. (Procedure as spelled out in the contract is pretty much 'Cut an annual check at the beginning of the new FY'.)

@alisonnjones and @NerdyGirl537 please keep this thread posted on progress to getting legal squared away. Thanks much for dunking on that.

**Comment by colinxfleming** [comment]
Spun up a working version via new pushbutton method in #1251

**Comment by colinxfleming** [comment]
AFAIK we've got paperwork, they've got a server, and the remaining stuff is them doing the transition. @NerdyGirl537 can you post the status of that and close if there are no next steps for engineering?

**Comment by NerdyGirl537** [comment]
The site is live. I've sent a note to Tannis about the data import but no joy. On my task list for this week to check in with them.

**Comment by colinxfleming** [comment]
@NerdyGirl537 can we close this? They're all set at this point, no?

**Comment by NerdyGirl537** [comment]
I'll take a look this weekend to be sure.

**Comment by colinxfleming** [comment]
Tweaks requested by BRAF:

* If this box is left unchecked[ Are we actively working with this clinic?] in Clinic Management, clinics show in the drop down list in Abortion Information as (Not currently working with DCAF). Should be changed to FUND
* Change language on pledge generator if pledge generator is not being used

**Comment by alisonnjones** [comment]
@NerdyGirl537 are we logging customization requests anywhere to revisit at the end of maintenance mode? sorry if we are and I missed it

**Comment by NerdyGirl537** [comment]
@alisonnjones  We haven't really received customization requests. Right now, most requests are just to update Fund name or Fax info.

**Comment by alisonnjones** [comment]
ahh, no need then. Sounds good to me!

**Comment by colinxfleming** [comment]
AFAIK this is all resolved so I'm closing. We can create new tickets if things pop up again.
