### ISSUE TITLE
Call List 'remove all' button for dashboard

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#1202]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Make a button to remove all calls from your call list. 

* **What feature or behavior is this required for?**
If the call list does not purge properly, it's a pain to remove each call by hand. 

* **How could we solve this issue? (Not knowing is okay!)**
`¯\_(ツ)_/¯ `

* **Anything else?**
I tried to put an ascii nyan cat here but markdown hates joy.

**Comment by colinxfleming** [comment]
Feature request sounds good but I'm kinda interested in why the list didn't purge properly. Might be worth digging into that too, let's be sure to file a issue for that if it happens tomorrow?

**Comment by colinxfleming** [comment]
Tagging UX for input on where we should put this button, then turning over to backend.

**Comment by lwaldsc** [comment]
Yeah I was wondering that too, to be honest, but it's been a while since I
used DARIA, so figured that's how we made it.

Will do tomorrow if it's still wonky.

**Comment by mebates** [comment]
I would go with a simple destructive link. Not a primary action; doesn't need a button.
I would also include a dialog confirmation: "Are you sure you want to remove all patients from your call list? This action cannot be undone." Yes/No

<img width="892" alt="screen shot 2017-09-11 at 7 17 55 pm" src="https://user-images.githubusercontent.com/6223901/30301008-f3d3f3e4-9725-11e7-8454-4223d196d713.png">

**Comment by lwaldsc** [comment]
$$$$$$$$$$$$$$$$$$$$
