### ISSUE TITLE
Patients still marked urgent after pledge sent

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#1203]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Need to revisit this because patients are still marked urgent after a pledge is sent. Refreshing the dash doesn't remove them.

* **What feature or behavior is this required for?**
My sanity

* **How could we solve this issue? (Not knowing is okay!)**
Looks like it has something to do with: https://github.com/DCAFEngineering/dcaf_case_management/pull/665

* **Anything else?**
![screen shot 2017-08-15 at 8 57 36 pm](https://user-images.githubusercontent.com/10578608/29343168-6f0196e0-81fd-11e7-97e1-46ceb976d98a.jpg)

**Comment by colinxfleming** [comment]
Legit might start redacting everything with pictures of Mr. Worldwide from now on
