### ISSUE TITLE
Call list not clearing

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#1209]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Call list isn't clearing the way I think it's supposed to. We should probably take a look at that.

Probably has to do something with: https://github.com/DCAFEngineering/dcaf_case_management/pull/570

* **Anything else?**
Here's "Bad N Boujee" over Earth, Wind & Fire's "September" https://twitter.com/RicWilson/status/897514438517043200

**Comment by colinxfleming** [comment]
I think we have this resolved, or at least extremely mitigated, via #1336 . @lwaldsc let me know if this is still a problem next time you take a shift, but I'm going to close for now.
