### ISSUE TITLE
Patient information saved pop-up 

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#1210]
If possible, can we have the patient information successfully saved pop up not force everything else on the page down? It's not a make or break feature, but it's kind of irritating while trying to input patient data.

**Comment by tingaloo** [comment]
I can think of two ways, either we allocate space up top reserved for notifications or have the notifications plop over.

**Comment by colinxfleming** [comment]
@tingaloo I think either way is great, probably slight preference for plop over unless it's notably harder. 

Tagging frontend and active, I think this would be a nice improvement.
