### ISSUE TITLE
Create & Document our Long Term Maintenance Plan

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1223]
* **What are we trying to do?**

Come up with our plans for what the long term maintenance mode looks like, and document it.

* **What feature or behavior is this required for?**

Long term health of the mature app.  
Being there for our awesome funds.
@colinxfleming getting more sleep!  

* **How could we solve this issue? (Not knowing is okay!)**

A solid doc with the decisions we make in this thread.  
Adding it to the readme

* **Anything else?**

Some starter thoughts:

  - how can new funds get on board? Has this changed?
  - how can existing funds request changes? Security vs important vs nice to have?
  - who has the patch pumpkin? Does it rotate?
  - how do we accept new features? Only fully tested PRs?
  - def more things

@colinxfleming @DarthHater @lomky @mebates @lwaldsc (others I'm forgetting please loop in)

**Comment by colinxfleming** [comment]
👍

**Comment by colinxfleming** [comment]
Here's my quick 

* I believe @NerdyGirl537 and @alisonnjones are the current keeper of the new fund process. I THINK there's some chatter with national that we have to have before we have a SUPER open process, but at the very least we can set up some way to get in touch with us (e.g. 'email X or hit us up on slack if you're interested in whether or not this will work for your fund').
* On existing client funds requesting changes, my inclination is again to have @NerdyGirl537 play middle-person, or to ask the DCAF board folks how they'd like to do it, and then just set that as the standard issue.
* We should spend some time tomorrow and check to make sure the comment box email works and forward appropriately. cc @lwaldsc . 

I'm pretty much totally clueless on the questions of the patch pumpkin, accepting new features, etc. I've never maintenance-moded a project before and I frankly have no idea how this is going to work, but having no idea how this was going to go didn't stop us from getting it going, so it's not going to stop us now either.

**Comment by alisonnjones** [comment]
Would love to discuss ideas for what our world will look like
post-September tonight. This includes 1) maintenance plan for DARIA for DC,
BAF, and BAF, 2) future build plan for new DARIA functionalities and tools,
3) game plan for how to strategically leverage DARIA for future roll out to
other funds.

Sound good?

**Comment by lwaldsc** [comment]
👍👍👍👍👍👍👍👍👍👍👍

**Comment by colinxfleming** [comment]
Here's my notes from the discussion tonight: 

Divided this up into three components -- engineering support / maintenance, new feature requests, and supporting client funds using our software.

* software maintenance

** heroku ate shit -- who's job is it to turn it back on? Probably core team's
** routine patching - Kat willing to put up a few hours, others also willing
** routine support requests - post to slack system for support tickets, first to find gets the pumpkin

* new feature requests and greenfield work from dcaf

** six-or-nine month iterative process where we poll users and member funds and find out what development priorities are
** when new development task comes up, the daria project lead is responsible for assembling volunteers and getting it done
** core team will continue to review pull requests

* support of client funds using our software

** lots of stuff we get from DARIA being in a heroku pipeline, such as 'turn it off and back on'
** routine support requests go thru the same process
** other funds are part of the six month user poll

**Comment by colinxfleming** [comment]
some action items
**** Write a 'how to turn it off and turn it back on again' guide
**** heroku has an option of limited controls of given apps -- investigate
