### ISSUE TITLE
Move CSV export to an async call

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1224]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

The only place in the app we're still getting memory errors or timeouts is the CSV export, which has become too big to pull. Rather than optimize the export I'd rather cheat and just move it to an async call, so it doesn't timeout in heroku after 30 seconds and we can just trust that it'll work no matter how huge it is. 

* **What feature or behavior is this required for?**

Export to CSV successfully, even after data gets massive.

* **How could we solve this issue? (Not knowing is okay!)**

Without knowing off the top of my head, here are two options:
* http://smsohan.com/blog/2013/05/09/genereating-and-streaming-potentially-large-csv-files-using-ruby-on-rails/ (streaming, probably requires more code)
* https://stackoverflow.com/questions/34729473/downloading-dynamically-generated-large-files-in-rails (activejob / background job processing -- probably requires more rigging)

* **Anything else?**

Tough one, but if you have experience doing this (especially on heroku), go for it!

**Comment by colinxfleming** [comment]
@alisonnjones for awareness

**Comment by alisonnjones** [comment]
Thanks for the notice @colinxfleming ! Do we think this issue is the reason why some folks are having trouble completing the CSV download at random times?

**Comment by colinxfleming** [comment]
@alisonnjones yeah, pretty much -- this issue aims to solve that problem.

**Comment by valeriecodes** [comment]
I can take a look at this if no one is working on it yet @colinxfleming

**Comment by colinxfleming** [comment]
@valeriecodes I'd really appreciate that a lot! To simulate the data export size I'd probably suggest seeding around 10k or 15k patients, which I think will give some idea of the wait/delay. Please let me know if I can be helpful at all.

**Comment by valeriecodes** [comment]
@colinxfleming Another possibility here is to make the CSV call on the postgres level, which I've seen speed things up a lot, but means introducing raw SQL, which is obviously less friendly. I'll try a couple things and benchmark.

**Comment by colinxfleming** [comment]
If i had to guess i would bet we could leverage the render_async gem to do
this e-z. The grimmest option is probably setting up some activejob deal.
I'm super interested in seeing what you work out for this!
