### ISSUE TITLE
Frontend styling edits for activity feed

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1232]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

I put together the activity feed div together pretty hackily in #1226  and made some guesses about how to render things, but I would love an opinion on it from someone with good design tastes and instincts. To that end, I think a quick UX once-over of the activity feed would be very helpful.

* **What feature or behavior is this required for?**

Make the activity feed look nice!

* **How could we solve this issue? (Not knowing is okay!)**

Insights from our UX friends!

* **Anything else?**

Stems from #1226

**Comment by colinxfleming** [comment]
Here's what it looks like currently:

<img width="1167" alt="screen shot 2017-09-05 at 11 02 36 pm" src="https://user-images.githubusercontent.com/3866868/30092670-52d6f6ee-928e-11e7-8941-990f480e8c51.png">

**Comment by colinxfleming** [comment]
<img width="1165" alt="screen shot 2017-09-05 at 11 04 14 pm" src="https://user-images.githubusercontent.com/3866868/30092714-8d66f7be-928e-11e7-918f-c4f82e0c0a58.png">

**Comment by lwaldsc** [comment]
Fantastic!

Would you hate me if I asked for the icons for VM and couldn't reach be different than reached? Was this a specific design decision @mebates or something we can change?

Just to make it easier for CMs to differentiate at a glance who still needs to be called.

**Comment by colinxfleming** [comment]
@lwaldsc Not a specific design decision that I can recall, and that's a pretty straightforward change. Feel free to pick something you like from this set of icons here: https://getbootstrap.com/docs/3.3/components/#glyphicons

**Comment by NerdyGirl537** [comment]
Loving this!!! and agree with @lwaldsc on the different icons. @colinxfleming maybe the envelop icon for VM and the X icon for couldn't be reached?

**Comment by lwaldsc** [comment]
I would suggest using the _earphone_ glyph for Voicemails and Could Not Reach and the _comment_ glyph for Reached. There isn't much difference between VM and CNR as far as moving the patient along in the process (and accounting for patients we cannot leave a VM for), so I don't think they need to be differentiated. 

Thoughts?

**Comment by NerdyGirl537** [comment]
Good points! I think it would also encourage CMs to keep trying those VM patients rather than going "we left a VM; they're good."

**Comment by colinxfleming** [comment]
Paging @DCAFEngineering/designers ! Knew I set those teams up for a reason. 

@lwaldsc @NerdyGirl537 I'll definitely make the glyphicon change, that's straightforward enough that we can do it in #1226 imo.

**Comment by mebates** [comment]
Are the icons interactive? If they are just a code and not something you can click, please avoid the color purple. I would also make them smaller, OR add more line spacing between each activity item, so they don't crash into each other.

**Comment by colinxfleming** [comment]
Yeah, they're just code. Let's swap them to black maybe?

More line spacing sounds great.

@serenayudon can i tag you in on these code changes?

**Comment by mebates** [comment]
50% gray should do it. If you want, you could do something more positive for a pledge sent, like a green!

**Comment by colinxfleming** [comment]
So the final changes are:

* change the icon styling to 50% gray for calls, green for pledge sent
* Add some additional line spacing between entries (maybe an additional margin of 2-5px? and see how that looks?)

Tagging frontend, let's finish this out!

**Comment by mchelen** [comment]
Should this just be styled based on the glyphicon classes, or do we want to add a class that defines the event type (call, pledge, etc)?

**Comment by colinxfleming** [comment]
Follow your heart! Im good with either

**Comment by mchelen** [comment]
Ok I gave it a try, any feedback welcome!
![image](https://user-images.githubusercontent.com/30691/31975097-fc0accb0-b8fc-11e7-98bd-3dfac6f8398e.png)
