### ISSUE TITLE
Activity feed (Add to call list) links don't work :(

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#1237]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Be able to add patients to the call list directly from the activity feed. 

* **What feature or behavior is this required for?**
It's super helpful.

* **How could we solve this issue? (Not knowing is okay!)**
Uh... make them work. Related: #1233 #1226 #1232 probably more

* **Anything else?**
Here is how you evacuate with chickens: https://twitter.com/TheBreeMae/status/905952949985091584

**Comment by colinxfleming** [comment]
There's some code in `events_helper` that powers this. The engineering task here is to get the commented out `add_link` code to work. 

Tagging backend and active.

**Comment by tedPen** [comment]
I'll take a look at this tonight.
