### ISSUE TITLE
General QA review

### ISSUE THREAD

**Issue by eheintzelman** [DCAFEngineering/dcaf_case_management#1242]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Make the design look like the mockups. 

* **What feature or behavior is this required for?**
Make it even easier to use. 

* **How could we solve this issue? (Not knowing is okay!)**
Review design overall for inconsistencies, funky stuff.

* **Anything else?**

**Comment by eheintzelman** [comment]
Sandbox
-  Left align column titles with column data (all sections in sandbox)
![image](https://user-images.githubusercontent.com/17989540/30302203-78bff7d6-972d-11e7-9ac8-022baf9d8ae7.png)
- Consider moving plus sign left, adjacent to ellipses. I'm concerned that users would potentially think the plus sign is a call to action, like the delete and call icons, instead of the indicator for showing the full note. (all sections in sandbox)
![image](https://user-images.githubusercontent.com/17989540/30302343-6b55dea2-972e-11e7-86c1-b0118cb581f8.png)

**Comment by eheintzelman** [comment]
Abortion Information tab
- Decrease the vertical spacing between these two checkboxes.  Make it consistent with the two 'enable' checkboxes on the left. 
![image](https://user-images.githubusercontent.com/17989540/30394218-6f3d7fee-9890-11e7-993e-34fb09053405.png)

Call Log
- Recommend changing 'Record new call' to a button style, since it is an action.
![image](https://user-images.githubusercontent.com/17989540/30395135-35f5be10-9893-11e7-97cd-c79883e4cf20.png)

- A button styled like this in the 'Notes' section.
![image](https://user-images.githubusercontent.com/17989540/30394766-1b92ec6a-9892-11e7-9f81-c88f78d2abf5.png)

Error proofing form fields with text input
-  Right now the text input fields are not error proof.  You can enter 'very old' in the 'Age' field, and nothing tells the users to put in a 2 digit number instead. It would be really tight if we added added some kinds of data validation and feedback to the user. Not a must have but something to consider.
- The only exception is the phone number field for saving a patient. 
- What do folks think about tackling this?  If it is a yes, I'd be happy to look into possible solutions for providing the user feedback.

Behavior of Alerts
- Great that we have a notification to the user that a patient has been saved successfully. Can we have it automatically disappear after a 5 seconds?  It's extra work for the user to have to click out of it. 
![image](https://user-images.githubusercontent.com/17989540/30395383-f458a700-9893-11e7-91bf-0f74486f4395.png)

- Anytime a change is made to the summary section the 'patient info successfully saved' alert shows up again.  Is this necessary?  Is the information so important that there should be instant notifcation that changes were made?  @lwaldsc @NerdyGirl537 what do you think? If we'd like to give the user feedback when making changes to this section, recommend positioning the feedback close to the form field that was changed. If we decide we'd like to give this feedback, can look into ways to do this.

![image](https://user-images.githubusercontent.com/17989540/30395630-c589b120-9894-11e7-85a6-ffaba9908680.png)

To be continued!

**Comment by eheintzelman** [comment]
Preferred language dropdown (located in 'patient information' tab)
- In the sandbox, English is the only choice that is showing up.  Not sure why.  I assume this should include at least Spanish and possibly other languages?

Abortion Information tab
- Can we round the 'outstanding balance' to two decimal points?  Would like to avoid this, which happened when I entered $150.90 for the abortion cost.  

![image](https://user-images.githubusercontent.com/17989540/30890295-ff00a066-a2f9-11e7-88e4-c71cabb82b18.png)

Alternatively, we could round 'abortion cost' and all pledge amounts and contributions to the nearest dollar.

- DCAF Pledge ToolTip does not function 

![image](https://user-images.githubusercontent.com/17989540/30890327-312a8b92-a2fa-11e7-9383-f260a00f4e75.png)

- What does the 'Referred to clinic' checkbox mean? No problem, if this is clear for case managers. 

Submitting Pledges

- Vertically align the text with the number.  This is located on the modals for submitting a pledge. There are 3 modals with this issue. 

![image](https://user-images.githubusercontent.com/17989540/30890842-63e8a228-a2fd-11e7-8076-fec73320d1d2.png)

- Check the button styling for the buttons in the submitting pledge modals.  Some have a light blue highlighted border. 

![image](https://user-images.githubusercontent.com/17989540/30890938-f3d164ba-a2fd-11e7-9671-7ee46787651b.png)

- After submitting a pledge, the pledge fulfillment fields show up under the patient info section.  See screenshot below. Just a bit wonky.  It goes away once you exit out of the patient and come back to it. 

![image](https://user-images.githubusercontent.com/17989540/30890604-e55de23e-a2fb-11e7-99ae-ccddce0691b2.png)

To be continued!

**Comment by NerdyGirl537** [comment]
@eheintzelman for your questions:
Language is now a pick list updated under the admin profile in the Admin Tools --> Config Management

For the abortion amount, I would recommend keeping it with 2 decimal places. I think that would work better. Just my opinion. @lwaldsc Thoughts?

The CMs know what to do with the 'Referred to Clinic' check box.

On pledge fulfillment, that only shows up if you are an admin user. The CM user doesn't see this.

**Comment by lwaldsc** [comment]
I would round to the nearest dollar. We almost never use cents.

**Comment by colinxfleming** [comment]
@eheintzelman my email just reminded me that hacktoberfest is coming, which means that a bunch of people will likely be looking to make one-off contributions such as UX fixes. In other words, keep these coming and feel empowered to get EXTREMELY nitpicky!

**Comment by colinxfleming** [comment]
@eheintzelman re the dropdown button, I think there's a path to that but it's not super clear how to break it up off the top of my head. a great flag though. Note to self to mull that one over!

**Comment by eheintzelman** [comment]
@colinxfleming My two cents (different from my initial assessment) is that we can leave the dropdown as is.  See my comment in #1249 

@lwaldsc Tried to clarify my comment about pledge fulfillment data getting wonky, above.
