### ISSUE TITLE
Design fix: Left align columns with column data

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1246]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Left align column titles with column data in `table_content` elements, like so:

![image](https://user-images.githubusercontent.com/3866868/31047181-bfd0ec02-a5d3-11e7-9442-d41348089cc9.png)

* **What feature or behavior is this required for?**

Consistent, clean design to keep our users happy.

* **How could we solve this issue? (Not knowing is okay!)**

Probably by slapping a class on the table in `app/views/dashboards/_table_content.html.erb` and then writing some CSS affecting the header row.

* **Anything else?**

You can see this element in action by logging in, going to the main dashboard at the authenticated root, and then looking at the table under Your Call List.

**Comment by TraGicCode** [comment]
I'll try and knock this out

**Comment by TraGicCode** [comment]
Should be done!

**Comment by amsourav** [comment]
#1257
