### ISSUE TITLE
Design improvement: Left-align 'show additional text' plus icon for notes

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1247]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

In our table content partial, we have a plus sign icon that displays additional text for the next note if it breaks grid. Right now it's in its own `td` cell, and we should have it inline with the text it's associated with rather than right aligning.

![image](https://user-images.githubusercontent.com/3866868/31047304-1b48738c-a5d6-11e7-8b3c-b1f31b51a988.png)

* **What feature or behavior is this required for?**

Nice and clean design, making it clearer what the button does.

* **How could we solve this issue? (Not knowing is okay!)**

In `app/views/dashboards/_table_content.html.erb`, put `plus_sign_glyphicon` in the same `td` cell as the note instead of its own. Make sure to remove the corresponding `th` in the table header.

* **Anything else?**

thanks!

**Comment by TraGicCode** [comment]
I'm on this
