### ISSUE TITLE
Design improvement: Consistent spacing on checkboxes

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1248]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

If you go to a patient edit page (by clicking on a patient name link) and then click on the `Abortion Information` link on the left sidebar, you'll see this: 

![image](https://user-images.githubusercontent.com/3866868/31047373-62bc5e8a-a5d7-11e7-82e9-b040133dc797.png)

The spacing between the checkboxes on the left and checkboxes on the right are noticeably inconsistent! We'd like to straighten them out so the stuff on the right is spaced the same as on the left.

* **What feature or behavior is this required for?**

Nice, clean design!

* **How could we solve this issue? (Not knowing is okay!)**

The code for this is in `app/views/patients/_abortion_information.html.erb`. Most likely it involves applying whatever HTML structure is on the left to the checkboxes on the right.

* **Anything else?**

thanks!

**Comment by sagar-kalra** [comment]
i would like to work on this, @colinxfleming

**Comment by sagar-kalra** [comment]
Please help me out, how to test the changes made locally?
