### ISSUE TITLE
Design improvement: Use number inputs for numbers in patient_information partial

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1249]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

@eheintzelman has pointed out that we should use number fields for numbers, and she's def right!

* **What feature or behavior is this required for?**

Clean data!

* **How could we solve this issue? (Not knowing is okay!)**

In the patient information partial (`app/views/patients/_patient_information.html.erb`) we should change text fields to numbers. Specifically, we should do this for:

* Age
* Minors in household
* Adults in household

I THINK this is as simple as changing `text_field` to `number_field` -- check the docs of our form library here: https://github.com/bootstrap-ruby/rails-bootstrap-forms/tree/legacy-2.7 

* **Anything else?**

This started as something else. See below.

<strike>
* **What are we trying to do?**

@eheintzelman has very astutely pointed out that it's kinda clunky to us a toggle-spinner-deal for dropdowns (per below), and that a downward facing chevron would be better here.

* **What feature or behavior is this required for?**

A clean design where it's clear what certain inputs are looking for, datatype wise.

* **How could we solve this issue? (Not knowing is okay!)**

Conveniently, I have no idea! I'd like to avoid some jquery-ui plugin if possible but am not opposed if that's the path of least resistance.

* **Anything else?**

When we settle on a styling, we'll want to apply this in particular to input boxes on patient information, abortion information, and pledge fulfillment tabs, as well as the create patient form.

See this comment for origins. https://github.com/DCAFEngineering/dcaf_case_management/issues/1242#issuecomment-328695235

I'm tagging as UX/question because I don't have a terribly clear strategy/path to victory on this one, and would like people's opinions.
</strike>

**Comment by eheintzelman** [comment]
After I wrote this comment in #1242, I started seeing this 'toggle-spinner' like dropdown used all over the place on other websites. So clearly, I was wrong and this is a common signifier for a dropdown. Stylistically, I prefer the simple downward chevron (as in original @mebates design), but from a usability standpoint, what we have works just great. It also looks different enough from the spinner that is currently used in a few fields (see 'Abortion Cost' field for example), and I don't imagine there will be any confusion. That's my two cents.

**Comment by eheintzelman** [comment]
Are you also looking to discuss the dropdown vs. spinner for some form fields? 

The control used for the cost fields is useful for numeric fields - quick entry by typing or option to use the spinner to increase/decrease value.
![image](https://user-images.githubusercontent.com/17989540/31106082-bf32812c-a7b6-11e7-8d7c-aff1165d7269.png)

Applicable fields:
- Age
- Minors in household
- Adults in household
- Weeks (LMP)
- Days (LMP)

**Comment by colinxfleming** [comment]
Made some edits to the issue at hand to reflect the simplified stuff, and the fact that the chevron is a wontfix. Bumping to active.
