### ISSUE TITLE
User password reset flow not letting users actually reset their passwords

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1266]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Allow users to reset passwords, if absolutely necessary, through the frontend workflow.

* **What feature or behavior is this required for?**

Allowing users to manage their own credentials, in the event that they don't want to or can't use oauth.

* **How could we solve this issue? (Not knowing is okay!)**

Go thru the following steps:
* Spin up the app, run the seeds, and go to localhost
* Click `Forgot your password?`
* Enter in `test@test.com` (the test user's email) and click `Send me password reset instructions`
* Check your rails server logs for the password reset email that would be generated -- grab the link out of there and paste it into your browser window

EXPECTED BEHAVIOR: User is taken to a password edit screen (with the route `devise/passwords#edit`)
ACTUAL BEHAVIOR: User is returned to the sign in screen

* **Anything else?**

ahhhh

**Comment by Sey1000** [comment]
I'll have a look at this!

**Comment by colinxfleming** [comment]
Thank you very much! Probably this either broke in an upgrade or we set it
up wrong. Let me know if i can be helpful as you dig in!

**Comment by Sey1000** [comment]
Ok I'm back. My guess is that something is overriding the edit password devise path skipping user authentication.. I'll do my best, but I am not sure yet if I can fix this. Update to come!

**Comment by colinxfleming** [comment]
@Sey1000 💯 💯 . If you did some digging and got nowhere, please let us know what didn't work -- that's just as helpful a lot of the time!

**Comment by Sey1000** [comment]
@colinxfleming Sorry for a late response. I started teaching on Monday and had very little time to work on it. It seems like devise passwords controller is not being able to skip authenticate_user! method, meaning it's expecting user who forgot password to sign in in order to change the password LOL
My plan for now is first poke around the configuration to see if we can quickly fix it, and if that doesn't work, make a custom method that inherits from devise passwords controller so we have more control over it and give it a bit more authority.

**Comment by Sey1000** [comment]
In the meantime, the email link was missing port of localhost (it was saying http://localhost/... instead of http://localhost:3000/...), so I added that to development environment configuration

**Comment by mdworken** [comment]
Is this still an issue? If so, could you please assign it to me?

**Comment by colinxfleming** [comment]
@mdworken you need to be in the org to be assigned stuff - just popped an invite your way.

**Comment by mdworken** [comment]
Update:

I found 2 things preventing it from working so far:
1) the route was commented out as a "Todo"
2) all unauthenticated users are redirect to sign in by the code:  
root :to => redirect('/users/sign_in')

I am continuing to dig.

**Comment by colinxfleming** [comment]
I was under the impression that we were getting it for free as part of Devise, but I could definitely be wrong about that. Might behoove us to go through this part of the devise setup again and see if we missed a step, or broke a part of the config.

Running `rails routes | grep devise` might yield some clues about what we're currently getting from devise.

**Comment by mdworken** [comment]
Update: it was a routing issue! Sending a PR once I get the chance to manually test the fix.
