### ISSUE TITLE
Turn CM Resources link into a config

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#1268]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
CM Resources link currently redirects to a production google drive link. Documents are currently stored in the drives of the individual line accounts.

* **How could we solve this issue? (Not knowing is okay!)**
Not sure. Need to consult CMDs on what they feel the best option is or how we make sure CMs are going to the right location.

* **Anything else?**
Anthony Clark's Wizard a Day is the most precious thing on the internet right now, but today's is especially precious: https://twitter.com/nedroid/status/917398416216518656

**Comment by colinxfleming** [comment]
hey @lwaldsc -- great flag, thanks for logging! Sounds like the resources link in prod for DCAF is a little more general, and we'd get some more utility about linking to a more general resource, if I'm reading you right, or should maybe rearrange things a little bit to have things in one central 'home'.

I'm going to assign this to you and have you chase @vtmeghan and the rest of Team CM for this, if that sounds good. When they decide, ping me and I'll implement.

**Comment by lwaldsc** [comment]
Yeah. Sorry I didn't give more thought to it, but on the line and just wanted to get the ticket up while I was still thinking of it. Sounds great!

**Comment by colinxfleming** [comment]
I am going to turn this into a backend issue to make this the CMD's problem; let's slap a new config on
