### ISSUE TITLE
Log event on patient create

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1270]

**Comment by colinxfleming** [comment]
@lwaldsc @NerdyGirl537 @alisonnjones when I was talking to a BAF person this evening, it occurred to me that it might be useful to include created patients (e.g. 'CM Jane Hetfield recorded patient Susie Everyteen' or something similar). Do you all think there's any utility to this?

**Comment by lwaldsc** [comment]
Are you talking in the activity feed?

I think there's definite utility but I'm afraid that's gonna really clog it
up. We create patients all the time.

Thoughts Jenn or Alison?

**Comment by alisonnjones** [comment]
Yeah, I think it could be too cluttered. But, if there was a way to
sort/peel them off if the screen got too busy, I could see this being very
useful.

**Comment by NerdyGirl537** [comment]
I'm gonna have to think on it. From a quick survey, it seems like not everything is getting logged (i.e. CMs aren't clicking on the phone icon and recording the call outcome) and it might be an easier way to find patients the CM has called that week as well.

**Comment by colinxfleming** [comment]
@NerdyGirl537 @lwaldsc can you all talk about this at the meeting this week and log whatever you decide in here? I'm good either way, so it's up to you both on the utility of this.

**Comment by alisonnjones** [comment]
I support! Let me know what you two need from me. Thanks.

**Comment by lwaldsc** [comment]
re: @alisonnjones @NerdyGirl537 consensus is "could be nice to have but not necessary feature and needs more thought to be really useful and not clogging the feed"

Jake Elliot it to revisit six months from now.

**Comment by colinxfleming** [comment]
Sounds good. I'm going to close in the interest of keeping the issue list down and if it winds up being an issue or if someone else wants it, please raise again.
