### ISSUE TITLE
Update BRAAF's name

### ISSUE THREAD

**Issue by NerdyGirl537** [DCAFEngineering/dcaf_case_management#1277]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
We need to change the display name at the bottom of BRAAF's page to Blue Ridge Abortion Assistance Fund (not Access).

* **What feature or behavior is this required for?**
To make BRAAF's website shiny.

* **How could we solve this issue? (Not knowing is okay!)**
Updating the code.

* **Anything else?**
BRAAF is super happy with this :)

**Comment by colinmcglynn** [comment]
Fortunately, that is set as an environmental variable, so I updated it on heroku, no code change required! @NerdyGirl537 I don't have a log in for BRAAF, could you double check that their name is showing up properly now?

**Comment by NerdyGirl537** [comment]
@colinmcglynn Checked out. Looks good!
