### ISSUE TITLE
Add destroy route for patients

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1279]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Once in a blue moon, CMs create duplicate patients, and a CM Director will reach out to me to ask to delete them. This doesn't happen often enough but it's a feature they should have in the unusual set of circumstances that they need it.

* **What feature or behavior is this required for?**

Colin not being the intermediary of CM business.

* **How could we solve this issue? (Not knowing is okay!)**

* Add `destroy` route for patients
* Make it usable by admin-only, and only if the patient in question does not have a `pledge_sent`
* Add a `Delete this patient from DARIA` button _that shows up for admins only and if the patient does not have a `pledge_sent`_ in the top patient dashboard - button should have the confirm popup text of 'Only do this if this patient is a duplicate of another patient. This is not reversible and this information is gone forever. Are you absolutely sure this patient is a duplicate and that you want to do this?'
* Add tests for this behavior to controller and integration

* **Anything else?**
 nope!

**Comment by rudietuesdays** [comment]
i'm on this!

**Comment by alisonnjones** [comment]
Hi @rudietuesdays! Very motivated to resolve this issue before we finalize our annual report next month. We really need to make sure we're publishing the most accurate/clean numbers, and that means we need to figure out a system for deleting the corrupt pt files. Let me know what I can do to help or if you have any questions.

**Comment by colinxfleming** [comment]
Popping back open until we have the PR merged
