### ISSUE TITLE
Write frontend for reporting system

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1280]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Cleanly report on what's going on with our case managers and patient load. Or, in this case, implement the lovely designs @SerenaYudon built around this.

* **What feature or behavior is this required for?**

A blind spot we're working on solving is how busy the caller load is over a given period -- a major value this system can provide is some information about what's going on over time periods.

* **How could we solve this issue? (Not knowing is okay!)**

Please implement @SerenaYudon 's designs as follows:

![image](https://user-images.githubusercontent.com/3866868/31925227-525410d4-b855-11e7-8bfb-8bc5f4888ef7.png)

Don't worry about functionality, just make static stuff and get the layouts in place and we'll pop in the backend code piece by piece for now.

This should live in `app/views/reports/index.html.erb` for now. Please use partials where you think it's appropriate -- the more we can break this into components the better.

* **Anything else?**

nope!

**Comment by mdworken** [comment]
Is anyone currently working on this? If not I'd love to take a crack at it.

**Comment by colinxfleming** [comment]
@mdworken all you, go for it!

**Comment by colinxfleming** [comment]
This is repped in the other ticket, so closing in favor of that and marking it futuretech
