### ISSUE TITLE
If pledge sent, pledge_sent_at updates every time a field changes

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1286]
Not sure why, but if a patient is marked `pledge_sent`, then `pledge_sent_at` and `pledge_sent_by` refreshes every single time there's an update. This is a bug in the `PatientsController#update` behavior -- see L63. Task here is to resolve that. Gold medal version is to move this to an activerecord callback (probably an `after_save` or whatever the 'while you're in this transaction, also' callback is?) if we can set the current user as part of it.

The ideal behavior is that information this is set when `pledge_sent` is, and nulled out when pledge sent is false or nil.

**Comment by mdworken** [comment]
Did some digging, I think L61 is the problem. It looks like calling update_attributes is performing an update and therefore returning true, so the code runs each time. Is there any reason it can't just be written as

if :pledgesent

instead?

**Comment by colinxfleming** [comment]
The `update_attributes` there is proper-ish behavior -- we can read that as 'if the update from the web form succeeds, execute L62-L67, otherwise flash an error via L69-L70'.

Stylistically, I think it's a problem that we're overloading the method by stamping on L62-L65 to it -- that should probs be its own method with its own logic somewhere, rather than baked into the controller. But yeah, I think the nut of the problem here is that L62-65 is executing because `params[:pledge_sent]` is part of the update payload more than we thought it was.

Let me know if that makes sense! Commenting on issues at 1am is never a good look, haha.

**Comment by mdworken** [comment]
Changing L61 to

if @patient.update_attributes params[:pledge_sent] and !pledge_sent

seems to resolve the issue.  Lmk your thoughts and I'll Pull Request it as appropriate.

**Comment by mdworken** [comment]
#1298
