### ISSUE TITLE
Can't create new vol roles for data team

### ISSUE THREAD

**Issue by alisonnjones** [DCAFEngineering/dcaf_case_management#1289]
I need to be able to create new volunteer users under User Management for data team vols. 

I clicked Admin Tools, User Management, Add New User, and entered their info. It saved, and they show up in the search when I search their name. But, they cannot see the admin toolbar (or CSV download) when they login. 

Is this because data vols do not have access to the download? Do they have to be CM or a different permission level?

**Comment by colinxfleming** [comment]
I think this is fixed by #1272 but I'll to make sure it's fixed after we merge it.

**Comment by colinxfleming** [comment]
@alisonnjones #1272 is merged so I think this might be fixed for both creating new users AND updating existing users, can you take a look on your end and close this if it looks good?

**Comment by alisonnjones** [comment]
Sure @colinxfleming let me test it tonight after work

**Comment by colinxfleming** [comment]
@alisonnjones nudging on this!

**Comment by alisonnjones** [comment]
so far so good! I've changed several current cm vols to data and it worked and i tested with a fake user for creating a whole new profile. thank you!

**Comment by colinxfleming** [comment]
thanks for checking!
