### ISSUE TITLE
Change Name of Fax Service

### ISSUE THREAD

**Issue by NerdyGirl537** [DCAFEngineering/dcaf_case_management#1295]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
onlinefaxes.com is now www.efax.com. We should change all the references in DARIA to reflect this.

* **What feature or behavior is this required for?**
Direct access for the fax service.
* **How could we solve this issue? (Not knowing is okay!)**
Change the labels and links.
* **Anything else?**
DARIA is awesome!

**Comment by mdworken** [comment]
#1297
