### ISSUE TITLE
Change log does not list updated by properly

### ISSUE THREAD

**Issue by mdworken** [DCAFEngineering/dcaf_case_management#1330]
Hi all! I'll fix it myself, but the change log is not listing the name properly. Probably needs a .name at the end to make it the user's name instead of the user's user object.

![wrong user](https://user-images.githubusercontent.com/31595784/34048502-f4976a62-e181-11e7-8e70-a2042948cbb8.png)

**Comment by colinxfleming** [comment]
@mdworken I think your inclination here is exactly right -- I'd consider throwing a function in a helper that properly parses the data depending on the object class (e.g. `if thing.is_a? User`...) Great catch!

**Comment by mdworken** [comment]
Will do, may be a bit depending on what work is like.

**Comment by mdworken** [comment]
Did some digging, it looks like the methods in audit_trail.rb were written specifically to create  this behavior. 

@colinxfleming any historical perspectives I'm missing?

**Comment by colinxfleming** [comment]
@mdworken in `audit_trail.rb`, the `changed_by` method is what spits out the column on the right side. I would slap something additional in `changed_from` and `changed_to` that transforms `value` (on L57 and L63). Something like `if value.is_a? User then value.name else value`.

**Comment by mdworken** [comment]
Will do! Still somewhat confused by the fact that users, etc were called "IRRELEVANT FIELDS".
