### ISSUE TITLE
Change Log entries do not line up properly when changed to/from nil

### ISSUE THREAD

**Issue by mdworken** [DCAFEngineering/dcaf_case_management#1338]
See screenshot in #1330 . Although this is not a severe issue (one can easily tell what was supposed to go where), it would be nice to make these line up properly.

I'll fix this myself, just wanted to put the issue out here.

**Comment by mdworken** [comment]
Upon further research, it turns out that the rows are instantiated at the change level, and multiple changes are being entered in as separated by breaks. This means that if a previous entry was nil the other entries get "bumped up".

I believe this can be fixed by still entering a break for nil elements, but will see if there's a "nicer" way that won't add to technical debt.

**Comment by colinxfleming** [comment]
After a brief exploratory PR I think this is going to entail a refactor of how we're displaying audit trails. I don't feel super scared of it though!
