### ISSUE TITLE
Viewing clinic details is slow

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1353]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
If you go to the clinic management page and click the expand chevron, it has a clunky feel. We should speed that up and put in a jquery `slideDown('fast')`.

* **What feature or behavior is this required for?**
Being able to easily see clinic details in the management list.

* **How could we solve this issue? (Not knowing is okay!)**
a) prerender, hide the dom element, and change it to a jquery slidedown or something
b) fix the test in `test/system/clinic_management_test.rb`

* **Anything else?**
nope!

**Comment by geoffreyyip** [comment]
Main issue is HTML tables. bootstrap's toggle functionality doesn't play nicely with HTML tables. Some workarounds are described in this link. Posting it here so I can refer back to it later:

https://damienfremont.com/2014/12/19/how-to-expandcollapse-table-rows-with-bootstrap/

**Comment by geoffreyyip** [comment]
Proposal: What if we got rid of the dropdown rows entirely? 

Right now, we have this:
<img width="1177" alt="screen shot 2018-01-27 at 4 55 15 pm" src="https://user-images.githubusercontent.com/15312106/35476771-a84a91c4-0383-11e8-91fb-adbc966e7efd.png">

This is bad UI. Users have to click on the dropdown to learn about whether a clinic **Accepts Medicaid?**, **Accepts NAF?** or has a **Gestational Limit**.  Users don't know that's in the dropdown until they click on it. And if they want to compare all clinics at a glance, they need to click on all row dropdowns first.

Instead, we could do this:

[
<img width="1177" alt="screen shot 2018-01-27 at 4 55 15 pm" src="https://user-images.githubusercontent.com/15312106/35476743-0af124ec-0383-11e8-8173-858dad3243da.png">
](url)

What do you think?

**Comment by colinxfleming** [comment]
I don't think it's bad UI, given how this endpoint is used. IIRC the thinking was that there were some things you needed, some things you were PROBABLY interested in that didn't necessarily warrant clicking into the form, and some stuff that was pretty much set-and-forget that CMs will never really have to worry about. I don't know that it'll ever really be necessary to compare clinics, since they're isolated institutions and this is primarily an admin view, and we have different ways of using the NAF/Medicaid lists that don't involve this index.

That said, we have an implementation challenge here that makes our old solution a tough fit, and I think we get the same amount of functionality out of your solution, so let's roll with it. Let's make those headers just `NAF`, `Medicaid`, and `Gestational limit (days)`.
