### ISSUE TITLE
BRAF Website Link is for DCAF

### ISSUE THREAD

**Issue by NerdyGirl537** [DCAFEngineering/dcaf_case_management#1378]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
I was on the BRAF App today and noted that the BRAF Website link at the bottom of the page goes to the DCAF website. I checked heroku and that references BRAF's website so I'm not sure where it needs changed.

* **What feature or behavior is this required for?**
To access BRAF's website from the CM app.

* **How could we solve this issue? (Not knowing is okay!)**
find where the app is referencing the DCAF website

* **Anything else?**
Nope. Thanks for all the great work.

**Comment by lomky** [comment]
Oops - we still have that hardcoded!

**Comment by lomky** [comment]
So we do have a variable available called "FUND_DOMAIN", but it seems to be based on the assumption that the domain is the same as the full name. I.E. FUND_FULL = `DC Abortion Fund`, FUND_DOMAIN = `dcabortionfund`. Is this true for BRAF, @NerdyGirl537?

**Comment by NerdyGirl537** [comment]
I know the fund website is a config variable in Heroku
(FUND_MAILER_DOMAIN). Would it be easier to just pull from there?

I'm not sure we can use the assumption. BRAF's website is blueridgeaaf.org
and they just changed their name.

2018-02-03 14:43 GMT-06:00 Kathryn Tipton <notifications@github.com>:

**Comment by lomky** [comment]
@NerdyGirl537 I think I found the disconnect. Despite having the Heroku variable `FUND_MAILER_DOMAIN` we weren't using that. I think I've got the fix in, but it will involve review for each running instance to make sure `FUND_MAILER_DOMAIN` is set properly. I.e. for BRAF we would want it set to `blueridgeaaf`, for DCAF `dcabortionfund`, etc.

**Comment by lomky** [comment]
PR in!
