### ISSUE TITLE
Upgrade CircleCI to 2.0 (or swap out for Travis)

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1388]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
We currently use CircleCI format 1.0 for our builds and deploys to sandbox. They're sunsetting version 1.0 on August 31.

* **What feature or behavior is this required for?**
Being able to do CI builds and deploy the app.

* **How could we solve this issue? (Not knowing is okay!)**
Two ways:
* upgrade circle.yml to use the version 2.0 format
* switch to TravisCI

I'm not sure I have a preference. Circle lets us take advantage of four build containers which is nice, and we do have some circle specific stuff in our build generally (see test_helper, and maybe our knapsack gem config). Travis seems nicer and has the cool miner logo though.

* **Anything else?**
@DarthHater make my problems go awayyyyyyyyyyyy

**Comment by colinxfleming** [comment]
Here's the email from circle: https://circleci.com/blog/sunsetting-1-0

**Comment by DarthHater** [comment]
I'll play with both on some branches.

**Comment by colinxfleming** [comment]
Def do whatever's easiest! Keeping tests split across nodes would be nice
but isnt necessary

**Comment by colinxfleming** [comment]
We're on circle via #1394 , closing
