### ISSUE TITLE
CSV export failing to export all pledges fulfilled

### ISSUE THREAD

**Issue by alisonnjones** [DCAFEngineering/dcaf_case_management#1393]
Hi all,

The CSV export tool is not exporting pledge fulfilled data correctly. We cross checked our Quickbooks for a time period (July-December 2017) with what is exported in DARIA, and there's more than 200 pledge counts and $73k missing from the data. Need help assessing if this is a flaw in the export code or mislabeling or something. @colinxfleming @NerdyGirl537 @lwaldsc 

I have no idea how to test if the export is working, so any help/insight would be appreciated. We need to figure out what our Quickbooks are not lining up with our DARIA exports.

**Comment by alisonnjones** [comment]
Is the field "DCAF pledge" in the CSV export correctly exporting the amount listed as "DCAF pledge" in DARIA? Could there be a break in the naming convention/what's exported? How can we test this?

**Comment by colinxfleming** [comment]
thanks for reporting this @alisonnjones . I'll follow up with you to identify a sample case and then we can figure out a fix from there.

**Comment by colinxfleming** [comment]
Since this involves some sensitive production data we're going to figure out the exact issue on background, and then we'll bring a fix back here for resolution.

**Comment by colinxfleming** [comment]
Update on this: Sent some possible sample cases to @alisonnjones for review and spotchecking. Will move forward when we hear back from DCAF brass, in this case probably @alisonnjones or DCAF's accountant.

**Comment by mdworken** [comment]
I think I've found the problem: the Bootstrap form for fulfillment isn't actually updating any of the patient attributes. Digging in to why now.

**Comment by colinxfleming** [comment]
@mdworken can you post steps to recreate the bootstrap form problem in this ticket when you get a chance so that we can verify and figure out a test to write against it?

**Comment by mdworken** [comment]
@colinxfleming I'll do step-by-step and a test once I get off work, but you can look at the following in the sandbox. Notice the variables are being saved but the export is not working. Can you check what's being saved in the DB?

https://sandbox.dcabortionfund.org/patients/5acab4a320e5ff000af51ada/edit

**Comment by colinxfleming** [comment]
Here's a snippet from the rails console looking at the fulfillment for this patient:

```rb
irb(main):007:0> Patient.find('5acab4a320e5ff000af51ada').fulfillment
=> #<Fulfillment _id: 5acab4a320e5ff000af51adc, created_at: 2018-04-09 00:32:35 UTC, updated_at: 2018-04-09 00:32:35 UTC, fulfilled: true, procedure_date: nil, gestation_at_procedure: "", procedure_cost: 333, check_number: "", date_of_check: nil, version: 1, modifier_id: nil, created_by_id: BSON::ObjectId('5abfbe7f0a5dee000445379b'), updated_by_id: BSON::ObjectId('5abfbe7f0a5dee000445379b')>
```

I updated it in the form to 335 and that was reflected in db:

```
irb(main):008:0> Patient.find('5acab4a320e5ff000af51ada').fulfillment
=> #<Fulfillment _id: 5acab4a320e5ff000af51adc, created_at: 2018-04-09 00:32:35 UTC, updated_at: 2018-04-09 00:32:35 UTC, fulfilled: true, procedure_date: nil, gestation_at_procedure: "", procedure_cost: 335, check_number: "", date_of_check: nil, version: 1, modifier_id: nil, created_by_id: BSON::ObjectId('5abfbe7f0a5dee000445379b'), updated_by_id: BSON::ObjectId('5abfbe7f0a5dee000445379b')>

```

@mdworken are you sure this is a technical problem separate from #1401 , which is putting the wrong column in the export (the `fund_pledge` field instead of whatever the fulfillment field is currently called), and which I believe will be fixed by #1408 ?

**Comment by colinxfleming** [comment]
(a note for ref: sandbox was on 59b9fb84 when I pulled that)

**Comment by mdworken** [comment]
Update: there must've been a problem with my local branch when I thought values weren't updating. 

At first pass comparing data this looks fixed by #1409 , but I'll work with @alisonnjones this weekend to confirm before closing this out.

**Comment by alisonnjones** [comment]
It looks like we're still off by $1k when comparing the cvs export procedure costs to the quickbooks finances. any idea what could be causing this discrepancy?

**Comment by colinxfleming** [comment]
That's within the range of what I would expect from data entry issues, honestly. I'd recommend doing an audit of what you have on file vs what CMs have entered to see if you can hone in on individual cases we can look at. I'm not sure there's an engineering reason it'd be off by that little. What number of pledges is it off by?

**Comment by alisonnjones** [comment]
It looks like I'm off by 10 pledges (csv = 126, quickbooks = 136). Let me go line by line to see if it's bc of individual files. So excited this is a much more accurate reflection, though!

**Comment by colinxfleming** [comment]
I would have guessed that regenerating a pledge thru the UI would bump the pledge generated timestamp, per https://github.com/DCAFEngineering/dcaf_case_management/blob/master/app/controllers/patients_controller.rb#L50 . Do we think they're just updating the pledge amount and communicating with the clinics verbally, or do we think that they're re-generating pledge forms thru the UI and it's just not taking because of a bug? (Or am I misunderstanding and Quickbooks only tracks the first pledge?)

**Comment by alisonnjones** [comment]
Quickbooks is what our accountant enters, and they entered the pledge sent date. 

But, you're right that regenerating the "pledge generated" isn't affected, it's the "pledge sent" field. Sorry for the confusion. I double checked this with the test case I mentioned above, and even tho the data vol resent the pledge to update the total pledge sum ("abortion care $" in DARIA), the pledge generated field stayed the same. Let me look at this again based on pledge generated and contrast with quickbooks.

**Comment by colinxfleming** [comment]
hey @alisonnjones or @mdworken  are there further DARIA fixes to make here?

**Comment by colinxfleming** [comment]
I'm going to close this since I don't think there's a rails fix to make here. @alisonnjones please reopen if there is a software change we need to make.
