### ISSUE TITLE
Activity log design going ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#1395]
The activity log is acting wonky. Don't think this how Mollie designed it.
![screen shot 2018-03-19 at 8 10 56 pm](https://user-images.githubusercontent.com/10578608/37628886-fcd3f98c-2bb1-11e8-9270-333a50228245.png)

**Comment by colinxfleming** [comment]
uhhhh pretty sure it is?

Just kidding, I can't write CSS worth anything so I bet I jacked this up at some point. Probably this ticket is removing the oval taking up the row body, which may or may not be as simple as swapping out a class somewhere. I'd look in the events helper in particular, which I think does a lot of lifting to render this.

**Comment by colinxfleming** [comment]
@tingaloo after reviewing some of the designs it kinda looks like there was never a gray box around it, so idk what I was thinking. Maybe let's just ditch it? Not sure it really serves our needs here, and we're short on designers to whip us into shape.
