### ISSUE TITLE
CSV export is using procedure cost value for abortion care column

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1401]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Team BRAF alerted us to a bug in the export: abortion cost is getting repeated twice, and it's showing up where `procedure_cost` should be.

Steps to recreate:
* create a new patient
* fill out appointment date, clinic, `Abortion Cost` as 1234, `DCAF Pledge` as 500, submit the pledge
* change `Abortion Care $` to 9999
* run the patient export. You will see that there is a row that has the 1234 repeat both in abortion cost (the full cost of the abortion, stored on the patient object) but also procedure cost (Abortion Care $ to DCAF, a representation of what DCAF actually pays out, store on the fulfillment object).

* **What feature or behavior is this required for?**
Accurate and useful exports!

* **How could we solve this issue? (Not knowing is okay!)**
Pop into `exportable.rb` and change it so the `procedure_cost` field is pointing at the correct database field. 

* **Anything else?**
nah!

**Comment by mdworken** [comment]
Self assigning to clarify that I'm fixing this with #1402
