### ISSUE TITLE
Rename fulfillment.procedure_cost to something more reflective of what it is

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1402]
What's the difference between abortion cost and procedure cost? No idea, but one of them is the quoted pricetag by the clinic and the other is what a fund paid out. (Procedure cost is the latter.) We should rename this so it doesn't drive me, personally, up the wall.

Steps are:

* write a ruby one liner that renames the field to something
* change it in the model
* update exportable
* update our docs
* flag for analytics team

cc @alisonnjones

**Comment by mdworken** [comment]
@colinxfleming I can knock this out for you if you'd like :)

**Comment by colinxfleming** [comment]
@mdworken sounds good. Please confirm with @alisonnjones / DCAF's accountant that my understanding of these fields is right, and that the number they're entering from the fulfillments is in fact what DCAF paid and not smoething else!

**Comment by mdworken** [comment]
Will do!

**Comment by alisonnjones** [comment]
Hi team! The data vols enter the fulfillment amount in the "Abortion care $" field in DARIA, and this is indeed the amount DCAF has paid. I think it exports as "Procedure cost" in the CSV, but I don't know if these different naming conventions has caused from fracturing in the export... The DARIA field "Abortion cost" is the total cost for the abortion, and is exported as "Abortion cost". The "DCAF pledge" field in DARIA is exported as "Fund pledge".

**Comment by mdworken** [comment]
Removed myself as assignee as I don't want to accidentally mess up the command for the rails console.
