### ISSUE TITLE
Delete Patient Record button is being triggered when setting Appointment Date

### ISSUE THREAD

**Issue by mdworken** [DCAFEngineering/dcaf_case_management#1407]
As an admin using Chrome, the date-picker for Appointment Date is triggering the delete patient record. This occurs both from clicking the date and entering a date and pressing enter. 

 My branch was 40519bd8 Merge pull request #1404 from DCAFEngineering/destroy-route.

Update: I had this occur in edge too now.

**Comment by colinxfleming** [comment]
Can verify this is happening on sandbox currently, so we should hold on shipping to production until we get this sorted out. 

@tingaloo any chance you've seen this problem before with in-browser datepickers?

**Comment by colinxfleming** [comment]
Steps to recreate:

* log in as an admin and go to a patient page
* click on the appointment date field and set it to something

Expected outcome: Field updates as normal
Actual outcome: Patient gets destroyed (woof)

**Comment by colinxfleming** [comment]
There are a few ways around this; we might try moving the button away from the dropdown and onto the sidebar below 'send pledge'; we might disable the button while the input is focused; we might implement a proper jquery deal instead if it goes well with bootstrap forms. Will confer with frontenders about how to handle this.

**Comment by colinxfleming** [comment]
Temporarily just shut this off for safety's sake so we can run a deploy. Shutoff commit is fd49d030

**Comment by tingaloo** [comment]
Taking a look at this, any change in the upper patient dashboard triggers the deletion.

**Comment by colinxfleming** [comment]
oh, durf! It's probably because it's a button within the form?
