### ISSUE TITLE
eIntake Form Interface

### ISSUE THREAD

**Issue by NerdyGirl537** [DCAFEngineering/dcaf_case_management#1417]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Create an interface for DCAF's eIntake form that will allow the information to be directly ported into DARIA. We will be working with Kate Bertash <kate@securityfund.io> of the Cyber Security Fund to select the form and integrate it into DARIA.

* **What feature or behavior is this required for?**
Not sure?

* **How could we solve this issue? (Not knowing is okay!)**
Not sure

* **Anything else?**
You guys rock!

**Comment by NerdyGirl537** [comment]
We've been doing eIntake planning calls with Kate and have a form that's
been thoroughly vetted. This is the current version:
https://docs.google.com/document/d/1iNZvP5RIft07veH4sZ6FBK_pPZC08fA-7ZESmQhIhlc/edit.
Kate is looking for what is needed to bring the information directly from
the form to DARIA. We did talk about the manual entry process as an
alternative. Kate needs to talk to the technical team about the more
involved version. Does this help?

2018-05-01 19:21 GMT-04:00 Colin <notifications@github.com>:

**Comment by colinxfleming** [comment]
Got it. I'd favor a manual entry for now, I don't want the engineering team to be a holdup for rolling this out if it's a priority for DCAF!

If we do want to pursue an automatic deal now or in the future, here's what it would PROBABLY involve DARIA side:
* set up a custom endpoint that takes a payload and maps it to a DARIA patient (OR something that knows to monitor a URL on its own, which might be more secure DARIA side but would probably be more of a pain)
* Probably creates a note with the data that doesn't cleanly map, like 'best time to call'
* Sets a new flag on Patient object, something like 'autocreated via web form' or something

Here's what it would involve Kate-side:
* Set up form so it outputs in a consistent agreed upon shape
* Either be ready to post to endpoint or set up their own secure endpoint

if Kate has a github acct, feel free to tag her into this thread if it's helpful!

**Comment by mdworken** [comment]
@NerdyGirl537 not sure if this is the right place, but I have slight concerns regarding the phrasing for the checkbox "☐ I have called the NAF hotline......" as to me it reads as too heavy of a directive. Has this been discussed much at all? I wonder if phrasing like 'I have _already_ called the NAF hotline...." should be considered.

**Comment by colinxfleming** [comment]
@alisonnjones @NerdyGirl537 I'm going to close this since it's not really a DARIA issue and if we have to do it, it'll come up on its own. Please reopen or let me know if you object.

**Comment by alisonnjones** [comment]
No this makes sense to me. We're planning to use an external service for
the eform and have CMs copy and paste the info in DARIA, so no DARIA
engineering necessary here. Thanks.
