### ISSUE TITLE
Add Audited Field to Patient

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1420]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Adding a boolean field to Patients that denotes whether the patient fulfillment has been audited.

* **What feature or behavior is this required for?**

Avoiding archiving fulfilled patients until they have been audited, up until a certain point.

* **How could we solve this issue? (Not knowing is okay!)**

Add the field and tie archiving into it. Add a failsafe to archive regardless after X days.

* **Anything else?**

We need to hash out what the timeline looks like for archiving fulfilled patients with audit and without. 
We strongly want to err towards code that supports best practices.

Tagging in @alisonnjones and @colinxfleming

**Comment by rudietuesdays** [comment]
I'm on it!

**Comment by colinxfleming** [comment]
resolved via #1524
