### ISSUE TITLE
Add tests for display of disabled user statuses 

### ISSUE THREAD

**Issue by mdworken** [DCAFEngineering/dcaf_case_management#1438]
According to our code coverage report, we aren't testing the display of disabled user statuses. Self assigning an issue to add tests for this.
![image](https://user-images.githubusercontent.com/31595784/41731141-9de4e236-754b-11e8-8aa6-79dc0137d397.png)

**Comment by Kevin-Wei** [comment]
https://github.com/DCAFEngineering/dcaf_case_management/pull/1514
