### ISSUE TITLE
High response time for Events endpoint

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1447]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

We're regularly getting logentries alerts like:

```
 306 <158>1 2018-07-08T16:08:00.368239+00:00 heroku router - - at=info method=GET path="/events" host=XXXX request_id=bf56698d-b23c-4608-bbe1-ba6f44948b60 fwd="xxxx" dyno=web.1 connect=0ms service=7080ms status=200 bytes=180789 protocol=https
```

We should do something about this to reduce the response time, or start loading events lazier (pagination, semi-infinite scroll, etc).

* **What feature or behavior is this required for?**

Not getting alert spam

* **How could we solve this issue? (Not knowing is okay!)**

not sure

* **Anything else?**

**Comment by mdworken** [comment]
Have we added indexing along `created_at:` in mongoid? It looks like it's not done automatically according to this ticket:  https://stackoverflow.com/questions/22797773/mongoid-timestamp-indexing

Not sure how much this will help, but it seems like something easy we can try!
