### ISSUE TITLE
Create system test for exportable

### ISSUE THREAD

**Issue by mdworken** [DCAFEngineering/dcaf_case_management#1469]
Since we've had data-integrity problems in the past (including but not limited to #1286) I and the rest of the data team would feel a lot more comfortable if we included an end-to-end test of data and exportable in the test suite.

Self-assigning this issue before I knock it out over the coming week.

**Comment by colinxfleming** [comment]
Can you do me a solid and spec out what exact behavior we need to test and lock in @mdworken ?

**Comment by mdworken** [comment]
Yes, will do!

I'm super swamped with data team stuff, but I should be able to flesh this out a little more within the next week or two.

**Comment by colinxfleming** [comment]
@mdworken is this still a pressing concern? Can we either close or spec this out? I'm not familiar with the particular pain point you all have been experiencing, and there's not a next step here currently.

**Comment by colinxfleming** [comment]
I think we're likely to broadcast any particular major breaking changes to this, and core functionality is covered by the controller tests, so I'm going to close this out as a wontfix for now. If we have specific concerns around locking in behavior we can revisit, but this hanging out in the backlog for a full year is I think a signal that it's not particularly scary; also as we've seen the exportable code doesn't move that much.
