### ISSUE TITLE
Surface Archive Date on Patients

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1478]
* **What are we trying to do?**  
Share the information about when a patient will archive with the data and admin folks.

* **What feature or behavior is this required for?**
Better information sharing & feeling secure in our data. Catching bugs like #1475 before they affect our data.

* **How could we solve this issue? (Not knowing is okay!)**

 - Option A: Show the info on the patient page
 - Option B: Add as a column on the accountant page
 - Option C: Both

* **Anything else?**
I don't object to having anyone be able to see this - but I don't see any use case for the CMs to need this info and don't want to clutter their panel.

Tagging in @colinxfleming and @verbingthenoun for thoughts!

**Comment by verbingthenoun** [comment]
Thanks for tagging me in. Hmm, I think most of the data team doesn't need this - just me and @alisonnjones. I can't see the accountant page so I won't weigh in there, but having it show on the patient page would be very useful.

**Comment by colinxfleming** [comment]
hm! Let's surface this on the patient page for now under the fulfillment partial. So I think steps to complete here are:

* writing a method that returns the archive date, with a test
* dropping that in on `views/patients/_fulfillment` in its own `p` tag with text like 'This patient will be archived on YYYY-MM-DD`.

Tagging it in

**Comment by colinxfleming** [comment]
@Kevin-Wei

**Comment by Kevin-Wei** [comment]
https://github.com/DCAFEngineering/dcaf_case_management/pull/1518 
Not 100% about the logic here

**Comment by colinxfleming** [comment]
resolved via #1524 I do believe

**Comment by Kevin-Wei** [comment]
👍
