### ISSUE TITLE
Set fax link in footer to an app config instead of an env var

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1495]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Our footer: 

![image](https://user-images.githubusercontent.com/3866868/47257375-c9a55180-d45a-11e8-924a-d9cf87bd4cb1.png)

It's nice, right? But sometimes people switch fax services, and we don't want to be on the hook for making a code change.

* **What feature or behavior is this required for?**

Getting engineers out of processes that should live with the funds themselves.

* **How could we solve this issue? (Not knowing is okay!)**

We have a working model for how to add this kind of app config in `app/models/config.rb`. We should:

* add fax service as an admin config option
* replace that footer link to either be nothing if the config isn't set or the config if so
* Figure out a way to accommodate both the name and the URL in one config

* **Anything else?**

stems from #1465

**Comment by vraravam** [comment]
I'll sign up for this

**Comment by colinxfleming** [comment]
hey @vraravam , I think @tingaloo  beat you to it, but could I point you toward #1499 instead?

**Comment by vraravam** [comment]
@colinxfleming : @tingaloo had asked me to take over the PR, but as I had mentioned, I would much rather start afresh (attributing to him as well). Hope that is ok with you. Please ack before I can start the work.

**Comment by colinxfleming** [comment]
resolved
