### ISSUE TITLE
Add indicator to tell if someone has had an ultrasound

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1497]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

DCAF and BRAF both work in VA, which since 2012 has required people seeking abortions to complete ultrasounds for `$BAD_REASON`. This has an effect of adding an additional fee and hurdle on top of abortion costs, but clinics generally make you do it once, so if someone has had one done already, that's nbd. Because abortion funds are super good at this kind of thing, whether or not a patient has had an ultrasound already influences the logistical advice CMs might give.

* **What feature or behavior is this required for?**

Saving patients dollars; providing effective service in states with mandatory ultrasounds.

* **How could we solve this issue? (Not knowing is okay!)**

* Add a boolean field on Patient: `completed_ultrasound`
* Add it to the patient edit form, under abortion information
* Add some helper text to spell out what the field is for and when you would use it (in a nutshell, if you're in a mandatory ultrasound state, why you would check this box)
* Adjust the patient info update systemtest to account for this new field

EXTREME GOLD MEDAL VERSION: Since not every state requires this, it's not relevant for much of the country; it would be nice to be able to set this on a line by line basis in the admin configs (in `app/models/config.rb`). This adds to the complexity a bit though so we can 100% kick it to a diff ticket.

* **Anything else?**

Please follow up with @lwaldsc / @NerdyGirl537 in slack to confirm that this will work appropriately for the VA use case in slack

**Comment by nikobozi** [comment]
hi, i would like to work on this one! :)
