### ISSUE TITLE
A few unit and systemtests to add

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1515]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

In the sprint of hacktoberfest, we left a few things uncovered. So let's cover them per comments below.

* **What feature or behavior is this required for?**

Safety first!

* **How could we solve this issue? (Not knowing is okay!)**

Adding tests per comments below.

* **Anything else?**

**Comment by colinxfleming** [comment]
Confirm `:textable` checkbox persists in `system/update_patient_info`

**Comment by Kevin-Wei** [comment]
https://github.com/DCAFEngineering/dcaf_case_management/pull/1519 system test here

**Comment by colinxfleming** [comment]
Controller tests for NAF and Medicaid clinics in clinicfinders per #1531
