### ISSUE TITLE
Unable to join the Slack channel

### ISSUE THREAD

**Issue by vraravam** [DCAFEngineering/dcaf_case_management#1520]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Join the Slack channel

* **What feature or behavior is this required for?**
Contribution and discussions with the leads.

* **How could we solve this issue? (Not knowing is okay!)**
Either allow self-signups for that slack group or don't advertise that this is open for joining in your README.md

* **Anything else?**
On the slack signup page, this is the message that I see: `Contact the workspace administrator for an invitation`

@colinxfleming @alisonnjones

**Comment by mdworken** [comment]
It appears the link is currently down, but one will normally use https://codefordc.org/joinslack.html as a method of joining the slack. I will see to it that the readme is updated appropriately.

**Comment by mdworken** [comment]
Update: it appears the link is included on the readme. The people responsible for the invite link are an external org so we don't have direct control over downtime, but I will ping them to ask on the status

**Comment by Kevin-Wei** [comment]
Yeah I don't remember having to be approved to join slack but this was years ago

**Comment by colinxfleming** [comment]
yeah, I think code for dc has had some website issues recently, but I believe they're out of the woods now? I think they have an autobot that grants slack accounts, so no org-side approval necessary that I remember.

hey @vraravam I'm gonna close this, but please flag in here if you need an assist or if this is still an issue when you try again!
