### ISSUE TITLE
Revamp Archive to give logic to Patient object

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1523]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Surface archive issues earlier by giving over archive calculations to hte patient object.

* **What feature or behavior is this required for?**
Debugging issues with archive.

* **How could we solve this issue? (Not knowing is okay!)**
Move logic to patient creation, remove fulfillment-based early archiving.

* **Anything else?**

**Comment by colinxfleming** [comment]
resolved via #1524
