### ISSUE TITLE
Figure out how to best Integration Test the locale changes

### ISSUE THREAD

**Issue by DarthHater** [DCAFEngineering/dcaf_case_management#1537]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Now that we are introducing another locale (Spanish) in #1526 and follow on work, figure out the best way to test this.

* **What feature or behavior is this required for?**
Essentially just figuring out that all the Spanish translation work, stays good!

* **How could we solve this issue? (Not knowing is okay!)**
In theory you could rerun all tests with the locale changed, but I'm not sure if that's correct.

* **Anything else?**
Fuerza!

**Comment by Kevin-Wei** [comment]
One option is relying on i18n keys.

I18n.t('key.for.something') can be used by both capybara helpers and matchers

For example 
`click_link 'Lock account' ` -> `click_link 'I18n.t("lock_account")' `
`assert_text 'Build your call list'` -> `assert_text 'I18n.t("build_call_list")' `

of course the downside now is you have to change your tests whenever you I18n keys change.

**Comment by colinxfleming** [comment]
I think I'd be good with the 'prove the locale switch works' method -- something like:

```
visit authenticated_root_path, params: { locale: 'es' }
assert has_content? 'Welcome to DARIA'
click_link 'Spanish mode'
refute has_content? 'Welcome to DARIA'
assert has_content? 'Bienvenidos a DARIA'
```

I don't think we need to exhaustively test every key, or key values. I'm mostly interested in 'when we smash the button the language switches'. But I am def open to hearing otherwise. @Kevin-Wei @DarthHater yr thoughts?

**Comment by DarthHater** [comment]
@colinxfleming I am 100% on board with that, not because it reduces work load, just because I think it is about as much as I think you SHOULD test. Keys can change quickly, it's really only important to test them if it's like mission critical that something says an exact thing.

**Comment by Kevin-Wei** [comment]
I didn't mean that it is critical that _every_ key is tested. What I'm recommending is a path forward for areas that have existing view tests that rely directly on text in the test that will be translated. 

I also agree that keys should rarely change and its not necessarily a bad thing to add that kind of overhead. It could reveal to us where we are over-testing text on the view. Therefore we can remove those kinds of text validations. Only leaving the ones that @DarthHater said are "mission critical"

**Comment by colinxfleming** [comment]
I'm not super concerned about this - i18n tools that @lomky adopted into our test suite make it so we don't have to be too scared of this, in my opinion. I'm closing unless @DarthHater or @Kevin-Wei have a strong opinion and/or a path to doing this.
