### ISSUE TITLE
mLabs sunsetting products -- what does this mean for the heroku add-on

### ISSUE THREAD

**Issue by BintLopez** [DCAFEngineering/dcaf_case_management#1539]
**What are we trying to do?**
MLab is becoming part of MongoDB and as such its products will eventually need to be migrated to MongoDB Atlas.

MLabs announcement blog post here:  https://blog.mlab.com/2018/10/mlab-is-becoming-a-part-of-mongodb-inc/, relevant excerpt below:

> What This Means For You, Our Customer
>
> * You will be given plenty of time to migrate, and nothing will be required of you for at least 4 months. We expect to have all customers migrated to Atlas within the next 12 months.
> * Once migrated, your Atlas database will be hosted on similar hardware and cost the same or less than your original plan on mLab.
> * We will provide tools that allow you to migrate with either minimal downtime or no downtime to your application.
> * All of this applies to users with mLab Heroku add-ons as well.

**What feature or behavior is this required for?**
required for database and basic app functionality

**How could we solve this issue? (Not knowing is okay!)**
Will eventually need to use a different add-on for the database. For now, can monitor the 
situation and await guidance from Mongo/Atlas -- perhaps they'll provide an alternative add-on? Otherwise, would need to use a different add-on.

**Comment by colinxfleming** [comment]
looked at this to see what was going on and here's what this came back with: https://docs.mlab.com/mlab-to-atlas/ probably nothing to do here yet.

**Comment by xmunoz** [comment]
I am in the process of actioning this migration. The sandbox instance has already been migrated to atlas, and the other instances will be migrated later this week. I will close this ticket once that happens.

**Comment by xmunoz** [comment]
It is done!
