### ISSUE TITLE
Adopting DARIA 101

### ISSUE THREAD

**Issue by alisonnjones** [DCAFEngineering/dcaf_case_management#1545]
We want to make a one-pager guide with all the top line information another fund would want to know if they are thinking about adopting DARIA. I know this lives in a few peoples’ heads, but will be good to have it all in one place that’s easy to share with folks who are new to DARIA (shoutout to @harumhelmy the idea! 💡). 

Tagging DARIA gurus @NerdyGirl537 @lwaldsc

**Comment by colinxfleming** [comment]
Lets structure as one paragraph summaries about each of the following: case
management flow, admin tools, security, how to migrate, costs.
