### ISSUE TITLE
Investigate what BRAF wants to report on that they can't now because of the archive process

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1561]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

From BRAF: 

> Can we control when data is archived? We want access much longer, at least more than a year. So at the end of the fiscal year when we are trying to get some statistics we can actually look at the person's intake record when needed.

It's not clear from this what they want to do and can't now, and what 'looking at intake record' means, really. but we should talk to them about it and give them a go or no go just so we  don't leave them hanging.

First step is to talk to them and figure out what the deal is.

* **What feature or behavior is this required for?**

reporting, but maybe?

* **How could we solve this issue? (Not knowing is okay!)**

tk

* **Anything else?**

stems from #1465

**Comment by colinxfleming** [comment]
@NerdyGirl537 @alisonnjones has there been any movement on this? Is now a good time to reach out and ask them about this, or should we assume that anything that's really troublesome for them will pop up again organically, or (third option here)?

**Comment by susanjw** [comment]
We reached out to BRAF, and they confirmed this is no longer an active request.
