### ISSUE TITLE
Set up JS build security tools

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1622]
Now that we're on webpack, our builds should reflect that. We should add equivalents of brakeman and ruby-audit for JS to our build process.

**Comment by colinxfleming** [comment]
(We have `yarn audit` but I do not know what else to add. This is a ticket to investigate and implement it.)

**Comment by BintLopez** [comment]
Came across this tool -- https://snyk.io/docs/using-snyk/#wizard

Need to read deeper but at first glance, this might be a good fit.

**Comment by colinxfleming** [comment]
someone exploring that and figuring out if it's a) free and b) better than yarn audit that would rule!

**Comment by colinxfleming** [comment]
I did some wrenching in here not long ago to squelch npm vulns and I think we can safely declare this okay with yarn audit. Also, after taking a look at snyk on an unrelated project it looks very nice but I'm not sure it gives us that much more than yarn audit. #1665 should rep the work here. Let's close.
