### ISSUE TITLE
Final Pass - User Facing Spanish Review

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1633]
This ticket is to capture the last needed Spanish translations _for the Case Manager facing sections_. Admin & Data manager sections _are not required_ for this review.

* **What are we trying to do?**

Browse around on the [Spanish Review](https://github.com/DCAFEngineering/dcaf_case_management/tree/spanish_review) branch and look for English. Look at the regular text, any helper text (the "?"s), error messages, drop down selections. Try clicking and editing things. Sort things. Edit the call list. Try to break things!

Do not worry about the user entered text entered in fields. Values in notes, the patient name itself, other contact relationship, etc are not what we're looking for here. If you're uncertain though, just go ahead and add a comment of it! 

Screen shot, or carefully describe in a comment here, the English.

Also look out for any errors related to translations.

* **What feature or behavior is this required for?**

User facing Spanish release!

* **How could we solve this issue? (Not knowing is okay!)**

Lotsa eyes.

**Comment by lomky** [comment]
"Forgot your password?". Would also be nice to have a language swap button on this screen.

![screenshot from 2019-03-03 10-55-23](https://user-images.githubusercontent.com/6129479/53697782-ddff4080-3da2-11e9-96b9-111062dbfccc.png)

**Comment by lomky** [comment]
Alert upon login: `translation missing: es.devise.sessions.user.signed_in`

![screenshot from 2019-03-03 10-56-39](https://user-images.githubusercontent.com/6129479/53697797-1272fc80-3da3-11e9-96ed-d891052ac726.png)

**Comment by lomky** [comment]
Confirmation box for deleting a call: "Are you sure you want to remove this call from the call log?", "Cancel", "OK".

![screenshot from 2019-03-03 11-03-15](https://user-images.githubusercontent.com/6129479/53697890-00de2480-3da4-11e9-8c1f-39e38417cd05.png)

(Unrelated, this is also an ugly box so we should theme it)

**Comment by colinxfleming** [comment]
From a fresh seed, logging a call for Other Contact:

![image](https://user-images.githubusercontent.com/3866868/53697981-dd67a980-3da4-11e9-9daa-dd96c2006d85.png)

**Comment by colinxfleming** [comment]
Most Recent Note in the note expander on the patient dashboard:

![image](https://user-images.githubusercontent.com/3866868/53697993-fa03e180-3da4-11e9-9434-0367d0099ff2.png)

**Comment by colinxfleming** [comment]
This is bizarre, but on the patient dashboard locale seems to reset to english in table content partials after a manual control-r reload. We might just file this as a bug and move on but wanted to log it.

![image](https://user-images.githubusercontent.com/3866868/53698033-8a422680-3da5-11e9-82c8-271bdc515b44.png)

Steps to recreate:

* Log in
* Switch to spanish
* Control-R to reload the page

**Comment by colinxfleming** [comment]
Another weird bug -- Status seems to lag one way or the other in the patient edit view if you click back and forth. Here's an example of the spanish Resolved Without DCAF on the english page: 
![image](https://user-images.githubusercontent.com/3866868/53698081-16ece480-3da6-11e9-9b0b-eb776fdecbda.png)

**Comment by colinxfleming** [comment]
If you update a field in the patient dashboard (top thing), it doesn't Respect The Localization when it reloads the weeks along calculations: 

![image](https://user-images.githubusercontent.com/3866868/53698103-4996dd00-3da6-11e9-8b66-952e4b4fc524.png)

To recreate:

* Go to a patient edit page
* Set appointment date to be sometime in the future

**Comment by colinxfleming** [comment]
I don't think we should worry about this for this round, but we should figure out what to do about the changelog field names:

![image](https://user-images.githubusercontent.com/3866868/53698190-6089ff00-3da7-11e9-9f45-0b0c4c71b824.png)

**Comment by colinxfleming** [comment]
Need to set locale in the clinic finder search:

![image](https://user-images.githubusercontent.com/3866868/53698243-f45bcb00-3da7-11e9-8eed-9fbc64cebe30.png)

**Comment by colinxfleming** [comment]
On logout, a missing translation: 

![image](https://user-images.githubusercontent.com/3866868/53698257-15bcb700-3da8-11e9-9dd9-592e48b96520.png)

**Comment by lomky** [comment]
Reset password and all else in the file `app/views/devise/shared/_links.html.erb`

![screenshot from 2019-03-03 15-26-06](https://user-images.githubusercontent.com/6129479/53701223-c33fc280-3dc8-11e9-8719-144ba1d6b3ab.png)

**Comment by lomky** [comment]
Missing translation:

![screenshot from 2019-03-03 15-39-50](https://user-images.githubusercontent.com/6129479/53701382-9ee4e580-3dca-11e9-8db3-73710e639be2.png)

To recreate:  
Hit forgot password  
Hit me password reset intructions

**Comment by lomky** [comment]
For later, we should standardize our Devise wording either into separate files, or included in the base locale file, but not both.
