### ISSUE TITLE
Translate changelog

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1638]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Here's the changelog in spanish:

![image](https://user-images.githubusercontent.com/3866868/53698190-6089ff00-3da7-11e9-9f45-0b0c4c71b824.png)

We should translate the actual table content.

* **What feature or behavior is this required for?**

A bell and whistle for translations. Would be helpful to be able to crunch this without skipping back and forth between spanish and english.

* **How could we solve this issue? (Not knowing is okay!)**

TBD. Probably this is an issue where we want to be referring to model field i18n tags but we can figure out how to do that later.

* **Anything else?**

broken out from #1633

**Comment by lomky** [comment]
I think we have them all, and if we dont we can do individual tickets like #1921
