### ISSUE TITLE
Change log: Translate patient model fields to spanish

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1658]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

The changelog uses english for all the model attributes. This makes it hard to read if you are a spanish CM who needs to work thru it.

* **What feature or behavior is this required for?**

Consistency!

* **How could we solve this issue? (Not knowing is okay!)**

This is probably going to be tough. I think we have to go thru individual fields on patient and add them to a namespace along the following: `mongoid.attributes.MODEL.FIELD`. Clinic is already in there as an example.

* **Anything else?**

not a blocker for spanish release

**Comment by lomky** [comment]
@colinxfleming Is this a repeat of #1638?

**Comment by colinxfleming** [comment]
it definitely is, thanks for flagging!

I found out a pretty surgical adjustment that I think is going to work.

**Comment by lomky** [comment]
I _think_ we have them all, and if we dont we can do individual tickets like #1921
