### ISSUE TITLE
JS: Port clinics.coffee from coffeescript to ES6

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1681]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

We're porting our custom javascript to ES6! This ticket is to port over:

clinics.coffee into app/javascript/src/clinic_select_filter.js

* **What feature or behavior is this required for?**

Long term project health and maintainability, plus an opportunity to clean up some of our messes when we wrote this the first time.

* **How could we solve this issue? (Not knowing is okay!)**

Rewrite the coffeescript in app/assets/ to be ES6 in app/javascript/src.

* **Anything else?**

See #1679 for an example of this with the `clinic_finders` js.

If this winds up requiring adding dependencies or something, please hit me up in slack!

**Comment by jmhooper** [comment]
I'll grab this one and see how far I can get.
