### ISSUE TITLE
JS: Port pledge calculator part of patients.coffee from coffeescript to ES6

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1683]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

We're porting our custom javascript to ES6! This ticket is to port over:

patients.coffee into app/javascript/src/pledge_calculator.js

Note that this file contains a lot of unrelated functionality, so no need to port it all over at once!

* **What feature or behavior is this required for?**

Long term project health and maintainability, plus an opportunity to clean up some of our messes when we wrote this the first time.

* **How could we solve this issue? (Not knowing is okay!)**

Rewrite the coffeescript in app/assets/ to be ES6 in app/javascript/src.

* **Anything else?**

See #1679 for an example of this with the `clinic_finders` js.

If this winds up requiring adding dependencies or something, please hit me up in slack!

**Comment by colinxfleming** [comment]
This one is patients.coffee L4-L48, 60-68, and 77-82

**Comment by bravogolfgolf** [comment]
I will take this one.
