### ISSUE TITLE
Add option to start budget week on non-Monday

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1698]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Per correspondence, BRAF is experimenting with weekly budgets and planning on having their budget start day be on something that isn't monday, which isn't as helpful since there's a day shift. To that effect, we should make it so that this is config-able.

* **What feature or behavior is this required for?**

proper budget bar functioning if you are not dcaf or otherwise do not have monday/sunday budgets.

* **How could we solve this issue? (Not knowing is okay!)**

my hope is that this is a pretty minor thing, and that we can continue to keep mondays as the defaults. To that end, I'd say let's try adding a config called like `budget_start_day` that should be a day name (e.g. monday, tuesday, wednesday). The budget bar functions should use that day if exists, otherwise default to monday.

I don't know how tangled a web this is, I don't think very, but you know.

* **Anything else?**

not a terrible thing if this doesn't get done for a bit but we probably owe BRAF a solid.

This is probably a fun fishing expedition thru the budget bar code.

**Comment by valeriecodes** [comment]
I'll take a look at this.

**Comment by valeriecodes** [comment]
@colinxfleming I'm looking around and not finding where the budgets are calculated based on date, just the individual patient pledges. Would you be able to point me to a file in the codebase or a page in the app where I could see?

**Comment by colinxfleming** [comment]
@valeriecodes sorry, my bad for not adding more detail for this! Should have added more of a grand tour.

The method that generates the report is here: https://github.com/DCAFEngineering/dcaf_case_management/blob/master/app/models/patient.rb#L143 

The place this actually shows up in a view is the patient dashboard here: https://github.com/DCAFEngineering/dcaf_case_management/blob/master/app/views/dashboards/_budget_bar.html.erb and the helper that calls that actual method is here: https://github.com/DCAFEngineering/dcaf_case_management/blob/master/app/controllers/concerns/budget_bar_calculable.rb

My guess is that the move here is to add a start day optional argument to `Patient#pledged_status_summary` and alter `BudgetBarCalculable#budget_bar_calculations` so that it passes in a config. If that doesn't wind up being a viable option or not super straightforward let me know!

**Comment by mdworken** [comment]
@valeriecodes are you still working on this one? Mind if I grab it?

**Comment by valeriecodes** [comment]
Go ahead @mdworken !

**Comment by colinxfleming** [comment]
Resolved by #1709
