### ISSUE TITLE
Replace state text field with state_geo_tools gem list

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1733]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

I wrote a oneshot library that builds lists of states, `state_geo_tools`. Should use it in selects instead of text inputs where people are inputting state.

It looks like we have state

* app/views/clinics/_clinic_form.html.erb
* app/views/patients/_patient_information.html.erb
* app/views/patients/data_entry.html.erb

You'll see something like `<%= text_field :state, ... %>`. We want to drop that in favor of whatever the bootstrap form

Gold medal: Update our system tests!

* test/system/update_patient_info.rb
* test/system/data_entry_test.rb
* test/system/clinic_management_test.rb

You'll see something like `fill_in 'State', with: 'XX'` in a bunch of places. There's another thing we use for using dropdown selects, but I forget what it is exactly. There should be examples in there.

* **What feature or behavior is this required for?**

CMs are in a hurry sometimes and put in wild stuff. This reduces overhead and adds a nice guardrail for them so they don't put in bad data, which our data team has to then deal with.

* **How could we solve this issue? (Not knowing is okay!)**

add the gem, then replace the state text inputs with the gem's list.

Instructions to install the gem are at https://github.com/colinxfleming/state_geo_tools

* **Anything else?**

The gem's codebase is at: https://github.com/colinxfleming/state_geo_tools

You can use `StateGeoTools.state_codes` to return an array of states.

**Comment by geoffreyyip** [comment]
@colinxfleming I can give this a shot

**Comment by colinxfleming** [comment]
(Please leave for tech rebalanced volunteers!)

**Comment by valeriecodes** [comment]
I can grab this.

**Comment by colinxfleming** [comment]
open season on this!

**Comment by geoffreyyip** [comment]
@colinxfleming I don't have bandwidth right now. Hope someone else can get it!

**Comment by colinxfleming** [comment]
@Kevin-Wei we talked about using a different library for this, do you remember what it was?

**Comment by Kevin-Wei** [comment]
https://github.com/loureirorg/city-state/ <- had the most downloads, hasn't been touched in a 5 years which for a gem like this is a good thing

**Comment by colinxfleming** [comment]
it looks like it uses an ext db for data and the issues list is a little scary. I think I'd sorta prefer using hardloaded constants, but I think ultimately this is the implementer's choice.
