### ISSUE TITLE
Docker Build Broken

### ISSUE THREAD

**Issue by cassidyjean9** [DCAFEngineering/dcaf_case_management#1741]
![image](https://user-images.githubusercontent.com/51214010/62666526-c596e180-b951-11e9-9be6-47a168486b13.png)

**Comment by colinxfleming** [comment]
(this is what happens when, from a fresh clone, you run `docker-compose build && docker-compose up` and go to localhost:3000 in your browser.)

**Comment by tingaloo** [comment]
looking into this.

**Comment by tingaloo** [comment]
This stumped me, applying this https://github.com/rails/webpacker/blob/master/docs/docker.md didn't exactly work.

Webpacker is not being read in the web_1 docker build even after ```yarn install```
Going to look more into the dockerfile later.

**Comment by colinxfleming** [comment]
I think this mysteriously started working out of nowhere with a recent docker upgrade? would like to have someone besides me investigate this at hacknight.
