### ISSUE TITLE
Let's talk about whether moving to postgres is feasible

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1751]
I know a bunch of us have done some independent exploration of this, so I'm interested in getting a team decision on paper. Should we port DARIA over from mongodb to postgres? I would like to open up a discussion on this and make a team decision to commit for the next year or two years.

We originally picked mongoid because we thought it would jumpstart development, and it definitely did. By not worrying about database migrations we skipped a whole set of problems in the first year. But we should revisit that now and make sure this is something that still works for us, and that we want to still be on.

Some major benefits of switching to postgres
* postgres is much more well-standardized and we love rails defaults on this project
* postgres' ecosystem is probably going to be really great for a long time; a bunch of our mongo libraries are not super actively maintained. (god help us the day the mongo-session-store person is like 'I'm over this' and quits maintaining that library.)
* a major benefit of mongo is no migrations; we don't benefit from that nearly as much as we used to now that our data model has settled down
* as @BintLopez has pointed out to me, complicated stuff that we've been meaning to do like field encryption gets way easier/cheaper

Some major drawbacks:
* our patient conception does work really well within mongo's conception of Documents. We'd be doing a LOT more database queries and it would definitely not make anything clearer.
* non-zero chance that we'd lose patient history. Not that I think CMs and directors are doing that much with it now, but we'd probably have to blow it all away.
* the frontend architecture of this site could REALLY use some care, and this would probably be at its expense. (I might not feel this way after we finish migrating completely to webpack / bootstrap 4. but right now I definitely do)

Everyone should feel free to add their own benefits, drawbacks, questions, concerns, thoughts, opinions, etc. I'm interested in hearing whether people think this is a good idea, a good idea but too much of a lift to actually do for a team in maintenance mode, a good idea but now's the wrong time, a horrible idea, etc, and reactions.

If you have investigated this independently, I am interested in your thoughts.
If you are new to the project and thought mongo was easy or hard to get used to I would like your thoughts!
If you have been on this project for awhile and have opinions about mongo, I am interested in your thoughts.
Is there anything that we could do with postgres that we can't do with mongo?

**Comment by valeriecodes** [comment]
Would we get any benefits from the querying power of Postgres/SQL? I think that's where it shines the most, but if there's not a desire from the perspective of the project to do more complicated data analysis/modeling, then it seems like a lot of trouble in data migration for a limited payoff.

**Comment by Kevin-Wei** [comment]
Wild thing I've heard about as a migration path is dumping entire DB's into the JSON-B columns first and then going from there. At a minimum JSON-B columns let you dump the truly unstructured data somewhere.

**Comment by colinxfleming** [comment]
Checking in from my sabbatical to post about this - the more I've thought about it, the more I've come down on the side of making the swap over, even knowing what a huge pain it's going to be. The reasons I think this are a good idea include:

* the main benefit that we get from mongo is that it's very easy to iterate on. Since we're no longer building out models as fast as we can, the pain of managing migrations in a shared codebase doesn't sound as hard.
* mongo is pretty nonstandard; my experience is that even with the mongoid abstraction onto activerecord, this is the part of the DARIA stack where people are like 'what is this'.
* as we've seen with mongoid userstamp, for example, the mongoid rails ecosystem is not exactly pumping in 2020. We nearly had to start maintaining one of these ourselves; compare this to, say, `activerecord-session_store` which is maintained by the rails core team.
* postgres plugs into nearly everything. If we wanted to, say, use Mode Analytics as our reporting system of record we could.
* the document model has served us pretty well (basically everything is under Patient, with the exception of User and Clinic), but if we want to get into doing a react or a stimulus or something, pg will be a lot easier for this by making it available to query related objects independently rather than refreshing a full doc.
* as @valeriecodes noted, where pg really shines is the analysis power. We heard from a few funds during our recentl working group that they DO want to do data analysis, a LOT. We've had a couple of ill-fated start/stops on this, but the fact is that ruby alone just isn't great at this, and a separate python/shiny app forks our codebase in some really unpleasant ways. I would bet that data analysis types speak sql more readily than they do ruby, so it's a bonus for the programming side (and helps make our reporting stuff much more robust for actual funds, so there's a major client benefit too). The alternative is, like, learning mongoid mapreduce.

What we lose:
* fast model iteration. The last time we did a new model was practical support and it saved us a lot of time and iteration to NOT do migrations.
* the ability to not worry about migrations at all. This was legit wonderful and we'll be sad it's gone.
* development time. This is not a slim undertaking and while it will suck less than bootstrap 3 -> 4 it's definitely not going to be pleasant.

I think this is worth it.

**Comment by colinxfleming** [comment]
oh, I almost forgot thebig one, which is that `attr-encrypted` on mongoid is EXTREMELY hard but attr-encrypted on pg is ez breezy by comparison.

**Comment by colinxfleming** [comment]
postgres!
