### ISSUE TITLE
Squelch js vulnerabilities

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1755]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

The following things are things in our yarn.lock which need updating to squash vulnerabilities:

* fstream (update to @^1.0.12)
* lodash (update to @^4.17.13)
* lodash.template (update to @^4.5.0, but might be covered if we update lodash?)

* **What feature or behavior is this required for?**

keeping our build clear and making sure we're handling js vulnerabilities!

* **How could we solve this issue? (Not knowing is okay!)**

I actually have no idea how to update dependencies in yarn, so this is a good learning experience for us all! 

* **Anything else?**
nope!

**Comment by tingaloo** [comment]
i'll check this out.

**Comment by tingaloo** [comment]
should we handle criticals only?

**Comment by colinxfleming** [comment]
If you want to resolve others that arent listed critical, i would say go
for it
