### ISSUE TITLE
Add option for monthly tracking to budget bar (DUE: Nov 1)

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1770]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Carolina is mostly set with our existing suite, but they do calculate their budget monthly. After confirming with them that they aren't going to use the budget bar as their canon budget system, I think it's reasonable to support this as an option, so let's add it as a config.

(This is starting to stretch our way of doing config UX a little bit, but we should be okay for a little while longer.)

* **What feature or behavior is this required for?**

Supporting Carolina's budget practices. Current DARIA funds calculate their budgets by week, and at the end of the week, they top off the money available to pledge on abortion care. Carolina does this but by month, so basically the timespan they care about is the first through the last of the month.

* **How could we solve this issue? (Not knowing is okay!)**

let's press the `start_of_week` config into service here and add an option where if it's `monthly`, then we calculate monthly. I think the things we'll change along the way are:

* `Patient#pledged_status_summary` (I think this is currently expecting a day so we'll want to make some adjustments to how it filters on time. I would see if there is a `beginning_of_month` thing that rails provides which we can press into service?)
* adjust the view `dashboards/_overview` to be smart enough to account for months instead of weeks. Please do rename any variables along the way to make it clear that this can either be months or weeks!

I THINK that should do it?

* **Anything else?**

would be good to have this in place by Dec 1 if possible; should have in place no later than than Dec 31

**Comment by lomky** [comment]
Working on this!

**Comment by colinxfleming** [comment]
Added due date to the issue title -- CAF is coming on Nov 1 and we should aim to have this in place for them then, or shortly after.
