### ISSUE TITLE
Fix factorybot deprecation warnings

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1793]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

I was getting my test on this afternoon and I noticed this deprecation warning:

```
Colins-Air:dcaf_case_management colin$ rails test test/models/event_test.rb 
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:

role { "cm" }

 (called from block (2 levels) in <top (required)> at /Users/colin/repos/dcaf_case_management/test/factories/user.rb:9)
Run options: --seed 48476
```

Let's squelch this deprecation warning!

* **What feature or behavior is this required for?**

Keeping our dependencies fresh!

* **How could we solve this issue? (Not knowing is okay!)**

Pretty much do what the deprecation warning says to do to fix it. This might be a fun journey to find out what a block is and how it works!

* **Anything else?**

nope!

**Comment by andersonfernandes** [comment]
Hi @colinxfleming, I could work on this issue if it's ok to you.

**Comment by colinxfleming** [comment]
@andersonfernandes that would be delightful! Don't worry about CI failures on your fork, those are because of some circleci deal. Let me know if I can be helpful on anything!

**Comment by andersonfernandes** [comment]
@colinxfleming it's a pleasure to help on such great project. I'm available to work on new fixes or features.

**Comment by colinxfleming** [comment]
@andersonfernandes we try and make it a point to keep the issues list pretty fresh, so I would advise skimming it and seeing if anything not marked `future features` or `admin` looks juicy. if something does, please post in the issue and let me know you're working on it so we don't assign it out to another vol. I am always around in issues or slack to be helpful if you ever have any questions or need clarificationon anything though!
