### ISSUE TITLE
BS4: Fix the 'Generate your Pledge' button

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1822]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
On the BS4 upgrade the PDF generator button isn't working! 

To recreate: make sure your patient has an appointment date, a clinic name, and all the funding squared away. Then hit "Submit Pledge", "Next", and "Generate your Pledge". It should offer a pdf download, but isn't!

* **How could we solve this issue? (Not knowing is okay!)**

Checkout the `bs4-2` branch and make a new branch off it. Fix from there, then PR back to `bs4-2`.

```
git pull
git checkout bs4-2
git checkout -b bs4-2_fix_generate_pledge
# Do the work!
git push
# Submit a PR!
```

**Comment by colinxfleming** [comment]
To recreate:

* Log in at localhost:3000 and pick DC as your line
* On the patient dashboard, find the patient named `Clinic and Appt - 2` and click on their name to go to their patient edit view
* Once there, click on the Abortion Information link and enter 100 in the `DCAF pledge` field. This should log the amount of money the case manager's going to send.
* At this point, we're ready to generate a pledge. Click the `Submit Pledge` button to pop up a modal, and then click next.
* At this point you should see this form:

![image](https://user-images.githubusercontent.com/3866868/67135644-c2d62980-f1e9-11e9-9092-a5ae9576eab7.png)

If you enter your name and smash the `Generate your pledge` button, it should make a fake PDF, but on this branch it doesn't. We're good to go when it downloads a PDF again!

**Comment by colinxfleming** [comment]
(Please leave for tech rebalanced volunteers!)

**Comment by colinxfleming** [comment]
Bit by the form_with being remote by default again!
