### ISSUE TITLE
BS4: User & Clinic Management Pages Button Styling

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1823]
* **What are we trying to do?**
BS4 ticket! The Styling of the Add New buttons on our User Management Page and Clinic Management Page look like they've been activated, when they should be idle.

![Screenshot from 2019-10-18 19-32-08](https://user-images.githubusercontent.com/6129479/67135068-ea29f800-f1e3-11e9-83d2-24a93648686f.png)

We want to make this look like other buttons on the site, for example: 

![image](https://user-images.githubusercontent.com/3866868/67135502-5575c900-f1e8-11e9-8a82-cca3a22dabc8.png)

* **What feature or behavior is this required for?**
A E S T H E T I C

* **How could we solve this issue? (Not knowing is okay!)**

Checkout the `bs4-2` branch and make a new branch off it. Fix from there, then PR back to `bs4-2`.

```
git pull
git checkout bs4-2
git checkout -b bs4-2_admin_styling
# Do the work!
git push
#Submit a PR!
```

**Comment by colinxfleming** [comment]
Once you've pulled down the proper branch, you can see this by going to the URL localhost:3000/users . The file itself that generates that view is in app/views/users/index.html.

Embarrassingly I don't know where the CSS classes for this live!

**Comment by colinxfleming** [comment]
(Please leave for tech rebalanced volunteers!)
