### ISSUE TITLE
Status Helper Text should update alongside the Status Text

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1825]
* **What are we trying to do?**
Our Status field dynamically updates without having the whole page reload, which is great! But the helper text associated with it (hover on the "?") does not! So they can mismatch :frowning: Can we make it update dynamically too?

To recreate: After seeding your data, click a patient with status "Needs Appointment". Notice the hover text matches! Pick an appointment date. The Status updates to Fundraising, but the helper text is left behind!

** Another Example
![Screenshot from 2019-10-18 19-29-06](https://user-images.githubusercontent.com/6129479/67135613-80ace800-f1e9-11e9-88a5-a2449e8e902a.png)

* **What feature or behavior is this required for?**
Clarity for our Case Managers.

* **How could we solve this issue? (Not knowing is okay!)**
Probably similar to how we make the Status field update?

**Comment by colinxfleming** [comment]
Rails has a cool thing that runs some javascript when an endpoint gets hit -- it's (pretty sick)[https://guides.rubyonrails.org/working_with_javascript_in_rails.html#server-side-concerns]! The javascript actually executing when you update a patient is in app/views/patients/update.js.erb .

**Comment by colinxfleming** [comment]
(Please leave for tech rebalanced volunteers!)

**Comment by harumhelmy** [comment]
Unless we're still waiting on Tech, Rebalanced vols, I'd love to take a crack at this!

**Comment by colinxfleming** [comment]
we aren't! go for it @harumhelmy
