### ISSUE TITLE
Make the Fax Service link less finicky

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1826]
* **What are we trying to do?**
We have the fax URL set as a user configurable option. Right now if the user forgets to type `https://` at the front of the link in the Configuration Management entry, the link at the bottom of the page is broken. It works fine if they have the https, but let's make the app worry about this instead of putting it on our users! Let's make it work regardless of https or not.

#### Broken
![Screenshot from 2019-10-18 21-00-56](https://user-images.githubusercontent.com/6129479/67135705-793a0e80-f1ea-11e9-8286-ef8a40824084.png)

#### Working!
![Screenshot from 2019-10-18 21-01-27](https://user-images.githubusercontent.com/6129479/67135704-793a0e80-f1ea-11e9-8192-f3a26d008b1c.png)

**Comment by colinxfleming** [comment]
The way we do Configs is via a Config model in `app/models/config.rb` -- basically it saves a unique config row to the database, and that gets invoked in `app/views/layouts/_footer.html.erb`, by a `fax_service` function in `app/helpers/footer_helper.rb`.

There are a few different ways to handle this and you can pick your poison:

* We can handle it on the Config model level by adding a class method like `self.start_day` has, and append `https://` if it's not there. We'll want to make a change in `FooterHelper` to account for that if so.
* Alternatively, we can do that check completely in FooterHelper and do all the string checking and handling there. Dealer's choice!

Bonus points if you add tests!

**Comment by colinxfleming** [comment]
(Please leave for tech rebalanced volunteers!)

**Comment by Kevin-Wei** [comment]
I'm def not going to get bonus points here.

**Comment by Kevin-Wei** [comment]
might actually get bonus points here
