### ISSUE TITLE
CSV Export shows all TRUE for special circumstances

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1827]
* **What are we trying to do?**
Our CSV export provides a limited about of anonymized information, including a boolean field specifying whether the patient had any Special Circumstances checked under Patient Information. But right now it is exporting TRUE for everyone, regardless of whether there are any checked.

 - Fix the CSV export to properly export `has special circumstances`
 - Update our tests to check that!

To reproduce, click the admin dropdown in the upper right and click 'Export anonymized CSV'

* **What feature or behavior is this required for?**
BRAF bug request!

**Comment by colinxfleming** [comment]
Popping this out of the TR milestone since a fix became available quickly. I will write up a data analysis ticket.
