### ISSUE TITLE
Update system tests to account for changes to data_entry workflow

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1828]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

We recently merged https://github.com/DCAFEngineering/dcaf_case_management/pull/1815/files which updated our data entry workflow with some new fields. We want to now update the test in test/system/data_entry_test.rb to match.

Specifically, we added these form fields:

* language
* voicemail_preference
* referred_to_clinic
* completed_ultrasound
* resolved_without_fund

We should follow the pattern in data_entry_test of entering in values for these fields, saving the patient, and then checking that the values saved properly.

* **What feature or behavior is this required for?**

Keeping our data entry mode well tested, and ensuring that it doesn't eat data!

* **How could we solve this issue? (Not knowing is okay!)**

We do something pretty similar in test/system/update_patient_info.rb - there's probably stuff in there we can crib for this!

* **Anything else?**

Rails' documentation on system tests is here: https://guides.rubyonrails.org/testing.html#system-testing

These are tests that are basically issuing commands to a web browser and seeing what happens. You can run them with `rails test:system`.

You also have to install a lot of junk to run them to get them to run, so don't worry about seeing it work, just whip up something that seems reasonable and pull request it. Usually we run these in an external system that's set up to handle them so developers don't have to.

**Comment by colinxfleming** [comment]
ps the actual view is available at localhost:3000/data_entry and the file is app/views/patients/data_entry.html.erb

**Comment by colinxfleming** [comment]
(Please leave for tech rebalanced volunteers!)

**Comment by valeriecodes** [comment]
I can take a look at this.
