### ISSUE TITLE
Build rake task to generate fake data

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1835]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

This would have been extremely helpful as we let some data scientists at DARA today! Let's build a rake task that will just generate like 5k rows of fake patients for export.

* **What feature or behavior is this required for?**

Safely giving people something they can try analysis scripts against.

* **How could we solve this issue? (Not knowing is okay!)**

Here's a starter kit. We need to add calls, external pledges, practical supports, and fulfillments at the least, and also account for the fact that a lot of this stuff is naturally null.

```
users = User.all
clinics = Clinic.all

10000.times do |i|
  flag = (rand(10) % 5 == 0)

  initial_call = Date.today - rand(1000)

  has_appt = rand(3) % 2 == 0

  has_pledge = rand(3) != 2

  patient = Patient.create!(
    name: 'Randomized Patient',
    primary_phone: "#{i}".rjust(10, '0'),
    initial_call_date: initial_call,
    urgent_flag: flag,
    line: i.even? ? 'DC' : 'MD',
    clinic: has_appt ? clinics.sample(1).first : nil,
    created_by: users.sample(1).first,
    appointment_date: has_appt ? initial_call + rand(30) : nil,
    last_menstrual_period_weeks: rand(15) + 7,
    last_menstrual_period_days: rand(7),
    procedure_cost: has_appt ? rand(600) : nil,
    pledge_sent: has_appt && has_pledge,
    patient_contribution: rand(400),
    fund_pledge: has_appt ? rand(300) : nil
  )
end
```

**Comment by harumhelmy** [comment]
I've never built a rake task before but I'm interested in trying it out - maybe pairing with @mdworken this weekend? :)

**Comment by marycodes2** [comment]
@harumhelmy I'd be happy to pair with you if you'd like!

**Comment by harumhelmy** [comment]
Sorry this is taking me ten million years to get started on! But I am working on it, hoping to show my work sometime this week :)
