### ISSUE TITLE
Replace bootstrap_form_for with bootstrap_form_with

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1861]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Rails used to do forms that were backed by models with `form_for obj` and forms that just hit a URL with `form_tag url`. Around 5.1 they introduced `form_with`, which took a keyword argument `url` or `model` and could do either. (We generally use `bootstrap_form_for`, which is basically just a little bit of extra styling but is pretty much the same as `form_for`.

A primer on `form_with`: https://m.patrikonrails.com/rails-5-1s-form-with-vs-old-form-helpers-3a5f72a8c78a

We have several instances of `bootstrap_form_for` that I would like to convert to `bootstrap_form_with`:

```
Colins-Air:dcaf_case_management colin$ git grep bootstrap_form_with
app/views/accountants/_search_form.html.erb:  <%= bootstrap_form_with url: 'accountant/search', remote: true, layout: :inline do |f| %>
app/views/clinicfinders/_search_form.html.erb:    <%= bootstrap_form_with url: clinicfinder_search_path,
app/views/clinics/_clinic_form.html.erb:<%= bootstrap_form_with model: @clinic, local: true do |f| %>
app/views/configs/_config.html.erb:    <%= bootstrap_form_with model: config, inline: true do |f| %>
app/views/dashboards/_search_form.html.erb:  <%= bootstrap_form_with url: '/search', layout: :inline do |p| %>
app/views/devise/sessions/new.html.erb:      <%= bootstrap_form_with model: resource, as: resource_name, url: session_path(resource_name), local: true do |f| %>
app/views/lines/new.html.erb:    <%= bootstrap_form_with url: lines_path, local: true, class: 'line-select-form' do |f| %>
app/views/patients/_abortion_information.html.erb:  <%= bootstrap_form_with model: patient,
app/views/patients/_abortion_information.html.erb:  <%= bootstrap_form_with model: patient,
app/views/patients/_fulfillment.html.erb:  <%= bootstrap_form_with model: patient,
app/views/patients/_new_patient.html.erb:<%= bootstrap_form_with model: patient do |f| %>
app/views/patients/_notes.html.erb:  <%= bootstrap_form_with model: [patient, note],
app/views/patients/_patient_information.html.erb:  <%= bootstrap_form_with model: patient,
app/views/patients/_pledge.html.erb:          <%= bootstrap_form_with url: generate_pledge_patient_path(patient),
app/views/patients/_pledge.html.erb:      <%= bootstrap_form_with model: @patient,
app/views/patients/data_entry.html.erb:<%= bootstrap_form_with model: @patient,
app/views/users/_search_form.html.erb:<%= bootstrap_form_with url: users_search_path,
app/views/users/edit.html.erb:    <%= bootstrap_form_with model: @user do |f| %>
```

We've done all the URL ones, but there are a bunch of model ones still in the codebase; this is to get them out.

* **What feature or behavior is this required for?**

Easy rails upgrades!

* **How could we solve this issue? (Not knowing is okay!)**

* go thru the list of bootstrap_form_for and change them to `bootstrap_form_with model: patient`  (or whatever the model object is).
* `bootstrap_form_with` is `remote: true` by default, so for any that ARE NOT `remote: true`, make sure you add `local: true` to the options hash.
* confirm that tests still pass

* **Anything else?**

There are a few tricky ones in there - I don't know how `bootstrap_form_with` will handle nested models like `[patient, new_external_pledge]` such as in app/views/external_pledges/_new.html.erb. Please feel free to ask for help if that is not a free basket!

**Comment by harumhelmy** [comment]
I'll take this! I'll be sure to ask for help as things break.

**Comment by harumhelmy** [comment]
Taking another crack at this! FOR REAL THIS TIME
