### ISSUE TITLE
Surface what roles do in app

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1868]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

@NerdyGirl537 quite accurately pointed out that roles are really confusing - it's not clear to anyone in the UI who has access to what, or what permissions they're granted. We should surface some information about what these roles actually do in the user management tools!

* **What feature or behavior is this required for?**

Not requiring specialized knowledge to operate a DARIA instance safely!

* **How could we solve this issue? (Not knowing is okay!)**

Let's do this in two ways:

* define role information on some constants in the user model
* on the user create page, let's add information about each of the roles below our current 'New users automatically...' helper text.
* on a user edit page, let's add the explanation text for each of the roles under the role buttons. (the user edit page is kinda cramped so feel free to add some whitespace if you like!)

* **Anything else?**

Here's some text you can use:

* CM: 'The Case Manager role is for people doing patient intake and making calls. This gives access to the main call list dashboard, the individual patient record page (minus the ability to edit fulfillment info), and the data entry page.'
* Data volunteer: 'The Data Volunteer role is for people who require access to data or accounting tools. This gives access to what CMs have, plus the following: accounting tools for pledge reconcilling, reporting tools with summary data on patient intake, the fulfillment tab on the individual patient record page, and the ability to download an anonymized spreadsheet of data for analysis.'
* Admin: 'The admin role is for people who are managing their fund's DARIA instance or case manager corps. This gives access to what CMs and Data Volunteers have, plus the following: user management tools, clinic management tools, DARIA instance configuration tools, and the ability to delete patients from the individual patient record page (such as in the case of a duplicate entry).'

Please keep these assigned to different variables in case we want to use them in different places later.

**Comment by NerdyGirl537** [comment]
I thought it would be helpful to also say what function those tabs for the data volunteers have. Wasn't 100% on the phrasing. Suggestions greatly appreciated.

**Comment by colinxfleming** [comment]
How about:

> The Data Volunteer role is for people who require access to data or accounting tools. This gives access to what CMs have, plus the following: accounting tools for pledge reconcilling, reporting tools with summary data on patient intake, the fulfillment tab on the individual patient record page (for marking pledges as paid out), and the ability to download an anonymized spreadsheet of data for analysis.

Does that cover it, or are there spots we're still missing?

**Comment by NerdyGirl537** [comment]
Looks good to me. @lwaldsc @alisonnjones thoughts?

**Comment by evornov** [comment]
I'm taking a look!

**Comment by colinxfleming** [comment]
@evornov got super close on this at hacknite, so I'm going to pull this out of active work while we wait for it to drop.
