### ISSUE TITLE
Install Chrome in Docker to run system tests

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1874]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

I'd like to be able to run systemtests in github actions, but when you run this command it errors out with something like "chrome not found in path": `docker-compose run --rm web rails test test/system/routing_test.rb`

If we COULD run that, we'd be able to get builds working in github actions! which would be good because it would hopefully fix the problem of 'all builds on forks are failing'. So let's set up chrome in the docker container.

We can declare victory when `docker-compose run --rm web rails test test/system/routing_test.rb` returns a green result instead of erroring out.

* **What feature or behavior is this required for?**

running system tests in both local environments and github actions; swapping to a CI system that works.

* **How could we solve this issue? (Not knowing is okay!)**

In CircleCI we use an image they have with browsers installed: https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/ruby/images/2.6.5-buster/node-browsers/Dockerfile

We might be able to adapt this to our use.

* **Anything else?**

**Comment by duaimei** [comment]
Unless somebody else says anything. I will be taking a look at this ticket next week.

**Comment by duaimei** [comment]
I'm still working on this.

**Comment by colinxfleming** [comment]
thanks much @duaimei , let us know if we can be helpful!

**Comment by duaimei** [comment]
I am still working on this issue, for about an hour a week. I got Chrome driver installed, but it isn't respecting the argument options for selenium. 

https://github.com/heroku/heroku-buildpack-google-chrome/issues/56
(except none of the accepted solutions have worked) 

A lot of the examples that I am seeing on the internet are using RSpec. RSpec has some integration with selenium, so I might end up giving that a go and seeing if it resolves the issue.

Something like this:
https://medium.com/@jfroom/docker-compose-capybara-selenium-standalone-for-dev-ci-6514bf16d77b
or
https://medium.com/@sbounmy/docker-compose-rails-react-selenium-capybara-65fa74250fa7
