### ISSUE TITLE
Data entry mode causes pledges to write to budget bar

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1882]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
If you add a patient with a pledge in data entry mode, their pledge shows up on the budget bar. This is bad news, because the budget bar is supposed to be for pledges that case managers are making, not historical pledges. We should make it so that making a new patient in data entry mode doesn't bump the budget bar.

* **What feature or behavior is this required for?**
Non-scary looking, and usable, budget bar.

* **How could we solve this issue? (Not knowing is okay!)**
Without looking at the actual code, we could probably send the Patient model callback a flag to not write the field that the budget bar populates on. I suspect that would solve this problem going forward.

* **Anything else?**
potential curveball: does this happen on sent pledges too, or just logged amounts of money?

**Comment by harumhelmy** [comment]
Hiya! Would love to help with this but having some trouble figuring out how to access data entry mode. I changed one of the test users' roles to a data_volunteer and still can't find it. Might be missing something obvious here but would love some help :) @colinxfleming

**Comment by colinxfleming** [comment]
ah, sorry! There's a data entry workflow at http://localhost:3000/data_entry .

**Comment by lomky** [comment]
data entry now allows you to enter the dates manually, avoiding having them hit the budget bar!
