### ISSUE TITLE
Extend Config Model with Validations

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#1888]
* **What are we trying to do?**
Extend the Config model to provide validations for each field.

These validations should be optional, and defined in the code. When the fund admin then enters data into the config field these validations will inform them if the input is invalid.

I.e. `budget_bar_max` will want to enforce an int with no `$` on it. `start_of_week` should be either a day (`Monday`, `Tuesday`, etc) or `Monthly`.

The scope of  this ticket is the new field and it's application to the field, and tests therefore. 

Once implemented, file issues for each implemented Config to create the validations!

**Comment by colinxfleming** [comment]
let's start by enforcing the validation on `budget_bar_max` to knock out a straightforward one first. After we have a working example, we can release the rest into the hacknite pool I think.

**Comment by elimbaum** [comment]
Would love to chat about this at next hacknight - while browsing issues I realized I just (accidentally) replicated a good deal of @lomky's #2002 while working on #2153, so maybe we can bring this back!
