### ISSUE TITLE
Add a next step to the welcome email

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1897]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
@verbingthenoun noted that one of the things data vols consistently ask for is 'where exactly do I go now that I have an account'. The template that gets sent is in https://github.com/DCAFEngineering/dcaf_case_management/blob/master/app/views/user_mailer/ .

We should make it clear what the next step is, whether that's 'reach out to your volunteer manager for the URL', or including the URL in the mailer. Let's figure out which of those we should do and then implement.

* **What feature or behavior is this required for?**
making sure there's a clear next step when someone gets the welcome email; taking some strain off of volunteer managers.

* **How could we solve this issue? (Not knowing is okay!)**
Let's check the state of the art for welcome emails in sensitive environments. If it's cool, we should include a URL; if not cool, we should go with the explanation route. but we should do SOMETHING.

* **Anything else?**
stems from a conversation with @verbingthenoun

**Comment by verbingthenoun** [comment]
point of clarification: data volunteers don't actually get _any_ email when I create their account, at least if they're Gmail users

**Comment by colinxfleming** [comment]
@verbingthenoun as an fyi, the mailer issue bug should be fixed as of earlier this week! Sorry about that.
