### ISSUE TITLE
Docker on Windows fails to start application due to CRLF line endings

### ISSUE THREAD

**Issue by Jello** [DCAFEngineering/dcaf_case_management#1907]
Docker-compose up step fails on Windows due to git autoconversion to CRLF. This can be solved globally with git on Windows with:
`git config --global core.autocrlf false`
Which forces the Unix line endings expected by the Docker instance.

Will create a pull request that creates a .gitattributes file to specify this setting for the repo.

**Comment by colinxfleming** [comment]
resolved via https://github.com/DCAFEngineering/dcaf_case_management/pull/1908
