### ISSUE TITLE
Budget bar not catching pledge sents if they're in a different week from soft pledge

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1911]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
BRAF reported an unexpected behavior on the budget bar:

For a patient with a pledge amount filled in on one week and with a sent pledge the following week, that pledge doesn't show up in the budget bar. That's because the `Patient#pledged_status_summary` method only cares about `fund_pledged_at`, which we set when the `fund_pledge` field changes. We should probably ALSO make it care about `pledge_sent_at`, which is our timestamp for a pledge actually going out the door.

* **What feature or behavior is this required for?**
A budget bar that accurately reflects money moving. I think.

* **How could we solve this issue? (Not knowing is okay!)**
change https://github.com/DCAFEngineering/dcaf_case_management/blob/master/app/models/patient.rb#L150 to be either `fund_pledged_at` or `pledge_sent_at`.

* **Anything else?**

**Comment by harumhelmy** [comment]
On this!
