### ISSUE TITLE
Adjust Archive Window to Match Workflow Needs

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1914]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
@verbingthenoun has flagged that some patients are getting archived a little before the data team wants them archived. We should figure out a way to prevent this from happening.

@verbingthenoun suggested loosening this again, and @lomky suggested the new dates be:

1. Audited patients archive 6 months days after the day they were fulfilled, 

* **What feature or behavior is this required for?**
Proper auditing by the data team

* **How could we solve this issue? (Not knowing is okay!)**
Let's do this:
* Update the logic in Patient.archive_dateto match the above

* **Anything else?**
(this issue has morphed a lot - check the edit history & comments for context!)

**Comment by lomky** [comment]
Definitely happy to adjust this based on user needs!

**Comment by verbingthenoun** [comment]
hey all! we're still running into pretty significant issues with folks not being able to audit records because they're already archived, on the order of 20-30ish records per month. any update on this?

**Comment by verbingthenoun** [comment]
although, now that I've said that - changing timing of archive after audit actually won't fix this because these are patients that have NOT been audited yet. would it be helpful for me to give some examples of fulfillment dates on records that got archived too early?

**Comment by lomky** [comment]
Hey @verbingthenoun - I might have an explanation for what you're seeing. While we archive at different time frames for audited records, we don't actually archive based on `fulfillment date`, today. 

We actually archive based on the `initial call date`. For a patient with a audited pledge pledge, we archive when we pass 3 months after the initial call date, and for patients without an audited pledge, we archive a year after the initial call date.

All that said, it sounds like this timeframe isn't doing what you need it to! I'll spend some time this evening gathering what other ways we could set the time frame, and post with the options.

**Comment by lomky** [comment]
My proposal:

  - shift our 'fast track' archiving option to track on `fulfillment_date` - archive a patient **six months after their fulfillment is entered**
  - extend our dropoff catch - archive any patient who's `initial_call_date` is **over two years old ago**

@verbingthenoun would that timeline allow your folks to do their work before the patient data gets anonymized?

**Comment by verbingthenoun** [comment]
Yes @lomky that’s perfect!

**Comment by colinxfleming** [comment]
@verbingthenoun @lomky what are the odds we could keep the dropoff catch as is? That does a lot of lifting to prevent us from having duplicate patients, which tend to be tough for CMs to handle. would limiting to the fulfillment date swap would catch @verbingthenoun 's issues here?

**Comment by verbingthenoun** [comment]
ahhh, got it @colinxfleming - I think we could give it a try with just the post-fulfillment date changing and see how things go. Thanks!

**Comment by lomky** [comment]
@colinxfleming That was my initial instinct, but it sounds like the dropoff catch is what's causing the problem here, since these were unaudited patients

**Comment by colinxfleming** [comment]
@lomky is this still live, or is there more to resolve on this front?

@verbingthenoun is this still problematic?

**Comment by verbingthenoun** [comment]
Thanks @colinxfleming - yes, this is still an issue.

**Comment by colinxfleming** [comment]
Got it, thanks.

The solution we were poised to implement was `shift our 'fast track' archiving option to track on fulfillment_date - archive a patient six months after their fulfillment is entered`. @lomky does that still make sense as a remediation strategy? @verbingthenoun do we still feel this would fix the core issue you were describing here?

**Comment by verbingthenoun** [comment]
Yes, that should work!

**Comment by lomky** [comment]
Sounds good to me - updating the topline comment!

**Comment by verbingthenoun** [comment]
Hola friends. This issue is still ongoing but my thinking on this has changed--I think this might be a clinic side problem. We had at least one clinic send in all of their 2020 pledge forms going back to January in one batch in December. I have flagged this for the clinic liaison and hoping it can be resolved by clinics doing something other than WAITING AN ENTIRE YEAR to tell us how much funds they used.

**Comment by colinxfleming** [comment]
wut

**Comment by colinxfleming** [comment]
I'm going to pop this out of hacknights for now until we have a chance to sync, if that's okay. I think a fulfillment delay might still be a good thing but I want to have another conversation before we implement anything.

**Comment by lomky** [comment]
@verbingthenoun I love a good tl;dr - please and thank you.

So the main thing that has us hesitating on pushing the button to implement the solutions for your scenario 1 & 2 is the tension that archiving enables ease of handling repeat patients. The longer we go before archiving a patient, the chance that same patient calls back and we run into data entry errors increases.

That said, @colinxfleming and I can't think of any reason why we should be making the call on that tradeoff at the code level, instead of empowering funds to make the choice. How would you feel about setting these values to your fund's preference via a config, something like this mockup:

![archive config mockup](https://user-images.githubusercontent.com/6129479/110719278-935aff00-81da-11eb-9985-f2adf1d102c6.png)

**Comment by verbingthenoun** [comment]
Works for me!

**Comment by lomky** [comment]
Created #2150 to handle this work since this issue is pretty long and we've changed our minds a couple times on it.  Closing this one!
