### ISSUE TITLE
Missing changelog translation for clinic

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1921]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

I clicked into a random patient's changelog in sandbox and saw this:

![image](https://user-images.githubusercontent.com/3866868/74557263-c4acc100-4f2d-11ea-8d87-e6df0d5abc2a.png)

That seems like bad news! Let's fix it.

* **What feature or behavior is this required for?**

Error messages are displaying in routine use of the app, and that's Bad News.

* **How could we solve this issue? (Not knowing is okay!)**

I believe we can resolve this by adding translations to `en.yml` under mongoid.attributes.patient.clinic_id, but there might be a cleaner way to do it. Your choice on how to fix!

* **Anything else?**

To recreate:

* make a new patient
* set their clinic
* reload the page
* click into changelog

**Comment by arjunrawal07** [comment]
I'm picking this one up!
