### ISSUE TITLE
User docs: Accounting guide

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1942]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

We need a guide explaining what accountants functions there are. This should cover fulfillments, and the accountant view page.

* **What feature or behavior is this required for?**

Good reference documentation that we can share with people!

* **How could we solve this issue? (Not knowing is okay!)**

Write up a doc in `docs/user_guides/ACCOUNTING.md`. (`md` is the `markdown` format; see https://guides.github.com/features/mastering-markdown/ Generally, worry about the text and worry about the reviewer getting the markdown formatting right.)

* **Anything else?**
nope!

**Comment by colinxfleming** [comment]
probably we should document the following:

* how to get to the accountant panel
* how the search works (covers all lines)
* who's populating the table (patients who are marked as pledge sent)
* how the table gets populated (from a patient's fulfillment information)
* how to log that a patient's pledge was cashed (use the pen icon to fill in the fulfillment form)

**Comment by susanjw** [comment]
1. Log into Daria
2. Do not select a line. Instead, open drop down menu under Admin. 
3. Select Accounting from the drop down menu. This will allow you to search all lines. 
4. The Accountant Dashboard shows fulfillment information for patients that have been marked by case managers as "Pledge Sent." 
5. To log that a patient's pledge was cashed, use the pen icon on the right end of the relevant line.
6. To audit the patient's fulfillment information, confirm the information that has been entered and check the "Fulfillment audited?" box.
