### ISSUE TITLE
Resolve sendgrid-noaf issues

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1983]
I had an issue provisioning sendgrid for noaf. I have opened a ticket to resolve it with heroku, but want to keep tabs on it here so it doesn't slip.

Done when NOAF's daria instance is able to send emails.

**Comment by colinxfleming** [comment]
Post conversation with @xmunoz and with our inability to get sendgrid set up thru attachment I've rigged them up with a separate mailer (tied to my email for now), but we have to do some DNS auth before we get that set up. I'm going to hopefully crack into DCAF's DNS panel tomorrow and rewire things to allow us to send emails from DCAF's domain, and then rewire everything else to use that.

**Comment by xmunoz** [comment]
From the slack channel, it looks like @colinxfleming is hooking up all email sending to a newly purchased domain to resolve this issue and future sendgrid issues. Not sure that this solution is fully in place yet though.

**Comment by colinxfleming** [comment]
NOAF's instance and all other instances are now sending emails via this singular shared sendgrid from a dariaservices-specific domain. Have done all the associated cleanup I could find. gl hf!
