### ISSUE TITLE
On config page, dropdown configs should display as dropdowns

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#1990]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

On the config management panel, there are several options that are for fleshing out dropdowns. In the UI, though, they show up as lists of options with some confusing array notation:

![image](https://user-images.githubusercontent.com/3866868/82851429-cd6a4700-9ecd-11ea-85fa-a84aa68dd436.png)

These are selects, and they should show up as selects when you're mucking around with them!

![image](https://user-images.githubusercontent.com/6129479/92665330-48683980-f2d4-11ea-9bac-fef78d856e5e.png)

* **What feature or behavior is this required for?**

Not confusing people who are trying to configure a DARIA environment!

* **How could we solve this issue? (Not knowing is okay!)**

We do something similar in the `config.rb` model around help text overrides. I suspect we could do something similar to display the html over there. It may be tricky to map the specific config to the function using it though.

* **Anything else?**
As a bonus: if we can actually make them show are real dropdowns here, that's be _sweet_

**Comment by dcbeergoddess** [comment]
Gonna attempt to tackle this issue for Hacknight!

**Comment by lomky** [comment]
Going to throw this one back into the hacknight pool!
