### ISSUE TITLE
Pledged data entry patients should have pledge fields set on save

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#2019]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Right now the hook for update_pledge_sent_by_sent_at is only invoked on update, instead of on save. 
https://github.com/DCAFEngineering/dcaf_case_management/blob/f600471bb898df8cff1510c7857ee727f04c5a40/app/models/patient.rb#L29
This works smoothly in our regular flow, but can leave these fields unset when we create via the `/data_entry` route.

* **What feature or behavior is this required for?**
Make behavior on similar fields consistent, capture fallback pledging info for data entry. 

* **How could we solve this issue? (Not knowing is okay!)**
Update the call above to `before_save` instead of update, and update the function to ensure we are updating on change, similar to `update_fund_pledge_at`.
https://github.com/DCAFEngineering/dcaf_case_management/blob/f600471bb898df8cff1510c7857ee727f04c5a40/app/models/patient.rb#L285

* **Anything else?**

**Comment by arjunrawal07** [comment]
picking this up!

**Comment by lomky** [comment]
Back out for general work!

**Comment by colinxfleming** [comment]
hm I think this might still be live, going to reopen it until we have a chance to take an eyeballing. @xmunoz let me know if I'm reading wrong

**Comment by xmunoz** [comment]
That's correct. I initially accidentally linked my PR to this issue number instead of #2091 :/
