### ISSUE TITLE
Fix CodeCov

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#2024]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Fix the CodeCov!

* **What feature or behavior is this required for?**
Keeping an eye on coverage

* **How could we solve this issue? (Not knowing is okay!)**
dunno!

* **Anything else?**
might need admin access?

**Comment by lomky** [comment]
Got it to circle! not yet to codecov

**Comment by colinxfleming** [comment]
What's the next step here?

**Comment by lomky** [comment]
haven't the slightest - I realized while moving to `main` that we weren't tying to CodeCov anymore and our README badge was broken. my goal is to make sure we're keeping an eye on coverage numbers (and to brag about it)

**Comment by colinxfleming** [comment]
I opened up the codecov console and swapped some stuff on that over to main, but I suspect this will still need some ci reconfiguring regardless.

**Comment by colinxfleming** [comment]
Our umbrella's back due to #2083  - 
![image](https://user-images.githubusercontent.com/3866868/101266625-97303e80-371e-11eb-8e97-000d0b7e1a5b.png)

declaring victory!
