### ISSUE TITLE
Fix slow queries for mongodb Atlas migration

### ISSUE THREAD

**Issue by xmunoz** [DCAFEngineering/dcaf_case_management#2025]
The [migration prerequisites](https://docs.mlab.com/how-to-migrate-to-atlas/#migration-prereqs) for Mongodb Atlas indicate the following:

> If your deployment is on a Shared or Dedicated plan visit the “Slow Queries” tab to view and build the indexes recommended by mLab’s Slow Queries Analyzer. We strongly recommend building indexes for all recurring query patterns.

Here is the command to remove:
```
{"updated_at":{"$lte":"<val>"}}
```

It looks like this is considered a "slow query" across all of the clusters. It also looks like building this index is a single mouse-click. How do ya'll feel about me clicking that button?

![Screenshot from 2020-07-28 15-58-17](https://user-images.githubusercontent.com/1065196/88730601-4dd63f80-d0eb-11ea-913c-2411fce1ca23.png)

**Comment by lomky** [comment]
@xmunoz click it!

**Comment by xmunoz** [comment]
Alright, I've created those indexes. Since those indices was created for the `sessions` collection, and that collection is managed by a [3rd-party gem](https://github.com/mongoid/mongo_session_store), there is nothing else to really do there.

However, on two fund sites, the following queries are problematic because of an in-memory sort (i.e. `order_by` clause): [patients.rb line 148-154](https://github.com/DCAFEngineering/dcaf_case_management/blob/main/app/models/patient.rb#L148) and [accountants_controller.rb line 39-41](https://github.com/DCAFEngineering/dcaf_case_management/blob/main/app/controllers/accountants_controller.rb#L39).

Possible solutions: Do the sort in ruby, not in Mongodb. Alternatively, build a compound index to support more efficient lookups for these queries. There are trade offs for each solution.

**Comment by xmunoz** [comment]
We went ahead with the migration without fixing the slow queries. These queries probably need to be rewritten as the number of records grows.

**Comment by xmunoz** [comment]
This can be closed once #2072 is closed, since we will be moving off of Mongo.

**Comment by xmunoz** [comment]
No longer relevant
