### ISSUE TITLE
Add a Zip Code field to the Patient Model

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#2053]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
(Re)add the Zip Code field for Patients

* **What feature or behavior is this required for?**
Chicago needs zip codes to provide accurate funding info! Rather than have them hack it into another field, let's explicitly support Zip Code so we can make sure we're properly clearing it on archive.

* **How could we solve this issue? (Not knowing is okay!)**

We removed this field _way back_ in 2017 as we had no need for it. Issue #1053 and PR #1056. 

Adding it back to the Patient model & the patient info view it was removed from is a great start! Also add it in on the data_entry view: 
https://github.com/DCAFEngineering/dcaf_case_management/blob/bf38f20d99f25942190222acdd24e5ec54360ab7/app/views/patients/data_entry.html.erb#L48-L49

Think about where to add this back into tests, if anywhere!

* **Anything else?**
Non-archiving field, so no need to add to Archive Patient

**Comment by arjunrawal07** [comment]
Picking this up!
