### ISSUE TITLE
Upgrade to Capybara 3

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#2062]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Upgrade our Systems Tests gem Capybara to version 3. V2 is two years old and has started throwing a lot of deprecation warnings at us.

* **What feature or behavior is this required for?**
App Health

* **How could we solve this issue? (Not knowing is okay!)**
 - Remove the version lock on Capybara in the `Gemfile`
 - Run `bundle update capybara`
 - Address any failing tests

* **Anything else?**

**Comment by colinxfleming** [comment]
Claiming this (as a reintroduction to programming in rails, since I have done exactly zero of that for awhile)
