### ISSUE TITLE
Prevent changes to custom configs from clobbering existing values

### ISSUE THREAD

**Issue by elimbaum** [DCAFEngineering/dcaf_case_management#2084]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
When custom configurations change (insurance, voicemail, language, etc.), we don't want users with the old values to be broken. Currently, both insurance & voicemail implement special code to show the available options, _as well as_ the current value, if not already part of the database. The current system exhibits slightly weird behavior (i.e. if a config is changed or deleted, the user will keep their old value, until any other field is updated; this change occurs silently).

* **What feature or behavior is this required for?**
Reliability of custom configurations; maintenance of user data across config changes. 

* **How could we solve this issue? (Not knowing is okay!)**
I think the best way to do this is to change over calls to `options_for_select` to a helper function which adds the current value if not already present. Pretty much just move the custom insurance + voicemail code into a function that is accessible from all fields. Not all fields have to use the updated version, of course.

**Comment by colinxfleming** [comment]
This plan of attack as written (which I understand to be, basically, 'apply our practices around voicemail pref and insurance to other dropdown-selects') sounds great to me! Thanks very much for taking the time to make an issue about this - will look forward to seeing what you come up with on this front.

**Comment by elimbaum** [comment]
I'm also thinking about adding some kind of alert to users, so they know certain values are outdated. But I'm not sure how to do that in a way that is intuitive. I can't really think of a universal "this value is outdated, please update it!" symbol.

Some ideas: [this is what the select box would look like]

```
Medicaid
Cigna
Old Insurance company (change me!)
```

```
Medicaid
Cigna
Old Insurance company (old)
```


```
Medicaid
Cigna
[!] Old Insurance company
```

```
Medicaid
Cigna
[⏰] Old Insurance company
```

If I use a symbol, would probably need some kind of help text near the select box to explain what it meant.

**Comment by colinxfleming** [comment]
I think the instincts you're showing here are right on, but I think I'd lean against alerting on outdated values. My thinking here is that even old/deprecated values will be safe to have in db, and (as @lomky has pointed out) in the event of values Really Needing to Get Fixed we can reasonably expect a fund to hit us up and ask us to do this via db query directly. Put another way, we're generally okay with slightly messy data or field deprecation, since we're storing everything as strings. (Also, as you note, there's not a straightforward UX way to do it.)

I'm curious as to whether I'm missing something though - do you think there's a risk here that I'm not recognizing?

**Comment by elimbaum** [comment]
ok, that sounds good. I guess my edge-case alarms were going off with something like a misspelling – where you might have an option that gets used a bunch, someone realizes there's a mistake, updates it. But if we're fine with not totally consistent fields I'll just go ahead and add it without alert.

**Comment by colinxfleming** [comment]
Yeah, we are extremely fine with not consistent fields, so no alert sounds good. Thanks much for talking this out with me!
