### ISSUE TITLE
Add Github Action or CircleCI automation to build a dev env for every PR

### ISSUE THREAD

**Issue by xmunoz** [DCAFEngineering/dcaf_case_management#2091]
The following steps are required to bring up a local dev environment.

```
docker-compose build
docker-compose run --rm web rake db:seed
docker-compose up
```

Add automation (either in Github Actions or CircleCI) to preform this test on every PR, to ensure that bringing up a dev environment remains possible on every change.

Inspiration: #2075

**Comment by colinxfleming** [comment]
love this idea
