### ISSUE TITLE
Create user test sometimes fails

### ISSUE THREAD

**Issue by elimbaum** [DCAFEngineering/dcaf_case_management#2099]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Pass system tests! `test/system/create_user_test.rb:26` fails on CircleCI, sometimes. For example, see [here](https://app.circleci.com/pipelines/github/DCAFEngineering/dcaf_case_management/405/workflows/a1e160b0-07c4-4105-afff-064b50f82939/jobs/6516). The exact same thing has happened to me multiple times, when I haven't made changes to code even remotely related to the failing test case.

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**
Here is the failing test:

```ruby
    it 'should be able to create user' do
      assert has_field? 'Email'
      fill_in 'Email', with: 'test@example.com'
      fill_in 'Name', with: 'Test User'
      click_button 'Add'
      wait_for_element 'User Account Management'
      assert has_content? 'Active', count: 2  # FAIL on this line
    end
```

* **Anything else?**

**Comment by elimbaum** [comment]
I wonder if the system test is trying to create a duplicate user. Unclear why that would only happen _sometimes_, however.

![Screen Shot 2020-12-18 at 14 00 53](https://user-images.githubusercontent.com/7085805/102650804-75c94c80-4139-11eb-8e27-ee9de718aa79.png)

**Comment by colinxfleming** [comment]
thanks a ton for spinning this up @elimbaum !

Can confirm that this test seems to be failing spuriously pretty often lately, which is annoying, so definitely worth fixing up.

**Comment by elimbaum** [comment]
Do we have any insight as to why this is inconsistent? Or what could influence it? Is it possible CircleCI isn't building a fresh database? Do we have any tests that intentionally operate in a random manner which could be influencing this one down the line?

**Comment by colinxfleming** [comment]
yeah -- system tests use selenium, which fires up a web browser and dummy rails server, issues commands to the browser, and sometimes runs the minitest asserts before the commands have completely resolved. Most likely the reason this is happening is because of this.

What's unusual about this is that we see this kinda thing more commonly with things involving lots of ajax, and not so much synchronous stuff like this. Life's full of surprises I guess?

**Comment by elimbaum** [comment]
@colinxfleming pointed out [this other system test][1] that uses `OptionalRetry`, so I'm trying that. 

[1]: https://github.com/DCAFEngineering/dcaf_case_management/blob/main/test/system/logging_calls_test.rb
