### ISSUE TITLE
Flaky VoicemailPreferenceInCallModalTest

### ISSUE THREAD

**Issue by xmunoz** [DCAFEngineering/dcaf_case_management#2117]
I opened PR #2116 and this test failed, even though my changes only touch documentation. This test is probably flaky and need to be fixed.

**Comment by xmunoz** [comment]
Proof: https://app.circleci.com/pipelines/github/DCAFEngineering/dcaf_case_management?branch=docs-cleanup

**Comment by elimbaum** [comment]
This looks like it's probably a similar thing as #2099. @colinxfleming same auto-retry fix?
