### ISSUE TITLE
Zipcode is a number but should be a string

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#2131]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

A DCAF CM pointed out that leading zeroes, such as in New England area codes, are getting cut off from zip codes. 

* **What feature or behavior is this required for?**

This is workable, but not totally accurate, and since we have some funds potentially on deck we should rep their area codes properly.

* **How could we solve this issue? (Not knowing is okay!)**

The current DB field is a number. I think I would suggest making this a string and writing a validator for it.

* **Anything else?**
nope!

**Comment by colinxfleming** [comment]
@elimbaum you interested in maybe taking a whack at this?

**Comment by elimbaum** [comment]
This is also probably a generally good idea, i.e. zip+4. I guess we're probably not worried about international addresses.
