### ISSUE TITLE
Add Configs to set Archive windows

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#2150]
* **What are we trying to do?**
Make the Archive timelines for Dropoff and Fulfilled patients a fund-controlled configuration

Mockup:
![archive config mockup](https://user-images.githubusercontent.com/6129479/110719278-935aff00-81da-11eb-9985-f2adf1d102c6.png)

* **What feature or behavior is this required for?**
Some funds have frustrations around our data anonymizing too early for their processes. We don't want to set everyone to a longer timeline, as that increased issues around folks who need our support again within that window due to the phone number being a unique ID. Instead, we want to allow funds to make that trade off decision themselves.

* **How could we solve this issue? (Not knowing is okay!)**
Add a new config field in the [Config model](https://github.com/DCAFEngineering/dcaf_case_management/blob/main/app/models/config.rb), set reasonable defaults and bounds on the input, and use that value instead of the literals in the [Patient model](https://github.com/DCAFEngineering/dcaf_case_management/blob/851bf72f0b67898bce06fceb32829d28ec1af346/app/models/patient.rb#L260-L271)

* **Anything else?**
See #1914 for the full discussion. CC @verbingthenoun

**Comment by elimbaum** [comment]
I might give this one a crack since I've been looking at Configs recently!

**Comment by elimbaum** [comment]
What should the default values and bounds be? Currently we are doing what's in the screenshot - 120 and 365 days. I'm not super familiar with this part of the process so would just be making up numbers for min/max.

**Comment by lomky** [comment]
I'd go with the values currently hardcoded as the default, that way folks who don't mind the current settings won't have any change

**Comment by elimbaum** [comment]
Sure. And no bounds?

Also, welcome input on language. I currently have this:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/7085805/117585105-9b51f500-b0de-11eb-80ab-5afb470bd72f.png">

which sounds a bit weird. But then again if we want them to be together on the config list (sorts alphabetically), it may need to be that wording.

**Comment by lomky** [comment]
Oh bounds. good point. I'd think the same for both, but I don't have a good idea what our acceptable latest archive should be.
Just a stab in the dark, minimum 2 months, maximum 1.5 years?
Any opinions, @colinxfleming?

For the wording, how about the titles :

> **Patient Data Archiving: Days to keep fulfilled patients**
> \<textbox>
> Number of days (from their initial entry date) to keep identifying information for a patient who's pledge has been fulfilled. Defaults to 90 days (3 months).

> **Patient Data Archiving: Days to keep all patients**
> \<textbox>
> Number of days (from their initial entry date) to keep identifying information for any patient, regardless of pledge fulfillment. Defaults to 365 days (1 year).

**Comment by elimbaum** [comment]
are you ok with "options" being added at the end... that text is automatically plugged into the header and save button. So it would be 

> Patient Data Archiving: Days to keep all patients options

and then

> Update options for Patient Data Archiving: Days to keep all patients

**Comment by colinxfleming** [comment]
honestly, @verbingthenoun you've thought more about this than anyone, probably -- what do you think the boundaries should be on each of these?

I do like 1.5 years as a high max if not audited. I subscribe to the philosophy of 'data is a liability' when it comes to PII.

**Comment by lomky** [comment]
Yeah totally chill to have it follow the existing `... options` and `Update ... options` flow

**Comment by verbingthenoun** [comment]
Agree with "data is a liability" but it's also really critical that we not set the low bound too low, especially for unfulfilled. I *think* two months is reasonable, although I'm actually not sure if we have cases that take 2+ months to resolve. maybe worth looping in someone on CM team?

**Comment by lomky** [comment]
Also, I wouldn't let this block you Eli! throw in a low bound and we can always hold on merging the final PR until we hammer out the right number
