### ISSUE TITLE
URI parsing (for fax service) is unstable

### ISSUE THREAD

**Issue by elimbaum** [DCAFEngineering/dcaf_case_management#2153]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Properly parse user-entered URLs, particularly ones that have slashes in them or are otherwise funky! Currently, we _only_ support URLs of the form `http://website.com`. Stumbled across this while working on PR #2151.

* **What feature or behavior is this required for?**
Fax service link in the footer.

* **How could we solve this issue? (Not knowing is okay!)**
Improved URL parsing! Currently, we are doing `@uri = URI.parse(URI.encode(uri))` which leads to all kinds of funky behavior!

* **Anything else?**
Here's the error:

> URI::InvalidComponentError in Configs#index
> Showing /usr/src/app/app/views/layouts/_footer.html.erb where line #15 raised:
> bad component(expected host component): a%20random%20string/testing
```ruby
  def fix_leading_slashes
    if @uri.scheme.nil? && @uri.host.nil? && @uri.path.present?
      @uri.host = @uri.path # this line!
      @uri.path = ""
    end
  end
```

Specifically, you can trigger this by entering a Fax service URL that has a slash in it, such as `https://yolofax.com/fax`. When the above code runs (while trying to render the footer), it will try to set the host (formerly `yolofax.com`) to the path (which is `/fax`), but hosts are not allowed to have slashes in them.

**Caution!!!** don't test this on the sandbox or any other environment where you can't easily rebuild the db! because the footer is rendered on _all_ pages, configuring an invalid url will make... all pages... crash. 😢 and you won't be able to fix it.

Another quirk of this bug is that you _can_ set the fax service url to something that would otherwise be invalid, such as `this is not a website`. Because of the call to `URI.encode`, Rails just renders the fax footer with an href to `https://this%20is%20%not%a%website` which is... not a website! my browser, at least, has no idea what to do with that.

**Comment by colinxfleming** [comment]
thank you for spinning this up and tagging it @elimbaum !

**Comment by elimbaum** [comment]
I've done some digging, and it looks like much of this code was added last year in #1843 and #1845. It looks like we added some edge-case handling but aren't handling everything. Kevin mentioned using [this gem, addressable](https://github.com/sporkmonger/addressable), which would be more robust and may make sense. However, I'm not even sure it solves the most basic edge case of adding schemes to scheme-less URLs (`www.google.com -> https://www.google.com`). But we can do that by hand.

However, I'm also wondering why we are only using `UriService` for the fax url. There are other URLs in the config (practical support, resources) which are not being validated whatsoever - they're just being passed straight out of the database into an href.

- Do we want URL validation, or should we just take whatever the user enters?
- Should we be validating the other two URL options?
- How fancy do we want our validation to be? We could do everything from just adding `https://` to properly handling [non-ascii domains](https://en.wikipedia.org/wiki/Internationalized_domain_name)...

**Comment by elimbaum** [comment]
I've settled on the following but welcome comments:

- Add `https://` if the URL doesn't already start with it (replace if `http://`)
- Validate that what we now have is a URL using the ruby parser.

This makes the following changes to these example URLs:
```
http://www.yolofax.com/path?query => https://www.yolofax.com/path?query
http://com/path?query => https://com/path?query
https://perfecturl.com/
yolofax.com/path => https://yolofax.com/path
www.yolofax.com => https://www.yolofax.com
/yolofax.com/path#frag
	INVALID
//noscheme.net/ => https://noscheme.net/
some random string => https://some random string
	INVALID
no+spaces => https://no+spaces
/relative_path
	INVALID
```

So this doesn't allow for relative paths. I'm not sure that would really be an issue unless a fund was hosting resources on their own server? But then they could just use absolute paths.
