### ISSUE TITLE
docker setup issue - webpack out of sync

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#2154]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Setup instructions, on docker-compose up, are returning an error because webpack is being weird and not compiled yet. Maybe there's a depends_on we need to do or something?

* **What feature or behavior is this required for?**

non-frustrating setup instructions

* **How could we solve this issue? (Not knowing is okay!)**

idk

* **Anything else?**

cc @patriciaDAscientist  who discovered this

**Comment by patriciaDAscientist** [comment]
ISO new issues
