### ISSUE TITLE
Instructions for creating a new user using Heroku cli don't work

### ISSUE THREAD

**Issue by xmunoz** [DCAFEngineering/dcaf_case_management#2175]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Create an admin user when provisioning a new fund.

* **How could we solve this issue? (Not knowing is okay!)**
There is documentation here: https://github.com/DCAFEngineering/dcaf_case_management/blob/8264dd3b411c769d4c2bbc25225207151de708c7/docs/administering/SETTING_UP_A_NEW_INSTANCE.md#smoke-test-to-confirm-everything-is-working-right

I tried that query, and it did not create a new user for me. This documentation needs to be updated.

**Comment by colinxfleming** [comment]
This scans -- 

```
irb(main):005:0> xx = User.create email: 'your@email.org', name: 'Your Name', role: :admin, password: 'cats12345', password_confirmation: 'cats12345'
irb(main):006:0> xx.errors
=> #<ActiveModel::Errors:0x00007ff5562395d0 @base=#<User _id: BSON::ObjectId('608210ade3a476ce1dc23f6c'), created_at: nil, disabled_by_fund: false, email: "your@email.org", line: nil, modifier_id: nil, name: "Your Name", role: "admin", updated_at: nil, version: nil>, @messages={:password=>["Password must include at least one lowercase letter, one uppercase letter, and one digit. Forbidden words include DCAF and password."]}, @details={:password=>[{:error=>"Password must include at least one lowercase letter, one uppercase letter, and one digit. Forbidden words include DCAF and password."}]}>
```

with a proper password (in my case, `Cats12345`) it does seem to blend.

**Comment by colinxfleming** [comment]
I'll bump this in such a way that we can just copy a snippet and not think about it.
