### ISSUE TITLE
Add city/state to the clinics dropdown in patient edit view

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#2188]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

If you go to a patient edit page, here's how the clinic dropdown renders:

![image](https://user-images.githubusercontent.com/3866868/117556529-f7ae0980-b037-11eb-93b6-d003f8a949af.png)

Those are just the names of the clinics, and they're a little tough to read on the fly - where is `Sample Clinic with NAF`? Since geography matters quite a bit, I think it would be really nice to add city/state to the dropdown. So, that screenshot should change to something like this:

```
Sample Clinic 1 - DC (Washington, DC)
Sample Clinic 2 - VA (Arlington, VA)
Sample Clinic with NAF (Washington, DC)
```
etc. 

* **What feature or behavior is this required for?**

A nice quality of life improvement for CMs.

* **How could we solve this issue? (Not knowing is okay!)**

Take a look at `clinic_options` in `patients_helper.rb`. You might have to muck with i18n a little bit, but changing around the clinic name a bit is probably the way to go.

* **Anything else?**
Note that `Sample Clinic 1 - DC` and `Sample Clinic 2 - VA` are the names of the clinic in the seedfile - we definitely are not doing this right now!

**Comment by nsiwnf** [comment]
Picking this up!
