### ISSUE TITLE
Add clinic filter system to accountants view

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#2214]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

I would like to add a clinic filter to the accounting workflow form, in addition to the existing patients filter.

* **What feature or behavior is this required for?**

When funds are cutting checks and reconciling, they're generally doing that by clinic; individual initials lookup is helpful but they're generally looking for like 10 patients who all went to a given clinic.

* **How could we solve this issue? (Not knowing is okay!)**

Here's what I think:

* add a dropdown to the search form that has the options 'All clinics' (default) or all individual clinics.
* If an individual clinic is selected, limit search results to just that clinic. (I don't _think_ this is super painful in either pg or mongo - hopefully just an additional `where` condition? if the field is set?) 

* **Anything else?**

Leaving the implementation purposefully a little vague for purposes of good exercise; please do ask me any questions if I've left anything out, as that is also part of the exercise!

The origin ticket here made reference to changing the sort. Let's not do that; a single-clinic filter will accomplish what they want more cleanly.

**Comment by elimbaum** [comment]
Makes sense!

- For patients who have _no clinic_ set, we will of course want them to show up when `All clinics` is selected. Should we _also_ have a `No clinic` option in the dropdown to filter for those patients?
- I assume we want to do both filters at the same time? So if you search for "Susan" and then pick a clinic, you'll get all the Susans @ that clinic, right? (vs. clearing the first search and just getting all patients at the selected clinic)

**Comment by elimbaum** [comment]
Note to self: looks like the "Displaying X patients" text doesn't update properly. Look into this.

**Comment by colinxfleming** [comment]
Patients that show up in this should have a clinic set by nature of them having a pledge, I think. If a patient is in this rack and doesn't have a clinic, that's a validation bug on our side!

Yes please to both filters at the same time!
