### ISSUE TITLE
Change information displayed on accountants workflow

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#2215]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
A fund has requested that we add some more information to the accountants workflow, to help ease their (currently very unpleasant through no fault of anyone's) accounting process. This is a ticket to adjust the UX a little and add a bit new information to the accounting patient roll.

* **What feature or behavior is this required for?**

In part, this is because a particular fund has a uniquely difficult situation around accounting - they aren't consistently getting remit lists, so they're having to draft them on their own.

* **How could we solve this issue? (Not knowing is okay!)**

I'd like to propose we do the following to accommodate:

* Make the display shell scrollable, to hold more information. (I believe there's a bootstrap class that does this. `scroll-overflow` maybe?)
* Ditch patient initials in favor of regular patient name.
* Add pledge amount and line.

* **Anything else?**

I would explicitly like @lomky 's thoughts here, since this is a slight change in our security posture - names would be exposed here in a spot it wasn't before, but still not bulk exportable (and click-thru-able). Not ideal, but this feels to me like a minor enough shift as to not really increase the risk level. I'd appreciate your gut check on this.

@elimbaum please also weigh in if you feel strongly; please don't start until @lomky 's had a chance to weigh in, in case we mix this up.

Screenshot of the current state of the world for ref:
![image](https://user-images.githubusercontent.com/3866868/120046107-70710780-bfdf-11eb-96bd-bdcf1143d8f9.png)

**Comment by elimbaum** [comment]
Just for my background knowledge - are there "accountant" privileges that are distinct from volunteers? i.e. are we actually exposing new information to (possibly) new groups of users, or are we just providing that same information (i.e. that would be on the call list) on a new page?

**Comment by colinxfleming** [comment]
yeah! The `data volunteer` permissions level gives you access to this, since (at DCAF) the data team led by @verbingthenoun leads this process. You can see that in the code at https://github.com/DCAFEngineering/dcaf_case_management/blob/main/app/controllers/accountants_controller.rb#L3

**Comment by elimbaum** [comment]
I think as part of this issue I will also update some of the plumbing for the table - we're currently hacking in search results by manually inserting rows into a table, rather than using (presumably) native kaminari pagination utilities. I stumbled across this because the number of search results doesn't update correctly.

**Comment by colinxfleming** [comment]
Definitely a good idea to poke at that and see what's up. That said, don't get too hung up on it I think -- the postgres work is wrapping up soon hopefully, and that'll probably change the stance / approach at least a little bit.

**Comment by elimbaum** [comment]
What's the difference between `fund payout` (existing) and `fund pledge` (new)?

**Comment by lomky** [comment]
This is definitely a slight increase in our risk, but given that it is a restricted role page I'm okay with this - we should be sure to communicate this change our to our funds so they can audit the access properly

**Comment by colinxfleming** [comment]
@lomky good call on communicating the change in available data, and a flag to give funds a chance to get ahead of this. Thank you very much!

@elimbaum fund payout is on the fulfillment model and represents how much money a fund actually contributed; fund pledge is how much a fund was planning on contributing. Usually they're the same, but occasionally funds will bump the pledge amount on the fly and not update it in DARIA, so we have them as separate fields so we can track where the final payout is different than what we figured it would be.
