### ISSUE TITLE
Accountant Search & Filter hides the pagination navigation links

### ISSUE THREAD

**Issue by lomky** [DCAFEngineering/dcaf_case_management#2261]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Searching and filtering on the Accountants page should retain the navigation links when there are paginated results.

* **What feature or behavior is this required for?**
Fully functional paginated accounting page

* **How could we solve this issue? (Not knowing is okay!)**
Not sure!

* **Anything else?**
Context!

> 
> When you use the accountants search, the Kaminari navigation links go away, because of line 6 below: https://github.com/DCAFEngineering https://github.com/DCAFEngineering/dcaf_case_management/blob/044bd8a5737a5dc1b5b4ec5d48d3198c0ab0348d/app/views/accountants/search.js.erb#L3-L10
> 
> This partially makes sense, because if you don't empty the `nav` links, they don't update with the search (i.e. clicking `Next` brings you to the second page of results for the unfiltered query). Since were in the neighborhood, I wanted to ask, but we can totally ignore this (or happy to make a new issue and look into it later).
> 
> <img width="340" alt="Screen Shot 2021-06-26 at 13 06 46" src="https://user-images.githubusercontent.com/7085805/123520588-621a1800-d67f-11eb-8fe3-b58112adfae8.png">

_Originally posted by @elimbaum in https://github.com/DCAFEngineering/dcaf_case_management/issues/2220#issuecomment-869031348_

> I believe this is existing behavior that was unexposed due to the search limit. I think this will require a deep dive into Kaminari -- my instinct is that we're not _quite_ using it as intended w.r.t. searching.

_Originally posted by @elimbaum in https://github.com/DCAFEngineering/dcaf_case_management/pull/2220#issuecomment-872562005_

> 
> Upon searching the next/last/>/>> buttons disappear, making it impossible to get to the second+ page.
> ![image](https://user-images.githubusercontent.com/6129479/124190522-6a63c000-da90-11eb-8a3a-1bc4e53e8fa3.png)
> ![image](https://user-images.githubusercontent.com/6129479/124190560-794a7280-da90-11eb-9106-888275257cbf.png)
> 

_Originally posted by @lomky in https://github.com/DCAFEngineering/dcaf_case_management/issues/2220#issuecomment-872557387_

**Comment by elimbaum** [comment]
I _feel_ like there must be a kaminari-endorsed way to do this - filtering and pagination go hand-in-hand. I haven't looked through the docs too much yet, however, so I can't say for sure.
