### ISSUE TITLE
Render inline errors in forms with rails-bootstrap-forms gem

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#274]
@ewiggins and I were working through a validation issue in #271  and in the process, it became clear that we aren't doing an excellent job of rendering form errors.

It's an open question of whether we should do this before MVP in July or not, but I do want to get it on the radar either way. 

@mebates @adinneen want to weigh in here? Should we roadmap this as part of mvp? 

Implementation-wise, the paths of least resistance are a flash notification up top or inline form errors. Will leave it to our UX friends to determine what's best here.

**Comment by mebates** [comment]
If we can build them in by July, that would be awesome. Could be a good think to work on in the next two weeks. I would recommend following the USWDS design, if that's easy enough: https://standards.usa.gov/form-controls/#text-inputs

**Comment by colinxfleming** [comment]
Does the uswds have a standard library or something like that, by chance?

The path of least resistance is probably just using whatever is standard in
the bootstrap forms library we are using, which is probably fairly similar.

Agree that having this in before launching would be fantastic. Let's make
sure we have it on the list.

**Comment by colinxfleming** [comment]
For MVP let's go with the functionality baked into the bootstrap forms gem we're using. Here's a link to this: https://github.com/bootstrap-ruby/rails-bootstrap-forms#alert-messages

Let's start by implementing for the main form in `app/views/pregnancies/edit` and `app/views/pregnancies/_new_pregnancies`. 

(A possible sticking point is that we have fairly minimal model validation at this time; feel free to whip up some fake stuff to make sure errors are rendering properly in testing.)

**Comment by colinxfleming** [comment]
Renaming and retagging to reflect the game plan.

**Comment by colinxfleming** [comment]
Dropping this from MVP

**Comment by colinxfleming** [comment]
Wonder if it would also be nice to have some marker of 'saved!' pop up when a field saves.

**Comment by colinxfleming** [comment]
This is currently our oldest not-fixed issue, and it's kind of a significant one. I would love to prioritize this. Here is a potential strategy that I think might work:

* create a file called something like `update_failed.js.erb`
* change the controller action in the case of error to return `update_failed.js.erb` instead of an internal server error
* if a patient saves cleanly, flash a success message `Patient data saved!` at the top of the form (rendering the `messages` partial should do the trick here)
* If a patient doesn't save cleanly, return `There was an issue saving the patient: #{patient.errors.to_sentence}. Please resolve and try again.` as a flash message (again, rendering the messages partial should work nicely)

@tingaloo if you've got any energy I'd love for you to take a stab or offer your thoughts. I'd also love any thoughts you have from general javascripty/UX-ness experience you have; definitely interested in whether or not there's a better way to do this.

**Comment by tingaloo** [comment]
There's a way to do this, https://stackoverflow.com/questions/23967390/rails-flash-notice-via-ajax/23967474.

It's similar to the whole dynamic loading before, knowing what to keep vanilla and what to change into UJS.

I got patient success working, but is the success message something you want to keep flashing every time a field gets changed?

Here's what I have so far, https://github.com/tingaloo/dcaf_case_management/tree/backend/274

**Comment by tingaloo** [comment]
also can you give me a case where saving a patient returns a failure?

**Comment by colinxfleming** [comment]
@tingaloo you can crank out a failure by taking two patients and trying to name them the same thing, or giving them the same phone number. That should spit out a 500 because of the model validation choke. 

Definitely would like the success message to keep flashing every time a field gets changed.

If we could chuck in some kinda spinner or something like that to indicate 'saving', I think that'd probably be a pretty nice enhancement, but can definitely punt on that until later if it's a pain.

**Comment by colinxfleming** [comment]
@tingaloo sorry, forgot to ask the other day -- anything I can unstick on this?

**Comment by tingaloo** [comment]
Got it working, pushed through some sticky jquery stuff. But #1163 is up and running.
