### ISSUE TITLE
Generate and download PDF of pledge

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#345]
@lwaldsc @NerdyGirl537 can you all post a screenshot of a pledge form with fake information in it, so we can incorporate that into the pledge modal?

**Comment by colinxfleming** [comment]
[Blank Pledge Form (v.16.3) (1).docx](https://github.com/colinxfleming/dcaf_case_management/files/372699/Blank.Pledge.Form.v.16.3.1.docx)

**Comment by colinxfleming** [comment]
Not necessary for MVP, backlogging.

**Comment by colinxfleming** [comment]
This would be a nice thing to come back from SF with for our case managers, who are currently hand filling these out. Would love it if we could generate that programmatically and fill it in with the relevant data from the patient.

I have no real awareness of what the available libraries look like, but prawn seems to require no additional dependencies other than ruby, so I'd favor going with that so our windows users can still contribute.

**Comment by FeminismIsAwesome** [comment]
@colinxfleming , I'd like to give this a spin. I'll follow up with you on slack?
