### ISSUE TITLE
Omnibus list of DB concerns: backup, size, sustainability

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#408]
Our mLab install is just the easy-peazy, straightforward one -- this might get dicey as we scale it up. When do we graduate from Free to Paid?

**Comment by colinxfleming** [comment]
(Sub-question: BACKUPS??? 😬 )

**Comment by colinxfleming** [comment]
a) Our current DB after what's basically 9-10m of data is ~40mb. So we have probably several years before we approach a single gb of data. Good job us.
b) That said we should upgrade our mlab because we're a serious production system now.
c) regular backups remain an open question.

Next step here is to clear the upgrade with DCAF brass and then take the upgrade step on heroku.

**Comment by colinxfleming** [comment]
At current rates, DCAF prod is going to start running up against limits probably end of next year mostly due to audit trails and sessions collections, which are currently taking up 76mb and 29mb respectively. (For context, patients is taking up 16mb.) Sessions we can occasionally just blast into oblivion, and hopefully the impact of audit trails will be lessened when patient archiving rolls out and we blow away audit trails on archive.

Note that we run out of sandbox space at .5gb and have to move to a paid plan per https://mlab.com/plans/ .

**Comment by colinxfleming** [comment]
Audit trails is increasing at a rate of about 10mb/month. We're going to need a recipe to deal with that soon-ish. We might consider nuking audit trails over, like, 4 months old as a matter of course just to keep this clean anyway.

mlab does system level backups daily but restoring is a 'when they get around to it' affair. I wonder if in an effort to keep prices down we should consider rolling our own scheduled backup system and dumping it into an s3 (that someone else paid for, ideally).

**Comment by colinxfleming** [comment]
I have an idea for this that's I think we can do on the so-cheap-it's-really-free, but it's going to require some buy in from @alisonnjones (and maybe BAF as well) and will require AWS S3 and possibly an EC2 box. But I really, really, really don't want to pay mlab 50 cents per run (which comes out to real money after awhile).

**Comment by colinxfleming** [comment]
Mulling this over some -- I think we can install a heroku buildpack that will install mongodump, and then we can set up a mongodump rake task to an s3 bucket. I think.

**Comment by colinxfleming** [comment]
So it turns out mlab's paid plans include free daily backups, so we don't need to do anything on that front for DCAF, just other funds. Built in snapshots managed by mlab that we can pull and restore from is preferable to rolling our own, but other funds will take awhile before they get to the point where they start to get close to space concerns.

**Comment by alisonnjones** [comment]
Well that's good news. When do you think we'll need to revisit again? Approaching our new FY budgeting process this June...

**Comment by colinxfleming** [comment]
Due to archiving rolling out (which saves us some space by removing data we don't need to keep) it'll be at least two years before we have to buy another DB upgrade, and probably several more; when we do have to get a db upgrade we can just pay for another gb and it'll be another $15/month or so.

**Comment by colinxfleming** [comment]
I am still not sure what I want to do about other funds backups. +$18/m is tripling the cost. I like the idea of archiving to s3 but I'm not sure I want to deal with the overhead of having our own AWS account (and getting DCAF administration to handle payments, etc). At the same time, we should do SOMETHING about this so that we're keeping something warm.

**Comment by alisonnjones** [comment]
Hm, I'm open to what you think is best. Budgeting for FY19 is around the
corner, so let me know what you recommend. I'd rather have a bit of a
cushion in the projections in case any of these costs shift.

**Comment by colinxfleming** [comment]
I think there's an unresolved deal here over what to do for other funds but idk what it is. Marking futuretech for now and we can revisit after the survey.

**Comment by colinxfleming** [comment]
I think we can be permanently out of the woods here if we do the three following things:
* add a cleanup task that deletes sessions in the db if they're over 72 hours old (See the `mongo_session_store` gem for a hint at how to query this collection - https://github.com/mongoid/mongo_session_store)
* delete audit trail history on patient archive
* delete orphaned audit trails (can be done with a ruby snippet)
* bump db instances in prod. 

The

**Comment by colinxfleming** [comment]
This is on its way to being done - these are all represented in ticketed or impending work. I'm opening up a ticket for the fourth and closing.
