### ISSUE TITLE
OWASP: Run through RailsGoat for Ruby on Rails vulnerabilities

### ISSUE THREAD

**Issue by charleshuang80** [DCAFEngineering/dcaf_case_management#433]
[OWASP description](https://www.owasp.org/index.php/OWASP_Rails_Goat_Project): 

> Railsgoat is a vulnerable version of the Ruby on Rails Framework and includes vulnerabilities from the OWASP Top 10, as well as some "extras" the initial project contributors felt worthwhile to share. This project is designed to educate both developers as well as security professionals.

Usage information on the [RailsGoat page](http://railsgoat.cktricky.com/getting_started.html): 

> The application is designed in a "choose your own adventure" style. Once the application is up and running, navigate to the tutorials homepage and it will walk you through it.
> Essentially, you can either go straight into attacking the application and identifying weaknesses or you can look at each tutorial to get an idea how each vulnerability is introduced, how to fix it, and how to attack it. For those who just want a hint, each tutorial comes with one!

Essentially, I think @colinxfleming and other interested devs (especially anyone else checking PRs) should run through the app to learn about Rails specific vulnerabilities and make sure we don't have them.

**Comment by charleshuang80** [comment]
[RailsGoat project github](https://github.com/OWASP/railsgoat)

**Comment by colinxfleming** [comment]
I think brakeman addresses this in practice, though it's definitely a nice sandbox to have on hand for understanding how the vulnerabilities can play out in practice. I'm going to mark closed. (miss u charles)
