### ISSUE TITLE
Change LMP to Weeks Along in patient edit view

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#453]
From #405 - 

> 2 – LMP dating:  Sometimes CMs update the LMP.  This happens when there is a significant change in the due date estimate.  It’s not clear how they would go about updating this since it is confusing to try to edit the “LMP at intake” after the fact.  Maybe instead of editing the “LMP at intake” there could be a way to edit the “current LMP”?

This is, in fact, confusing as hell. Is there a cleaner way to do this? 

@lwaldsc @NerdyGirl537 @mebates @eheintzelman

**Comment by mebates** [comment]
What if the label just said "LMP" ?

**Comment by NerdyGirl537** [comment]
That's what the spreadsheet has: just 'LMP'

**Comment by colinxfleming** [comment]
Let me think about whether or not there's a good way to have current LMP editable. Right now LMP as appears in the helper text is calculated from initial call and LMP as reported at initial call, and making that editable as is will result in some pretty weird stuff happening.

**Comment by lwaldsc** [comment]
I do agree though that we need to make LMP editable for reasons stated in #405.
Not sure how that affects our coding but it's something that we will need. For right now, the autocalculated values under it aren't as important as being able to edit that number IMO.

**Comment by lwaldsc** [comment]
Discussed with @NerdyGirl537 and @eheintzelman 

If possible, could we recalculate Current LMP value based on the date LMP value changed and the new LMP and then rewrite the Current LMP to the new value?

CM1 opens up PT file on 8-2-2016 to see "Currently: 9 weeks (as of 7-29-2016) " 
CM1 changes LMP from 9 weeks to 12 weeks for whatever reason. 
SHERO would recalculate and rewrite Current LMP value to show "Currently: 12 weeks (as of 8-2-2016)."
CM2 opens up the PT file on 8-15-16 and it would show "Currently: 14 weeks (as of 8-2-2016)."

Does not necessarily need to display the new "(as of...)" date on the dashboard but just to illustrate how it should calculate on the backend.

**Comment by lwaldsc** [comment]
ALSO discussed with @NerdyGirl537 and @eheintzelman 

The term LMP should be changed to something that reflects more accurately what we are measuring. 
While LMP was a great catchall for old DCAF CMs, we don't always calculate last menstrual period.
Could we change it to "Gestational Age" or "Weeks Along" to make it more appropriately catchall.

**Comment by colinxfleming** [comment]
Changing this to Weeks Along makes a lot of sense. I'll make sure that's taken care of as well. 

@lwaldsc thanks for that scenario, that's something I can code around without too much trouble. I'll tackle this on the plane on Friday.

**Comment by colinxfleming** [comment]
With regrets I'm going to move this out of deploy milestone. A little too gassed to take care of it -- I think we can handle before too long, but this is complex enough that I want to be in a more awake state for it.

**Comment by colinxfleming** [comment]
Since this is a little complex, and it's the last week of august I'm kind of inclined to tag this one 'wontfix' and just add a helper tooltip to note that LMP is relative to initial call date.

@lwaldsc @mebates @NerdyGirl537 what do you all think? Is this a clutch feature or is it something we can fudge by leaving as is?

**Comment by lwaldsc** [comment]
File me under "good enough as it is."

**Comment by NerdyGirl537** [comment]
Same here

**Comment by mebates** [comment]
fine with me - but is it an easy fix to just change the label to "weeks along" as suggested above?

**Comment by colinxfleming** [comment]
Definitely! Thanks for not letting that slip @mebates .

Renamed to reflect that, promoted to active and tagged appropriately.

The ending task here is to pop into the patient dashboard partial and change the label for 'LMP at intake' to 'Weeks along at intake'.

You may have to do a little bit of styling stuff (making `at intake` the label for the days dropdown, adding a css overflow property to just that label, or something like that) to make this render cleanly. Follow your heart.

**Comment by colinmcglynn** [comment]
I got this
