### ISSUE TITLE
How do we effectively transition from one week to the next?

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#454]
From #405 - 

> 3- One user wanted to understand how the transition would work from one week to the next, one CM to another.  Have we thought this through? 

@lwaldsc @NerdyGirl537 @mebates

**Comment by mebates** [comment]
This seems like a great user story that could/should be prioritized into our next Release. I'll add it to the wiki.

**Comment by colinxfleming** [comment]
bumping this -- what's the next step here?

**Comment by mebates** [comment]
Hey @colinxfleming - it's on our list for Release 2. Not something we can solve for before releasing to the DC line, I think.

**Comment by colinxfleming** [comment]
Got it, thanks @mebates . Keeping on backlog until at least September.

**Comment by mebates** [comment]
@lwaldsc and @NerdyGirl537 have assembled some sample transition emails into a google doc for us. If you are doing work on this issue, make sure to request access to the doc!

**Comment by NerdyGirl537** [comment]
@mebates  Thoughts on transition.  I like the idea of some sort of communication between CMs.  We're all virtual and the email gives me the feeling of being connected to the other CM, that all my patients have been put in good hands.  The transition also allows CMs to share things that aren't in the system, especially when one of the sister funds is out of funding and when they will be able to fund again.  It also allows the outgoing CM to share how the line is going -- more or fewer calls than usual, things affecting the line (like a blizzard), and things that I might still be working.  I think the rest comes down to how much programming we want to do.  Letting the CMs continue to do email is the least effort.  Other thoughts would be to generate an editable email template with current budget (if not on Sunday night/Monday morning) and number of urgent patients that allows the CM to add other comments; a transition screen where CMs could leave information in the system for the next CM (this would keep CMs from sharing PPI inappropriately); or some way I'm not currently thinking of.  Thoughts?

**Comment by mebates** [comment]
@NerdyGirl537 good thoughts. So the minimum action is to do nothing. 🎉 

Another thing we could do is have an easy list of all the calls you've made *on your shift, across many nights* so you can review them and decide what information you want to share. We could also make it easy to share that list with the next CM. We've heard from folks that they liked being able to scroll through the excel doc to see what's been going on the past few nights. 

Maximum functionality would be to include CM-to-CM note writing within the app. But that would be silly!

**Comment by colinxfleming** [comment]
Throwing this out, to piggyback on @mebates 's point above about CMs being on top of the last few days of calls -- we've heard in a few places that CMs are interested in some sort of activity feed. Maybe the initial block of wood we can start from is an activity feed of some sort with the last 3-5 days of calls, and meet this need by some combination of this + what we're already doing around last note?

**Comment by mebates** [comment]
Closing this, in lieu of activity feed issue #654
