### ISSUE TITLE
Patient Info in pledge and status isn't reflected until page refresh

### ISSUE THREAD

**Issue by MiroFurtado** [DCAFEngineering/dcaf_case_management#490]
Pretty self explanatory. In order for the patient info to be saved (for example if I want to show the state of the patient in the pledge popup box), I have to click on the dashboard and then back on the patient.

**Comment by colinxfleming** [comment]
So if I'm understanding correctly, the steps to recreate are: 

* I am looking at a pregnancy edit page
* I edit an attribute such as phone number
* I click on submit pledge; submit pledge has the wrong phone number
* I reload the page and click submit pledge again; submit pledge now has the right phone number

**Comment by colinxfleming** [comment]
Potential solution here is to have the submit pledge modal populate by js injection rather than on page load. I'll investigate tomorrow night.

**Comment by colinxfleming** [comment]
Thanks a ton for flagging this @MiroFurtado . Good call.

**Comment by colinxfleming** [comment]
This probably isn't a Monday thing. Sorry @lwaldsc .

**Comment by colinxfleming** [comment]
This is currently a major pain point so I'm going to slate it for the hackathon.

**Comment by phoenixeliot** [comment]
I'm taking a look at this one.

**Comment by colinxfleming** [comment]
I'm popping this into active. I think there's a useful feedback win here. 

The technical step is to probably update `app/views/patients/update.js.erb` to reload the patient's status on the pregnancy edit page with new information.

**Comment by colinxfleming** [comment]
#1015 resolves for the submit pledge flow (which, A++++++++++). Still need to include a couple other dynamic fields (some fields in patient information, fields in fulfillment partial, probably the changelog?).
