### ISSUE TITLE
Abortion Date Entry

### ISSUE THREAD

**Issue by NerdyGirl537** [DCAFEngineering/dcaf_case_management#510]
I'm struggling a bit with the location of the appointment date.  It's good that it's always at the top, but that area doesn't have any other information that a CM would edit, so I've missed entering appointment dates.  Is there a way to put it in the 'Abortion Information' section as well?

**Comment by colinxfleming** [comment]
I'm closing this because I think our CMs have figured out where this lives, at this point, and changing it would cause more problems than it solved. If there's objection from @NerdyGirl537 
 or @mebates please reopen.
