### ISSUE TITLE
Ask for CM full name when logging a sent pledge

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#55]
I think we have an open question about what Case Manager / User name data to have in this information, specifically whether to do `first name` and `last name` both, or just an all inclusive `name`.

**Background**: We set up models with both first and last in #38, and I rolled this back in #49 to allow user objects to save again. (Devise requires that you specifically whitelist non-devise attributes, which in #38 are `first_name`, `last_name`, `role`, and `line`. We also may need to change pages downwind, such as the sign up page.) 

Beyond just the code changes, though, we should figure out what to do about including CM full names.

My own perspective is that DCAF rarely uses full names on the internet or in its current spreadsheet except in cases of board of directors, and I'm (admittedly) gunshy about use of full name, so I'd prefer to use an abbreviated name or nickname.

However, @NerdyGirl537 pointed out that this is would be a barrier to autofilling full name on pledge forms, which is true and also a problem, since part of the goal of this app is to make the rote parts of CMing less time-intensive. 

**A few sample options of how to proceed**:
- Full name only
- Full name as a slightly buried field in a different place than name, so it's not IMMEDIATELY accessible but still accessible via the app (a little extra development, slightly safer).
- Split the baby and do something like 'type in your name to send the pledge', and require a full name there (would require some annoying extra development but safer)

I'm totally open to criticism that I'm being too gunshy on this and that we should roll with first name and last name and it's no big deal, but would like to get the discussion on record to inform a group decision, and have something to use as a signpost in case this pops up again. 

cc @lwaldsc @mebates @kevin-wei @drownedout @adinneen as immediate stakeholders / people who worked on #38 .

**Comment by lwaldsc** [comment]
Def into the third option if it's not too much extra work. We can have the CM enter their full name as kind of a signature when they send the pledge. I feel like using initials in the actual data is safer.

**Comment by colinxfleming** [comment]
I think we can declare the third option (coincidentally, the one we're the way to proceed here, let's just keep name / username and require full name on pledge sending. Changing the title to reflect that and backlogging.

**Comment by colinxfleming** [comment]
Resolved in #956 !
