### ISSUE TITLE
Create DCAF Style Guide wiki

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#621]
Other designers need to be able to jump in and design for the DCAF CM App. Our design style should be documented on a wiki page. (ex: issue #302)

**Comment by colinxfleming** [comment]
This is a fabulous idea! Is the first step here scoping out what we need to cover and then settling in and writing it?

**Comment by colinxfleming** [comment]
@mebates can I give you a nudge on this? Still worth doing?

**Comment by colinxfleming** [comment]
No movement on this in a year and a half means we're probably not going it -- marking closed unless someone from @DCAFEngineering/designers wants to pick it up.
