### ISSUE TITLE
Design administrative support screens for user management

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#626]
Right now I'm creating new accounts through the heroku console, which clearly is not tenable. We should turn account creation back on for people with administrative privileges.

**Comment by mebates** [comment]
This sounds like a 'support' function. Any other support-type things we should consider? Def needs more UX thinking.

**Comment by colinxfleming** [comment]
Google dump:
* http://wiki.summercode.com/rails_authentication_with_devise_and_cancan
* http://stackoverflow.com/questions/19017978/allowing-admins-to-add-users-with-devise
* http://stackoverflow.com/questions/23879648/devise-allow-only-admin-to-create-users

(There's a baked in devise form we can use for the immediate thing.)

I'm not sure about support type stuff, but I'm not super worried about it honestly. I think this kind of stuff will rise pretty organically.

**Comment by colinxfleming** [comment]
After a good night of sleep (imagine that, after a good night of sleep I look at problems differently, who'd have thought), I think there might be some basic admin support of users we can roll up -- some kind of admin panel that's just a paginated view of users, their last login timestamp, and a button to send them a password reset email might be very helpful. What do you think @mebates ?

**Comment by mebates** [comment]
Yes. A support screen or two. Needs work and thinking. Doing this at my job right now too.

**Comment by colinxfleming** [comment]
Sounds like in practice this is probably two tasks:

a) Backend wise, wiring up `devise` and `pundit` libraries so that authorized users (e.g. CMDs, program admins such as myself and Jenn) can create users 
b) UX wise, figuring out what authorized users need to be able to handle this administrative component of the system.

The former we can start on now, since it's basically just 'wire up the devise route and install pundit'. I'll spin that off into its own issue and we can use this one for admin support pages. @mebates I'm super interested in what we can crib from your day job for this.

**Comment by nimiro** [comment]
Hi, here are some draft wires for user account management based on what we discussed at the meetup last week: [DCAFwireframe101016_user_account_management.pdf](https://github.com/colinxfleming/dcaf_case_management/files/520274/DCAFwireframe101016_user_account_management.pdf)

The data columns definitely aren’t finalized, and I wasn’t sure how important it is for directors to be able to bulk reset passwords and/or lock accounts. So there are two different options for the table view - multi-select or inline buttons in each table row. But hopefully this is a useful start for getting feedback.

**Comment by colinxfleming** [comment]
@nimiro thank you so much for this, this absolutely slays. I'd like @mebates ' eyes on this and once we have thoughts from her, dev side will build a shell and work on the functionality. 

Really love how straightforward this is! Thank you so much.

**Comment by mebates** [comment]
@colinxfleming - what happens when you 'lock' an account? Do we want to keep a user and just restrict their access? Or should there be a way to delete a user? 

And, what data is needed when you add a new account? First, last, email?

**Comment by mebates** [comment]
@colinxfleming - does 'Create new account' trigger an email to someone to create a password? Or what?

**Comment by colinxfleming** [comment]
@mebates yeah, I want to go with the locking strategy over the deletion strategy so that we can keep their notes, call records, etc. We wouldn't be able to preserve that if we did hard deletes. 

Data required to create a new account is name (which we collect as a blob rather than separate first and last) and email. 

Correct that creating a new account triggers an alert email sent to that address to let them know that an account's been created.

**Comment by colinxfleming** [comment]
Mollie -- right now when you lock an account it's more or less functionally
the same as a complete access restriction, and it doesn't take away
anything they might have created to go along with it (e.g. their notes are
preserved). I'm in favor of locks instead of hard deletes for this reason.

**Comment by colinxfleming** [comment]
And yeah, people get auto emailed on account creation. Right now i think it
just sends a message to the effect of "you have an accoubt now and here is
the url". I'm working on getting it to a place where before logging in they
have to reset their password.

**Comment by mebates** [comment]
Cool! I think we had some next steps on the designs, right @nimiro?

**Comment by nimiro** [comment]
Yeah, here are the updated designs.
[DCAFwireframe110116_user_account_management.pdf](https://github.com/colinxfleming/dcaf_case_management/files/564853/DCAFwireframe110116_user_account_management.pdf)

There are still a couple questions:
- Should the case manager director be able to edit all fields for an existing user (full name, email, role) as currently depicted?
- The exact wording of the confirmation banner messages for password reset and account creation. It sounds like there'll be an email with a password reset link?

**Comment by colinxfleming** [comment]
My inclination is that we do want a CMD to be able to edit everything, but let me mull it over. I'm cognizant of the fact that privileges elevation in particular is a risk so I want to look at how other securityminded orgs do it before we reach a decision. If you need a decision at this point to be able to move forward, let's assume yes if that's cool with you. 

Confirm that there'll be an email with a password reset link, as well.

**Comment by colinxfleming** [comment]
PS these designs are wonderful @nimiro . Really appreciate how clear and concise the flow is! Thank you so much.

**Comment by mebates** [comment]
Reviewed with CMs tonight, looking great! @nimiro is going to make some small adjustments. It would also be awesome if we started using the 'alert' style from US Web Design Standards with this new feature, and any future alerts. https://standards.usa.gov/alerts/

**Comment by nimiro** [comment]
Updated wires - with style adjustments and the addition of a locked user account page with an unlock button - are here: [DCAFwireframe110316_user_account_management.pdf](https://github.com/colinxfleming/dcaf_case_management/files/571543/DCAFwireframe110316_user_account_management.pdf)

The existing user account page still needs some thought. Basically, an admin should be able to edit and save a field like email address without being sent back to the table view, because they may still want to hit the reset password button.

**Comment by colinxfleming** [comment]
The USA standards look great. Totally a doable thing to move those over. That's probably a good candidate to spin into a beginner friendly issue, I'll do that now. 

@nimiro anything I can help unstick on that front? @vtmeghan might have some insight on what the ideal there is too.

**Comment by colinxfleming** [comment]
Spun message styling out into #728

**Comment by nimiro** [comment]
@colinxfleming Thanks, I think I'm good on the alert visual design, using the US Web Design standards. And I have some thoughts on the flow issue (i.e. allowing an admin to easily save edits to user account fields before resetting the password) - just need to wire it up before thursday :)

**Comment by mebates** [comment]
@colinxfleming - this issue kind of stalled out, but the last wireframe PDF is in great shape. I think we could move this to active development.

**Comment by colinxfleming** [comment]
I'm into that. These designs are really fabulous. My inclination is to release it into the pond after we roll out to Baltimore in the near future.
