### ISSUE TITLE
Audit & Accounting for MVP

### ISSUE THREAD

**Issue by eheintzelman** [DCAFEngineering/dcaf_case_management#643]
Integration of some audit and accounting functions.

Notes from Interview with DCAF Accountant: https://github.com/colinxfleming/dcaf_case_management/wiki/Audit-&-Accounting-Notes

We need to decide how much to integrate for the MVP.  I see two big picture options:

1 - Maintain the current process where the accountant maintains a 'shadow spreadsheet' to reconcile pledges submitted by CMs with fulfilled pledges.  Another volunteer takes this information and goes into the CM system to mark cases as fulfilled. 

2 - Integrate fields from the accountant 'shadow spreadsheet' into the CM system.  This spreadsheet is currently the best resource for actual activity: actual procedure dates, actual weeks/days along on day of procedure, actual number of procedures funded, total $ funded.  We would need to add several additional fields to the system and a time-efficient way for the accountant to enter this data across all lines.  This is great programmatic data, right? 

Any initial thoughts?

**Comment by colinxfleming** [comment]
I think I favor option 2. Getting out of the spreadsheet business and getting some of DCAF's admin functions out of the 'shadow' level is a pretty important goal, and I think the last two big things are this and clinic info.

Maybe we can strap a Reconciliation object onto our data model, and have that include Date of Procedure, LMP on Day of Procedure, and any other stuff that the accounting side needs specifically. This gives us a place to expand outwards and kind of store all accounting-related stuff that we need to. 

+1 on a time efficient way to enter data across lines! And you're right on that this is really great programmatic data. 

@mebates , yr thoughts?

**Comment by eheintzelman** [comment]
Ok, so moving in the direction of getting out of the spreadsheet business, I put together a proposed process flow for integration of accounting functions with DCAF CM.  I'm working on getting feedback on this from the accountant and would like feedback from @NerdyGirl537 and @lwaldsc 

[DCAF Accountant Process Flow - Proposed - 10-3-16.pdf](https://github.com/colinxfleming/dcaf_case_management/files/506311/DCAF.Accountant.Process.Flow.-.Proposed.-.10-3-16.pdf)

**Comment by NerdyGirl537** [comment]
The flow looks good.  I think a lot will depend on the kind of reports the system will generate.  Coming from working in financial systems, tracking the check numbers can be helpful with regards to audits and redundancy can be highly desirable for that as well.  

What about creating a tab specific to Accounting (like patient info or abortion info) where Emily can input all that information?

**Comment by lwaldsc** [comment]
Everything looks great to me. Not a whole lot to add as this isn't really my wheelhouse but I agree with Jenn on adding an Accounting/Audit tab.

**Comment by mebates** [comment]
Ahh, I started a comment on this at work and didn't click send. I'm sorry!

I agree that we should add the audit/accounting left nav item. Let's start with adding a checkbox for 'fulfilled' and build on it from there! I don't see the purpose in adding any of the quickbooks functionality yet.

**Comment by eheintzelman** [comment]
Yes, sounds good to add the audit/accounting left nav item and starting with the fulfilled checkbox.

Before the accountant even gets to financial items, she tracks data on actual procedure date, weeks on the date of procedure, and pledge amount (she calls it 'Abortion Care'), based on the returned IOUs from the clinics. Here are sketches of search and data entry for the accountant. It's programmatic data that I than envision would show up in the patient summary. Let me know your thoughts!

![accountant input sketch](https://cloud.githubusercontent.com/assets/17989540/19152106/62f7311c-8b9e-11e6-8086-9abaedcac839.JPG)

**Comment by colinxfleming** [comment]
I love how this looks and how straightforward it is -- @eheintzelman this is really lovely to my eyes. Very interested in your thoughts @mebates !

Once we have an approx design squared away, I'd love to be able to get it in front of the accountant with an invision thing or something, to confirm that we aren't missing anything too significant.

**Comment by colinxfleming** [comment]
Pending a design review I think there are a few things we're definitely going to need:

a) Accounting specific view and controller
b) Modal with some accounting stuff in it
c) Changes to the patient edit view

the first two we can iterate on no problem. I'll spin those into separate issues.

**Comment by eheintzelman** [comment]
@colinxfleming Based on feedback from the team and the accountant workflow, here are suggested changes to the list of needs:

a) Accounting specific view and controller - within this, I can think of 2 accountant use cases

- Search for individual patient by unique Patient ID 
- Search for fulfilled cases that need to be viewed as a list and printed out for entry into Quickbooks (I'm imagining some kind of advanced search or filterable table view)

b) Left nav item for accounting stuff (moving away from modal idea) in patient view.  Use case is for accountant to be able to mark cases fulfilled and enter all accounting data. 

c) Changes to patient edit view - Yes! need to think through what changes and what data gets locked, once cases are marked fulfilled. 

d) Automated process that marks cases unfulfilled. This is for cases where the pledge was sent but DCAF did not receive a returned IOU.

**Comment by colinxfleming** [comment]
@eheintzelman into it. My instinct on a lot of this stuff is to follow the principle of least privilege and restrict it entirely to people with accounting privileges. So for CMs the edit view would be the same but an accounting nav item wouldn't show up. Is that cool? 

Automated process might be a little trickier but I'm sure we can carve it out. We'll have to discuss with the accountant what the exact params of this will need to be, but I'm pretty sure we can get there.

**Comment by eheintzelman** [comment]
@colinxfleming Could the accouting nav be viewable but not editable for CMs? Re the automated process,  I talked to the accountant about this and she suggested 30 days past LMP + 120 days = 150 days past LMP.  Clinics have 60 days to get the returned IOUs to DCAF and then DCAF has 60 days to pay out. I'll check with her again next time I get the chance.

**Comment by eheintzelman** [comment]
I've wireframed the proposed accountant left nav and put together two options for user flows to mark cases fulfilled.  Filling in the check data comes later in the accountant workflow.  

Option 1: Simple checkbox triggers a change in status to fulfilled.

Option 2: Call to action button below left nav triggers change in status to fulfilled.  A modal (ok I keep coming back to this!) guides the accountant to enter the information on the returned pledge form.  Once this info is entered, it gets locked from editing. 

One benefit of option 2 is that it ensures the data gets entered when it is supposed to in the accountant workflow. Interested in feedback and other ideas!  @mebates @nimiro

Big question for @NerdyGirl537 @lwaldsc 
What gets locked from editing once a procedure is fulfilled? 
- All data in CM patient edit view?  Or are there some fields that could get filled in later even after a pledge is fulfilled?  Patient demographic info? 
- What about the ability to use add notes to a file? 

[Option 1: Marking pledge fulfilled.pdf](https://github.com/colinxfleming/dcaf_case_management/files/545919/Option.1.Marking.pledge.fulfilled.pdf)
[Option 2: Marking pledge fulfilled.pdf](https://github.com/colinxfleming/dcaf_case_management/files/545920/Option.2.Marking.pledge.fulfilled.pdf)

**Comment by colinxfleming** [comment]
Dev @DarthHater did some A++ work stringing up the accountant dashboard and a search. Looks like the next step here is to bolt pledge fulfillment stuff into its own object, and wire up the stuff in the views. 

I think I favor the first workflow for mvp. Interested in others' thoughts. There are some common elements between both that I think we can get started on either way though.

re: the lockable stuff, I'd say that when we mark a pledge fulfilled, it's no longer editable except by admins. 

I think the remaining items here are (and they can be largely independent of each other): 
- [ ] Add fulfillment object and stitch it in to controllers etc
- [ ] View change / adding the partial and forms
- [ ] Integration test for marking a patient fulfilled

**Comment by eheintzelman** [comment]
Are we taking into account two separate steps in the accountant workflow within DCAF? It's important because the accountant needs the ability conduct searches separately for procedures that have been fulfilled (but not paid) vs. procedures that have been fulfilled (and paid).

Step 1: Accountant marks pledges fulfilled and enters data for procedure date, weeks along, and abortion care $.  Status here is 'Fulfilled'

Step 2: Accountant enters check info (Check # and Date of Check).  This is indication that DCAF has paid out for the procedure.  Status here is 'Fulfilled and paid'

**Comment by colinxfleming** [comment]
I think that squares into our data model fairly cleanly, as it exists -
just involves changing around how we define status. Are there design side
changes we should anticipate to reflect this need?

**Comment by eheintzelman** [comment]
No design side changes that I can think up.

**Comment by eheintzelman** [comment]
Next up to meet Accountant MVP needs are data tables!  See accountant workflow for more context: https://github.com/colinxfleming/dcaf_case_management/blob/475bb8b8ad6dd8b1b8edba542c2dd47a34be31e5/_design/Accountant%20Flow%20-%2011-16-16.pdf

User stories: 

1 - Accountant needs the ability to generate a list of unpaid, fulfilled procedures that can be printed or exported to a .csv or excel file.  Accountant uses this to input data into QuickBooks and generate checks to clinics.

* Search parameters:  Status = Fulfilled.  Check fields (Check # and Date check sent in fulfillment tab) are blank.  
* Data fields for display: Clinic name, Patient initials, Abortion Care $, Weeks at procedure, Date pledge sent.

2 - Accountant needs the ability to generate same list of unpaid, fulfilled procedures and to efficiently enter data for Check $ and Date Check Sent.  Admin users of DARIA will be able to see what procedures have, not only been fulfilled, but also paid. 

* Search parameters: Same as above.
* Data fields for display: Clinic name, Patient Initials, Abortion Care $, Date Pledge Sent, Check #, Date Check Sent. 
* Inline editing functionality for Check # and Date Check Sent fields.  Entered data should flow into corresponding fields in Fulfillment tab. 

Question: How much flexibility should we incorporate at this early stage?  Do we focus just on accountant needs, or broaden this to consider needs of program staff? If the latter, how much more discovery is needed to understand needs?  I don't want to overcomplicate things for this basic functionality...but also want to avoid redoing stuff later if a more customizable solution is really what's called for. 

Option #1:  Hard code these 2 reports (search parameters + view).  

Option #2: Make a much more customizable data table, where user can choose filters, create and save different views and/or searches.  Could also incorporate sorting functionality.

Option #3: Some kind of interim option that allows for some filtering/searching flexibility but hard codes a couple of different views and/or searchers.  

Here are two mockups that show just basic functionality for the accountant (Option #1).
![quickbooks billing info - annotated](https://cloud.githubusercontent.com/assets/17989540/21198091/fdc4cb2a-c20b-11e6-999e-2b178e010219.png)
![check data entry annotated](https://cloud.githubusercontent.com/assets/17989540/21198090/fdc4c008-c20b-11e6-9d5c-34d922eca875.png)

**Comment by colinxfleming** [comment]
Love this. 

To speak to the questions about further discovery, I think right now we set this up according to the first option and iterate from there. 

A concern: Right now one of the things we've tried our absolute hardest to avoid is a way to bulk export data out of this sys. I would like to pursue other solutions -- a custom view that's easy to copy/paste from, API calls to Quickbooks, building a team of volunteers to shout across the room -- before we fall back to a csv export. I'll look into whether we can ship people over to our quickbooks online acct.

**Comment by colinxfleming** [comment]
sorry, hit go before I completed the second thought. 

To speak to the questions about further discovery, I think right now we set this up according to the first option and iterate from there. I think there's merit in reviewing and taking stock of how program staff other than DCAF's accountant will put this to work, but I think that option 1 gets us something usable soonest, and I kinda think of fulfillments as the last major component before we have something that 100% replaces the functionality of the spreadsheet.

**Comment by mebates** [comment]
If we are not allowing an export, we would _just_ need the second view, with the data entry, right? I think the inline editing of check number and date should work. Once it's entered though, does it disappear from the list? Or disappear upon reload? 
Looks great @eheintzelman !

**Comment by eheintzelman** [comment]
Re exporting data:  sounds good to explore other options.  For now, as long as she can view the data in a list format and either copy/paste or print out the view, it will meet her needs. 

@mebates I think that's right.  We only need one view, as long as there is room for all the data fields.  I'll combine the two.  Good question about data disappearing - bad feedback if it disappears! My thought is that the data stays even upon reload, and that I change the search parameter for this view to just status = fulfilled (so doesn't matter whether those check data fields are filled in).  

@colinxfleming How hard would it to be have sorting functionality?  That way, accountant could use sort to move procedures to the top of the list that don't have check data entered.

**Comment by colinxfleming** [comment]
Just to log the contents of my and @eheintzelman 's conv tonight: Sorting is probably NBD, there's almost definitely a js library we can use of some sort. We can throw a javascript friendly person at it as a nice to have.

**Comment by eheintzelman** [comment]
Good feedback.  I've combined the reports into one, revised the search parameters, and added proposed sorting functionality.  I'll be running these wireframes by the accountant in early January for feedback. 
![accountant dashboard - annotated](https://cloud.githubusercontent.com/assets/17989540/21289344/43d2e778-c469-11e6-9d7b-68e3d1b450f2.png)
![accountant billing report - annotated](https://cloud.githubusercontent.com/assets/17989540/21289345/43d3ba04-c469-11e6-92d8-ff22f8b44660.png)

**Comment by colinxfleming** [comment]
Spinning up an issue to implement the core of these designs, the Accountant Billing section.

I think we can save the sorting functionality for a bit later. CMs have also asked for that on the call list, I think we can solve this in a few different places but want to get the core of this in place first. Let's skip pagination too, as that's almost definitely going to turn into a pain.

On thinking about how the billing report is populated, I wonder if we should be populating this with people who have pledges sent. Let's do Fulfillments for now and see where it takes us though.

**Comment by colinxfleming** [comment]
Closed via #1292 . aw yis
