### ISSUE TITLE
Feature req: Activity feed

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#654]
A CM said it would be nice to have some representation of what she did over the course of the evening -- her point of reference was a facebook activity feed. This seems to stem from a concern that the call list being cleared would run the risk of people falling through the cracks. For all the things we hate about the spreadsheet it does make history accessible. 

Should keep in mind as an eventually thing.

Stems from #614

**Comment by mebates** [comment]
Love this idea! @lwaldsc what do you think? What data would be relevant in the feed? Should it clear out every 24 hours or once a week?

**Comment by lwaldsc** [comment]
Thoughts we have to run through:

- Where does this live? On the dash? Under another link at the top?
- If a separate page, is this connected to an individual CM data center (#632) ? (This may be a pipe dream at this case, but I think would be nice for CMs.) 
- Is this just one CM or across CMs on a single line?
- How often to clear: after 24 hours, 72 hours, or a week? My gut is to clear more often then less often but there is something valuable in keeping activity data more than one day for CM shift handoff. 
[Un/related: We have an issue now with CMs putting a lot of unnecessary patient data in handoff emails, so anything that cuts down on that is great.]
- Phone Number, LMP, Last Call Date, Last Call Time, Last Call Result, Last Case Manager to record a call, Last Note in a popdown, + to add to call list

**Comment by lwaldsc** [comment]
Thoughts @NerdyGirl537 and @vtmeghan ?

**Comment by NerdyGirl537** [comment]
I think 48 hours could be a good time frame which would make change over a little more seamless.  It should be line specific but not specific to the CM or it won't be helpful in handoff.

**Comment by lwaldsc** [comment]
Colin and I chatted this out tonight and feel it would be best as just an action log housed in scrolling box at the bottom of the dashboard. Would be a text list of recent calls and pledges within a 48-72 hour period over a given line, sorted by date. Thoughts?

##[Date]
*Lisa W. called C.F. (D0-6660) at 10:03 pm. **(+)**
*Lisa W. left a voicemail for K.T. (D1-2345) at 9:45 pm. **(+)**
*Lisa W. pledged J.H. (D9-8765) at 9:15 pm. **(+)** 
*Lisa W. called J.R. (D2-4680) at 8:58 pm. **(+)**
*Lisa W. left a voicemail for C.F. (D0-6660) at 8:50 pm. **(+)**
*[CM] [action "called"/"called but did not reach"/'left a voicemail for"/"pledged"] [PT initials] [DCAF id] at [time]. **[Add to call list button]**

##[Date]
*[CM] [action "called"/"called but did not reach"/'left a voicemail for"/"pledged"] [PT initials] [DCAF id] at [time]. **[Add to call list button]**
*[CM] [action "called"/"called but did not reach"/'left a voicemail for"/"pledged"] [PT initials] [DCAF id] at [time]. **[Add to call list button]**
*[CM] [action "called"/"called but did not reach"/'left a voicemail for"/"pledged"] [PT initials] [DCAF id] at [time]. **[Add to call list button]**

**Comment by mebates** [comment]
Love it. Just to add some easy specs:

h1. [DC] Call Line Activity Log
h3. [Date]
bulleted body list
'Add' as an underlined blue link

Easy peasy!

**Comment by colinxfleming** [comment]
We haven't really explored event messaging that much, but I thnk we can do it fairly painlessly from a backend perspective. Here's a proposed backend implementation of it:

* We track certain CM-relevant events (logging a call, sending a pledge)
* Those go into a mongo collection, `events`, backed by its own model with no relations
* In the event the appropriate controller action gets hit (patient create, call create, patient update with a pledge sent), an event gets logged in the mongo collection
* to keep the events table from spiraling, we clear out everything more than 72 hours old every night as part of the `nightly_cleanup` rake task

Frontend wise, we stick this in a partial at the bottom of the dashboard, and give it a scrollbar so it doesn't take up a ton of space.

**Comment by tedPen** [comment]
I started laying down some groundwork for this. There's still a lot more to be done: [PR 1136](https://github.com/DCAFEngineering/dcaf_case_management/pull/1136)

**Comment by lwaldsc** [comment]
Tagging @vtmeghan @alisonnjones @deesriv cuz we talked about it tonight
