### ISSUE TITLE
Async modal content loading

### ISSUE THREAD

**Issue by mchelen** [DCAFEngineering/dcaf_case_management#662]
spun off from #612

> GOLD MEDAL: Have it be an empty thing until it pops up, and then have it populate contents dynamically! This will fix a lot of CM complaints and make the system generally feel less janky.

**Comment by colinxfleming** [comment]
@tingaloo here's the async issue mentioned in the other PR -- @mchelen has been working on abstracting our modals generally in #663 -- @mchelen do you think your work there is nearing a place where @tingaloo can start up on this issue?

**Comment by colinxfleming** [comment]
I'm reasonably sure this is fixed in #1015 ! I'm marking closed. 💯
