### ISSUE TITLE
List a line's appointments in next few days on the main call list dashboard

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#679]
Stems from #593

**Comment by vtmeghan** [comment]
@lwaldsc and I discussed - we don't think they should automatically be marked as urgent, but if there was a way to flag them in another way that would be great. Either by a section on the homescreen for "Appointments tomorrow" or "Appointments within 36 hours" that auto-populates, or by allowing searches by appointment date, that would be useful. probably need to complete #671 before this is possible/useful. @colinxfleming @NerdyGirl537 @mebates

**Comment by mebates** [comment]
I would suggest leaving this in the backlog and focusing on our Release 2 priorities.

**Comment by colinxfleming** [comment]
Agree with @mebates that popping into the backlog is the way to go here, now that we have some client feedback and we know that this isn't an urgent fix. Let's revisit in 2017.

**Comment by lwaldsc** [comment]
Oh definitely. This doesn't need to be a priority, but wanted to give
feedback as we were going through questions.

**Comment by colinxfleming** [comment]
Swapping this to future features since it needs more context and some sense of how useful it would be.

**Comment by colinxfleming** [comment]
This is coming up on three years without any forward action, which makes me think there isn't a critical pain point around this. @alisonnjones @vtmeghan @deesriv @mlindberg61 can we close?

**Comment by deesriv** [comment]
This is one of the proposed interventions to prevent drop off, it doesn’t
impact CM operations but it will reduce burden for callers— @alisonnjones
and harum and I started having scattered convos about it but would love to
revisit about what’s possible and reasonable!

**Comment by colinxfleming** [comment]
My opinion is that if there is a specific and identified pain point for CMs that this would address then we should keep it on the backlog and prioritize it accordingly. If it's not, then we should close this out as something we won't do unless it comes up again organically, since that probably means it's going to hang out on the backlog forever.

**Comment by deesriv** [comment]
For sure! Closing for now makes sense, but I don’t want to completely lose
this thread, as it relates to some of the operational changes to CMing that
we’ve been thinking about over the last few months with our strategic
planning workgroups and such. Cool if we bring it back to y’all once we’ve
ironed out a more comprehensive plan to handling/preventing caller drop
off?

**Comment by colinxfleming** [comment]
yeah, if it comes back up organically as part of a broader thing then that's cool, but absent a broader thing we'll never get to it so there's no point considering it 'outstanding work to do'. thanks much @deesriv
