### ISSUE TITLE
Build out draft user admin panel

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#686]
One of the ongoing goals for this app is to make sure that we get it to a place where engineers need to maintain fewer non-code parts of it; to that end, @nimiro is doing some heroic work building out some beautiful designs. Check them out here: https://github.com/colinxfleming/dcaf_case_management/files/520274/DCAFwireframe101016_user_account_management.pdf

The steps here are as follows:
- Add a view and a route for `users/index`
- Code up the first page of that in hard HTML (no functionality needed yet)
- If possible, add a simple controller test to confirm that the route is accessible

Stems from #626

**Comment by itsWill** [comment]
I'll take a stab at this!

**Comment by mebates** [comment]
Which page of the mockup are we working from? Great work @nimiro !

**Comment by mebates** [comment]
@itsWill - can you touch base with @nimiro before you start, and keep an eye on our convo in #626? Thanks!

**Comment by itsWill** [comment]
@mebates I just picked the first page, I understand the frontend design is not ready yet so this mainly sets up the backend, we can then change the view according to the design you and @nimiro come up with once its decided.

**Comment by colinxfleming** [comment]
Demoting from active development so we can focus on required stuff for Dec 1 -- thanks a ton to @itsWill for getting this process started!

**Comment by colinxfleming** [comment]
Here are some super dope designs courtesy @nimiro --https://github.com/colinxfleming/dcaf_case_management/files/571543/DCAFwireframe110316_user_account_management.pdf

I'm ready to start moving on this, and I think it'd be a nice thing to get into place. Marking active.
