### ISSUE TITLE
Lock users out after 6 months

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#713]
In order to control the number of users and access to the system, can CM App automagically lock users out after six months of inactivity? CMDs could unlock their accounts if they become active again (see #626). 

CMs are supposed to work at least one shift per quarter.

**Comment by colinxfleming** [comment]
Doable, and a very good idea. We could probably write a task here as part of the nightly cleanup job that disables CM accts that have had too much time go since last login.

How should we prioritize this @mebates ?

**Comment by mebates** [comment]
Let's do it in about six months! Backlog. :)

**Comment by colinxfleming** [comment]
I'm interested in revisiting this! @vtmeghan what do you think?

**Comment by lwaldsc** [comment]
I am not @vtmeghan but I def support.

**Comment by vtmeghan** [comment]
yes, definitely support - as long as there's a simple way to reactivate accounts (since we do have folks take hiatuses, etc...), I'm in favor.

**Comment by colinxfleming** [comment]
We'll roll this out after #1098 , so we can toggle CM lock/unlock. 6m it is, part of the nightly rake task.
