### ISSUE TITLE
ACCOUNTING: New status for unfulfilled pledges

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#735]
We may need a new status for a pledge that was sent, but not fulfilled. It should timeout after a certain period of time after being sent. Accountant suggested ~150 days would be a safe number of days. 

@eheintzelman @vtmeghan @lwaldsc @NerdyGirl537

**Comment by colinxfleming** [comment]
This should be a pretty straightforward change to our status logic once we have the business logic clearly defined. Either way a great thing to represent. Good call!

**Comment by colinxfleming** [comment]
@KatSDC want to take a look at this and see what it might look like from a code perspective?

**Comment by colinxfleming** [comment]
Okay, here's a game plan for this. There are three changes I'd like here as part of this:

* Add a `pledge_sent_at` field in the patient model, which sets to the current time when someone marks a pledge sent. This is something I think we've needed for a minute but haven't finished off yet. A `pledge_sent_by` would be nice too as long as we're wrenching around. A rails `after_save` callback might be pretty useful here.
* Adjust `app/models/concerns/statusable` to put a `Pledge not fulfilled` status in there after 150 days of having a `pledge_sent_at` and a `pledge_sent`, but no fulfillment. This should go between the pledge_sent status and the resolved status in the `status` method.
* Further adjust `app/models/concerns/statusable` to put a 'Fulfilled' status in there, if `patient.fulfillment.fulfilled?`. This should go up top of the `status` method.

**Comment by colinmcglynn** [comment]
I'll grab this

**Comment by colinxfleming** [comment]
@colinmcglynn let me know if you run into any snags!
