### ISSUE TITLE
Omnibus thread for feedback from data entry weekend

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#766]
(A QUICK PROGRAMMING NOTE: We tend to roll up feedback into omnibus threads like this and then spin individual stuff off into their own issues, which get some additional written context. Please don't make PRs against this issue. Thanks!)

Here's a running list of actionable stuff from conversations, trainings, etc during data entry for the full rollout. @NerdyGirl537 you should log stuff you're hearing too.

* Data entry form is hugely helpful, possibly worth writing tests for and having on hand permanently as a just in case. (#771)
* The pledge button says 'Submit pledge'; a data entry vol got a little confused about this. Wonder if it's worth changing the language on this to something like `I'm ready to send a pledge`? (#922)
* A data entry vol got a flash error something like 'pregnancy is invalid', which is a dicey thing to say (if I said that to someone, they'd rightfully point out that I was being a huge jerk). Worth changing use of 'invalid' to 'missing required information' or 'cannot save' something along those lines? (resolved by the great patient-pregnancy merger) 
* Spent some time troubleshooting with someone who was beating on the sandbox. Should come up with some way to clearly flag sandbox in in the staging env. (#792)

**Comment by colinxfleming** [comment]
* Since we quietly started just calling pledges 'pledges' everywhere (instead of hard/soft), we should remove references to hard/soft around the app, including but not limited to: the DB field, pledge validation error messages.

**Comment by colinxfleming** [comment]
* We've got an n+1 query problem for the main dashboard due to the new call modals requiring a lot of DB hits. It's causing high load times for people with large call lists (doubt it's affecting people using it in routine ways though). May not be the simplest fix but might be a nice optimization.

**Comment by colinxfleming** [comment]
* A data entry vol punched a few people into the DC line by mistake because session wasn't set. We should force line to be set in session anywhere on the dashboard controller.

**Comment by colinxfleming** [comment]
* @vtmeghan ran into a snag where someone was not creatable because of phone, but not searchable due to line scoping. 
* For some reason the env var for `LINES` comes back as `63` and I have no idea why. The lines var is properly set and the lines we actually use are showing up, so idk man. 
* We should change `Line: (STATE)` to `Your Line:`. Had a point of confusion about this. Might also be good to have it say 'No line selected!' with a link to the page if not set.

**Comment by NerdyGirl537** [comment]
Brain dump in no particular order:
- We have patients crossing state lines (finding in both MD and VA or MD and DC or VA and DC; think students especially).  This will gum up the old system with "unique" patients and phone numbers on each line.   
- Patients with no phone numbers: crypto data loss or issue to address with CMs?  (can't create a patient w/o phone number in DARIA)
- Several patients who had been spoke with had no last name. 
- Phone numbers get reused by different patients.  Examples might be another fund's CM calling; or a social worker calling.   
- Can we add a patient whose name we can't make out?  There are several examples of this in the spreadsheets and our data entry vols had some challenges.
- Noted that we could have a patient entered twice because different case managers heard different things; ex. very similar first names/same last names and different phone numbers.
- Would change 'unemployed' to 'not employed'
- Would change 'Hispanic/Latino' to 'Hispanic/Latina'
- Need to be able to transfer callers to another line or delete from current line when they call the wrong line.  CMs cannot identify callers who should be on other lines until after speaking with them; most will have already created a new patient record.

**Comment by colinxfleming** [comment]
I'm settling in to resolve a few problem cases now, which I think might yield some good insights. Github in one window, excel in another, sheet in a third, like a boss.

**Comment by colinxfleming** [comment]
* LMP counter on the patient edit page below LMP at intake keeps going no matter what. Should stop that

**Comment by colinxfleming** [comment]
* Pledge sent partial is referring to external unimplemented clinic object and not actual clinic attribute we're using.

**Comment by colinxfleming** [comment]
@NerdyGirl537 I punched in a couple stragglers' worth and re-uploaded the resolved ones. Have three more to rack before I exhaust what was in there tonight. idk if it flagged anything but was good dogfooding.

**Comment by colinxfleming** [comment]
* The dashboard page has an n+1 query problem -- every user in the call list is getting hit individually, so for people doing data entry a dashboard visit means 100+ queries to the effect of `select * from patients where id = x limit 1`. For individual CMs during normal use it probably doesn't matter much, but we should do it if for no other reason than to get logentries alerts to hush.

**Comment by colinxfleming** [comment]
* Accidentally screwed something up and did a db rollback. The good news is that we can restore from backups without incident via doing a db:mongoid:purge and a mongoimport, and this proves it. We should start taking regular daily or bi-daily backups as part of a schedule. I don't think we need to do this as part of the mongo service we use, and probably storing them in s3 and keeping them for like 1 week or some other similar protected but low cost solution is fine.
* Germane to that point, if there's a way we can add a safety check to destroy operations we should. I ran a `delete_all` when I should have run a `clear` and it almost screwed up a full day's worth of work.
* The MD CM had a bit of trouble getting a field to save. We should see if we can minimize the time before the jquery `change` event fires, since I think that's the culprit.
* Separately, we should standardize dates -- I think we're doing dd/mm/yyyy in new patient and YYYY-MM-DD for appt date.

**Comment by colinxfleming** [comment]
* Wonder if it would also be nice to have some marker of 'saved!' pop up when a field saves.

**Comment by colinxfleming** [comment]
* Backend thing: We're now searching on line so we should index that too!

**Comment by colinxfleming** [comment]
* Got our first person who's used DCAF's services twice, several months apart (e.g. multiple pregnancies). I'm entering them as their own patient and saving using a validation skip from the backend, but this does mean that we'll need to find a way to figure out how to handle this better now that it's a reality.

**Comment by colinxfleming** [comment]
* probably around 4 used-DCAF-twice incidents so far.

**Comment by NerdyGirl537** [comment]
Another thing I've noted is that the spreadsheets had started to track which clinic had referred the patient not just that it was a clinic referral.  Am wondering if the DCAF Board is working on something specific with that.

**Comment by NerdyGirl537** [comment]
Need to look at the case of Angela Harris in both MD and VA.

**Comment by colinxfleming** [comment]
The clinic referral thing is something that trickled down from the CMDs that I hadn't gotten around to putting in github. I was under the impression that it was more 'we pointed that patient toward that given clinic' (which in turn gives DCAF leverage to negotiate cost reductions) but I don't think the business logic around it is terribly well documented, and it definitely isn't clear from the spreadsheet.

**Comment by NerdyGirl537** [comment]
From one of our outstanding data entry volunteers:

- Adding immigration/non-citizen option to the extenuating circumstances checkboxes
- Include a spot for notating what portion of the procedure insurance is covering in the "Abortion Information" section
- Include a spot for notating what portion of the procedure the clinic is covering as a discount in the "Abortion Information" section
- Create a pop-up of some sort when a search finds an entry on another line. Right now, when you search for a number that doesn't exist in the line you are working on, you are prompted to create a patient. However, you cannot save the patient if the primary number is saved in a PT file on another line. Figuring out this will also, I hope, ensure that records are only kept on the correct line and not created in incorrect places. Given that duplicate records on multiple lines cannot exist, there might also need to be new protocols for handling PTs who accidentally call multiple lines. In Crypto, each line could keep a record.
- Add a function where users can pull up a report of people who've called the line in the last week. If someone calls from a new number and you can't quite get their name, it would be useful to be able to look at a list of recent calls to try and match. This is especially important with people who have names with multiple spelling variations. Again, in Crypto, this information was easily available so the challenge is just making it so in DARIA without having to flag everyone who still needs follow-up as urgent so they pop-up.

**Comment by colinxfleming** [comment]
Plenty to spin out into microissues. I think we can call this good to go and start spinning things out. Good mix of copyedits, small features, and UX stories we should talk about.

**Comment by colinxfleming** [comment]
Everything actionable here now spun out into its own deal; closing.
