### ISSUE TITLE
Frontend improvements for call line selections

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#779]
Per request of @mebates in #745 -- probably some stuff we can strip out in here.

**Comment by eheintzelman** [comment]
- Change 'Select line for this session' to 'Start'
- Increase size of radio buttons
- Align radio buttons and text descriptions
- Add padding between radio button and text description

@mebates other suggestions?

**Comment by mebates** [comment]
Yes to all of the above! Would recommend using standard radio buttons from U.S. Web Design Standards. https://standards.usa.gov/form-controls/#radio-buttons

**Comment by mebates** [comment]
UX is done on this! Ready for some front end attention.

**Comment by colinxfleming** [comment]
promoting to active! Edits can be made in `views/lines/new`. 

If you want to dig in on some css, feel free to make the radio buttons a global style.

**Comment by colinxfleming** [comment]
ps please take advantage of bootstrap styling classes wherever possible!

**Comment by StraubJones** [comment]
Grabbing this!

**Comment by colinxfleming** [comment]
Hey @StraubJones , let me know here or in slack if we can be helpful on this!

**Comment by StraubJones** [comment]
Oh I was going to just pick it up again at the next Hack Night but if it's more urgent than that someone else can grab it :)

**Comment by lomky** [comment]
Diving in on this tonight!

**Comment by lomky** [comment]
- [x] Change 'Select line for this session' to 'Start'
 - [ ] Increase size of radio buttons
    -  U.S. Web Design Standards. https://standards.usa.gov/form-controls/#radio-buttons
 - [ ] Align radio buttons and text descriptions
 - [ ] Add padding between radio button and text description

**Comment by colinxfleming** [comment]
@lomky can you pop up your branch from this, if it's not too much trouble / you still have it laying around?

**Comment by lomky** [comment]
@colinxfleming done, not much to look at atm.
