### ISSUE TITLE
Phase out passwords in favor of google SSO

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#811]
I'd like to move us entirely toward single sign on, so we can hop on google's security entirely and reduce the terror factor. Here are the hurdles we need to overcome to get to SSO-only:

* How do we get everyone google SSO keys to developers who need them without exposing them?
* How can we account for training needs, when a whole slew of people will show up and need accounts in a sandbox environment?

**Comment by colinxfleming** [comment]
possible solution: can we allow a regular sign-in just in sandbox and take it away in full prod? Something to consider.

**Comment by colinxfleming** [comment]
I don't think there's a world where we get out of having to have some sort of password entry, but I do think there's a way we can offer a carrot. I think we just make the Sign In With Google link bigger, add `recommended` so it looks like 'Sign in with Google (recommended)', and call this good.

**Comment by colinxfleming** [comment]
This is on the sign in form in `app/views/devise/sessions/new.html.erb`

**Comment by rudietuesdays** [comment]
on it!
