### ISSUE TITLE
Report on the PTs to whom we've soft pledged but never hard pledged

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#817]
As discussed in the DCAF internal meeting on 1-25-17, we'd like CMs to be able to pull a report of patients we have soft pledged (gave an initial amount we could help them with) but never hard pledged (confirmed a sent pledge). 

Starting this issue thread for discovery and discussion on how we build this baby.

cc: @NerdyGirl537 @colinxfleming @mebates

**Comment by mebates** [comment]
It could be an up-to-the-minute report, if you want. Just a page with a live feed of PTs in that situation.

**Comment by colinxfleming** [comment]
The sense I get from DCAF brass is that they want two things out of this:
* a sense of how much money they might suddenly be on the hook for, if a bunch of people cash in on their pledges; the design piece here is probably how to 
* the rolling list that @mebates describes intended for CM followup, which I think we can use our normal call-list-style `table_content` for; the design piece there is probably just finding the best place to put that

The first step here is to build some kind of way to easily identify them, though! Can we start with something like the following added to the `Patient` object?

```ruby
def self.pledged_patients
  # get all patients who have a dcaf pledge amount but no pledge sent
  # break them into different weeks, going 3 weeks in either direction from the current date. remember that DCAF weeks start on Monday and end Sunday. sorry
  # return a hash that looks like the following, so that we can further process it
 { week_20160220: [ Patient1, Patient2, Patient3 ], week_20160227: [ Patient6, Patient8, Patient10 ], ... }
end
```

I suspect we're going to start have to build out a decent amount of reporting methods, so if there's some way we can put this in a module and `include` it in the patient model, that'd be awesome. See [rails' concerns](https://gist.github.com/dhh/1014971) for this, even though it and I have a real history.

**Comment by mebates** [comment]
Alison notes that this page might be super helpful for the new Case Management Follow Up / Audit Team. Serena is going to take a crack at this! 

cc: @lwaldsc @NerdyGirl537

**Comment by lwaldsc** [comment]
Updating this issue so we can get it somewhere in the To Do hopper. 

So in addition to soft pledged patients, this should also be able to patients who we have not pledged yet but fall under:

- We have made at least one call to in the last 14 days (regardless of the outcome of the call).
- There has been no change to the patient's file since that last contact.

This report would not be exportable, but would look similar to the call list. Maybe even automatically populate into the call list? Idk.

**Comment by lwaldsc** [comment]
Tagging in @alisonnjones @deesriv @vtmeghan for their thoughts.

**Comment by alisonnjones** [comment]
Thanks, @lwaldsc ! I think what we want to do is have a search tool that populates the search results into a display similar to a call list. The search terms would be based on the following criteria - 
1. Pledge sent field is blank (no pledge has been sent yet)
2. The last call recorded with the patient is between 7-21 days old

**Comment by colinxfleming** [comment]
The timbre of this reminds me a lot of #679 -- is there some crossover there?

**Comment by alisonnjones** [comment]
@colinxfleming it definitely sounds like there could be. i think the difference is in the usage. We'd want the cm clean up crew to use this search tool to do follow up, whereas the urgent flag from #679 would be primarily used by cms on shift who need to have those pts on their radar. i see #679 coincided more with the events feed than this type of functionality, but that's just me

**Comment by lwaldsc** [comment]
They definitely both fall under "Reducing drop off" but yeah, different
issues and different actions.

**Comment by deesriv** [comment]
Agree with Alison and Lisa. Also I think that this one might still want to
capture patients regardless of contact made or not so that as few calls go
unanswered as possible, whereas #679 involves some more context about a
patient. Both aim to reduce dropoff and missed appts in diff ways/by diff
people.

**Comment by mebates** [comment]
Likely a 'won't fix' as we can get this information in excel.

**Comment by colinxfleming** [comment]
@alisonnjones @deesriv @vtmeghan 

I'm going to close this as a wontfix for now and we can revisit if we want, since as @mebates pointed out the data team can pull this data currently. In the event that they're doing it on the reg, we can explore building out a workflow for it. As it stands I think this is more effort for less reward than some of the other stuff we have on the remaining docket.
