### ISSUE TITLE
How should search handle patients on different lines?

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#825]
Problem description TK

**Comment by colinxfleming** [comment]
* **What are we trying to do?**
When CMs try to create a patient who's already on a line, right now they're getting an absolutely useless error message, and patient creation fails. The failure is right, but the useless error message sucks. (Steps to recreate - try logging into the VA line and creating a patient with phone number `123-123-1231`.)

* **What feature or behavior is this required for?**
Reducing frustration point for CMs.

* **How could we solve this issue? (Not knowing is okay!)**
Probably two things we should hammer out: What would a helpful error message look like? (Starting point: `That patient already exists on the VA line.`) And should we display them anyway with some kind of special flag that they're on a different line?

* **Anything else?**
nah

**Comment by eheintzelman** [comment]
How does this play out?  If a DC line patient calls the VA line, does the VA line CM just pass on the vm message to a DC line CM?  Or are there cases where the CM would want the ability to change the line for that patient? Is this a functionality that currently exists in the system or is it only enabled for admin? 

Once we have a handle on this, we can create an error message that includes some direction for the CM.

How about the 'warning status' style for this? 
https://standards.usa.gov/components/alerts/

**Comment by colinxfleming** [comment]
@eheintzelman I'm not sure how this plays out on the business side, actually. @lwaldsc @NerdyGirl537 what do CMs do when a patient hits the wrong voicemail when they're already going thru the process? 

There are def cases where we'd want to change the line of a patient, but that's admin only right now. We can loosen that to data volunteers and/or CMs @vtmeghan or @NerdyGirl537 think it's appropriate.

Warning status sounds great for this! 💯

**Comment by lwaldsc** [comment]
Yeah, they'll simply email the case manager on the correct line with
something like "Oh hey Eva (#1-2345) called me on the DC line, but she's
actually yours." and then the correct CM would either start or continue
case management.

It really depends if the CM directors want to keep the added work of
changing a line for a patient. I don't think/know it happens often enough
to warrant letting all CMs do it, *but* it happens enough that a warning is
suuuuuuuuuuuuuper useful.

**Comment by NerdyGirl537** [comment]
Also, this weekend Joy contacted me thinking there was a problem with a patient on the DC line she'd been working with.  Turns out she had been logged onto the MD line when she entered the patient.  She could find the patient when logged into DC but not add to the call list.  (I'm not sure what all we've done on this issue for CMs as I didn't realize that you could see patients from other lines).  I moved the patient to the DC line.

**Comment by colinxfleming** [comment]
That's interesting! I thought that you couldn't search for patients on other lines. That's probably something for eng to investigate to make sure that's working as intended (no crossover, period, at this time). I'll file a separate ticket to confirm that's okay tonight.

@NerdyGirl537 can you chase @vtmeghan and confer on @eheintzelman 's question above?

**Comment by lwaldsc** [comment]
Per @vtmeghan and this big wall of error message text was cleared by @mebates @eheintzelman 

Ideally, we should be able to search for a patient under all three lines.

Actions it should take if you search for a PT in DARIA but they are not on the line you are working:

1) Give you an error message "This number in already use on the [MD/DC/VA] line. Please contact the case manager on duty on the [MD/DC/VA] line to confirm which line the patient should be case managed under. If the line needs to be changed, please contact the CM Directors."
2) Continue to **not allow** new patient to be saved (as currently the case).

**Comment by eheintzelman** [comment]
Thanks for the language!  Here it is in the warning status style. In this example, the case manager is on the DC line and searched for a patient that already exists on the MD line.

![error message](https://user-images.githubusercontent.com/17989540/29051695-8657b3f2-7bb2-11e7-8ab2-4a6360a52645.png)

I assume that this pulls down from the top of the page, like the other status messages.

Font awesome works for the icon: http://fontawesome.io/icon/exclamation-triangle/

**Comment by lwaldsc** [comment]
This looks great Eva! <3

**Comment by colinxfleming** [comment]
Switching to a backend task since this is now shovel-ready. This probably involves some complex wrenching in searchable but I think it should be doable. Some guidelines:

* For simplicity's sake, if it's easiest to just worry about primary phones and/or exact matches then do that.
* It may be easier to search the other lines only if the primary search returns no results.
* Might have to adjust the messages partial in `app/views/layouts/_messages` so that it accepts whatever the bootstrap warning class is called. I think we only handle danger and success now.

**Comment by colinxfleming** [comment]
ps as @lwaldsc noted, @eheintzelman this is a real beaut and some wonderful work digging team eng out of this unexpected hole!

**Comment by colinmcglynn** [comment]
I'll grab this

**Comment by geoffreyyip** [comment]
Quick update, I am still working on this issue. No proposals yet. I'm still feeling out the app structure.

**Comment by geoffreyyip** [comment]
It seems like there's two different components we're trying to change.
- the search box to list existing patients
- the form to submit a new patient.

For the search box, what behavior do we want regarding multiple lines? I'm seeing different ideas.

For the new patient form, how about writing a [custom validator](http://guides.rubyonrails.org/active_record_validations.html#validates-with)? There's no built-in functionality to check when a number exists under a different name.

**Comment by colinxfleming** [comment]
@geoffreyyip I think we only really need to worry about the second form-to-submit-new-patient case here, and the rest will follow. I don't think we need to change search behavior at this time, just provide a more helpful error message that a CM can work off of. (My fault for bad issue title/problem description.) A custom validator that provides better errors on primary phone uniqueness is a great idea, I think.
