### ISSUE TITLE
Call list features/edits

### ISSUE THREAD

**Issue by lwaldsc** [DCAFEngineering/dcaf_case_management#830]
We've had a lot of user feedback on different actions they would like the call list to be able to make, including the possibility of keeping a pt we do not touch in the call list rather than having it move to the completed calls list. Just starting an issue thread to further discuss what options we'd like to see and what is possible from a design/development standpoint.

**Comment by colinxfleming** [comment]
@lwaldsc has anything bubbled up to the surface on this front? Wondering if we should close this in favor of specific issues, or if the next step here is having UX undertake a review of the call list functionality generally.

**Comment by colinxfleming** [comment]
@lwaldsc I'm going to close this out, since there's nothing actionable here yet and it's been quiet. In the event that stuff bubbles up, do me a solid and make a new issue for the individual stuff you're hearing and tag it UX. $$$$
