### ISSUE TITLE
Small UX changes to pledge fulfillment

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#838]
stems from conversation with @mebates 

* no autofill options
* <strike>make submit pledge disappear if fulfillment is showing up</strike> (resolved elsewhere)

**Comment by AlexandraCasser** [comment]
@colinxfleming What file does this need to happen in?

**Comment by colinxfleming** [comment]
Turning this into an actual task!

* Please add `autocomplete: false` to the form fields in `app/views/patients/_fulfillment` . We'd like this because the form acts weird and tries to put in random data otherwise.

**Comment by SamuelLangenfeld** [comment]
Hey I'm going to take this since it's been inactive for awhile.
