### ISSUE TITLE
Rails5 Technical Debt: Move Mongoid-Session-Store-rails4 to a Rails5 lib

### ISSUE THREAD

**Issue by DarthHater** [DCAFEngineering/dcaf_case_management#867]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
* Well, right now we rely on a lib that is rails4 specific. It seems this lib is going to be absorbed into an official mongoid-session-store lib, and support for Rails 5 will be added there
* Problem is, they haven't released the Rails 5 support yet
* Bigger problem is, I added a reliance on a branch of a fork of the original lib where there is Rails 5 support
    - See: https://github.com/drgcms/mongo_session_store/tree/rails5
    - drgcms lib didn't work (he didn't implement a method we needed) so we forked to our own: https://github.com/DarthHater/mongo_session_store

* **What feature or behavior is this required for?**
* We want to make sure to use libs that are seeing active development, and won't be abandoned
* If we don't do this we will probably be decently mad at ourselves when Rails 6 or something else comes along

* **How should we solve this issue?**
* Move to using the mongoid-session-store lib once they release a Rails 5 version
    - This one: https://github.com/mongoid/mongo_session_store

Related to the work at #865

**Comment by colinxfleming** [comment]
Looks like there's an issue for rails 5 support that we can keep an eye on here: https://github.com/mongoid/mongo_session_store/issues/16
