### ISSUE TITLE
Omnibus issue for report requests

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#877]
Now that we have actual data, the time has come to start really working it. I've received a couple of data requests from DCAF brass and I think we can start building them out. 

Backend wise, let's try and put these in a namespace under the patient object (something like `Patient::Reporting`) and try to right as much of it in activerecord as we can. For more complex items or things requiring statistical rigor, let's hold until we can bring in Datakind because I have no idea how to manage that sort of information. 

Frontend wise, let's get a design consult once we have the initial reporting designs placed in production.

**Comment by colinxfleming** [comment]
note to self that we should see what keshif can do for us, as well.

**Comment by colinxfleming** [comment]
Requested by DCAF VP Lauren on 2/24/17: 

```
1) Fulfillment rates by state
2) Fulfillment rates by clinic

I'd be particularly interested if someone could get raw data as well as a basic statistical analysis to see if the difference is significant.
```

**Comment by colinxfleming** [comment]
We need a way to get the quant figures in from here: 

http://dcabortionfund.org/wp-content/uploads/2016/02/DCAF_Annual_Report_2015.pdf

This is stuff that NNAF requests from everyone annually, plus some extras that go in our annual report.

**Comment by colinxfleming** [comment]
@rfroetscher hey, if I remember right you had a second WIP branch here, right? If you still have that would you mind pushing it up and making a WIP PR for it?

**Comment by rfroetscher** [comment]
hey @colinxfleming. I have a WIP PR here https://github.com/colinxfleming/dcaf_case_management/pull/966

**Comment by NerdyGirl537** [comment]
Need a report to reflect number of calls by line for each day.  Need to know when the case load grows beyond what a single case manager can support.

**Comment by colinxfleming** [comment]
Punching into #634
