### ISSUE TITLE
UX req: Way to mark patients urgent outside of the patient view

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#898]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
CM Joy asked for a way to add an "urgent" toggle to the dashboard (or outside of the  so that you can mark or unmark someone as urgent without needing to go all the way in to the patient notes. 

* **What feature or behavior is this required for?**
Being able to mark someone urgent without popping into the patient edit view, probably at the time of either logging a call or checking a voicemail, but not necessarily? 

Team UX: Your thoughts on whether this is useful, or whether the current workflow is perfectly adequate for this?

**Comment by mebates** [comment]
I think the current workflow should work for this.

**Comment by mebates** [comment]
Closing. We don't need to add this, users can reach the 'urgent' checkbox easily enough with the current workflow.
