### ISSUE TITLE
UX req: Way to add called patients back to call list once in completed calls?

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#899]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Some feedback from CM Joy: " Could there be a way to to move someone from completed calls back to the call list. I had a hard time getting a record back in my call list when I left a message for someone and then they called back."

* **What feature or behavior is this required for?**
Patients sometimes call back in the middle of a shift for some phone tag -- what Joy's asking to do here is re-rack them into the call list when she sees there's a new voicemail from them, after having called them earlier in the shift and left a message.

Team UX: Thoughts on whether this would be a useful part of the workflow?

**Comment by mebates** [comment]
Looks like this can be easily solved by adding the word "Add" into the table of completed calls, to match what it looks like in 'Search'. 

<img width="1265" alt="screen shot 2017-04-04 at 7 27 13 pm" src="https://cloud.githubusercontent.com/assets/6223901/24683433/00d6d516-196d-11e7-9424-6a987e553862.png">

**Comment by colinxfleming** [comment]
I'm going to close this as a wontfix unless other people besides Joy raise this as an issue -- I think this is tougher to implement from the backend side than it's really worth.

@lwaldsc @NerdyGirl537 please flag if you object and this is a super common use case where the system can really have a value-add -- right now I get the sense that there's a nontechnical solution of 'look at the voicemail box again and log another call'.
