### ISSUE TITLE
Style clinic edit page

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#947]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
More easily manage the index of clinics at `/clinics`, so we can find info we need about individual clinics we work with.

* **What feature or behavior is this required for?**
Displaying clinic information, and some workflow easing for entering new clinics, which in turn lets us keep our clinics up to date and help patients figure out the best clinic for their given set of circumstances. This in turn plugs into the work we're doing around getting clinics to stop being env vars, and start getting them into updatable models where we don't have to fix them up.

* **How could we solve this issue? (Not knowing is okay!)**
That's up to team UX!

* **Anything else?**
We're anticipating ~30-40 clinics. Some sortability might be helpful. More details might go well with an accordion.

Stems from the PR in #929 

cc @mebates @jingpei

**Comment by colinxfleming** [comment]
Moving to active. This is a good UX task for tonight, personnel permitting! The object model is roughly thus: 

* name
* street address
* city, state, zip
* gestation limit
* whether or not they accept naf $
* some complicated financial charting for costs based on gestation

**Comment by lwaldsc** [comment]
<img width="1077" alt="molly is an artist" src="https://cloud.githubusercontent.com/assets/10578608/24683878/0fed93b6-1970-11e7-850f-a85f2a26de6d.png">

**Comment by mebates** [comment]
Sortable table with expand/collapse on the right edge:

<img width="655" alt="screen shot 2017-04-04 at 8 27 49 pm" src="https://cloud.githubusercontent.com/assets/6223901/24684605/3c6024a4-1975-11e7-9752-edda6b3dd39f.png">

**Comment by colinxfleming** [comment]
Bumping to frontend now that we have designs! 

Feel free to heavily leverage this bootstrap component: https://getbootstrap.com/javascript/#collapse-example-accordion

**Comment by SamuelLangenfeld** [comment]
I'll jump on this

**Comment by colinxfleming** [comment]
As part of #1011 we regressed slightly and took out the costs at weeks chart. Here's the code we used to generate that previously:

```
      <tr>
        <% (5..30).each do |week| %>
          <th><%= week %></th>
        <% end %>
      </tr>

      <tr>
        <% (5..30).each do |week| %>
          <td>$<span class="blush"><%= clinic["costs_#{week}wks".to_sym] %></span></td>
        <% end %>
      </tr>
```

We can consider this closed when this is in the collapsible clinic details somehow, I think.

**Comment by colinxfleming** [comment]
On second thought, we aren't doing anything with that data yet anyway, let's just call this good.
