### ISSUE TITLE
Investigate Routes

### ISSUE THREAD

**Issue by DarthHater** [DCAFEngineering/dcaf_case_management#950]
When upgrading rails in #865 and #853 I noticed our routes get knocked out by `rails app:update` / `rake rails:update`, which throws a bit of caution to the wind. It might be worth checking out routes.rb and ensuring we are following the most current patterns, etc...

**Comment by colinxfleming** [comment]
I took a look at this recently and we still seem to be following best practices on this front. I'm marking closed.
