### ISSUE TITLE
User edit page: make changes 

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#951]
TK, just an issue I noticed in talking to a user

**Comment by colinxfleming** [comment]
Here's the bucket list of stuff to alter, in `users/edit`:

* email should not be an editable field
* only name should be editable
* remove 'enter password to confirm' and password reset stuff
* instead of password reset, include a link to `new_user_password_path`

**Comment by AlexandraCasser** [comment]
@colinxfleming I could also take this if it's ready to go.

**Comment by colinxfleming** [comment]
@AlexandraCasser go for it!

**Comment by colinxfleming** [comment]
(let me know if you run into any snags in the process, of course. There might be a few curveballs buried in there, since a lot of this stuff comes straight from `devise`)

**Comment by AlexandraCasser** [comment]
@colinxfleming is it possible for you to assign this to me so I can find it more easily?  Thanks.

**Comment by colinxfleming** [comment]
@AlexandraCasser you bet!

**Comment by colinxfleming** [comment]
whoops, maybe not, sorry. Looks like you need to have push access to the repo to be assigned stuff, sorry. I'll talk to you on slack on how to resolve. 

The other day we were discussing migrating this project to a proper github organization, which would allow us to assign tickets easier (I think).

**Comment by AlexandraCasser** [comment]
Hey @colinxfleming , does this look reasonable?

`<div class="authform">
  <h2>Edit <%= current_user.email %> (<%= current_user.name %>)</h2>

  <%= bootstrap_form_for resource, as: resource_name, url: '/users', html: { method: :put } do |f| %>
    <%= devise_error_messages! %>

    <h3>Change your account details</h3>
    <p>Email</p>
    <p><%= current_user.email %></p>
    <%= f.text_field :name, label: 'First and last name' %>

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
    <% end %>

      <%= link_to "Forgot your password?", new_user_password_path %>
  <% end %>
  <br>

  <%= link_to "Back", :back %>
</div>
`

**Comment by colinxfleming** [comment]
@AlexandraCasser That looks good to me! Will you spin up a PR with that so we can try it out? We might have to make some slight controller adjustments in case devise is cagey about not having a password/password confirmation.

**Comment by AlexandraCasser** [comment]
[Pull request is here.](https://github.com/DCAFEngineering/dcaf_case_management/pull/1050)
