### ISSUE TITLE
POTENTIAL BUG: Turbolinks upgrade uses new event type

### ISSUE THREAD

**Issue by DarthHater** [DCAFEngineering/dcaf_case_management#970]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

So in moving to the new Turbolinks, apparently it uses a new event type. More on that here:

https://stackoverflow.com/questions/17317816/rails-javascript-only-works-after-reload

There are a few spots that still use the old event type, but I'm unsure if it's causing issues, here's an example of it still kicking in patients.coffee

https://github.com/colinxfleming/dcaf_case_management/blob/master/app/assets/javascripts/patients.coffee#L57

* **What feature or behavior is this required for?**

Not quite sure yet, to be honest. Things could be busted, they could be fine? They were broken for at least one piece of functionality, documented in #968 

* **How could we solve this issue? (Not knowing is okay!)**

Follow the advice in the top answer at the SO link above.

* **Anything else?**

I like turtles.

**Comment by colinxfleming** [comment]
I'd like to bump turbolinks as we continue to dig ourselves out of technical debt. Promoting to active.

**Comment by colinxfleming** [comment]
Resolved via #1033
