### ISSUE TITLE
Limit Clinic Selection to clinics that accept NAF for some PTs

### ISSUE THREAD

**Issue by mebates** [DCAFEngineering/dcaf_case_management#979]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
We now have great data stored on clinics, and we want to reveal it to the CMs. Add a selector below 'Clinic details > Clinic Name' that says "Only show clinics that accept NAF funding". If the CM checks this box, limit the list to clinics that accept NAF.

**Comment by colinxfleming** [comment]
The file in question here is `app/patients/views/_abortion_information`, and the clinic source is in `app/helpers/patients_helper.rb#clinic_options`.

The possible rub here is that if a clinic is selected, we don't want it to disappear. We might be able to do that with some jquery and data attributes, something like: 

* all select options have a data attribute like `data-naf=true` or `data-naf=false` - the selected clinic has `data-selected=true`
* the 'show only NAF clinics' toggle removes or disables selection of anything with `data-naf=false` in the option that doesn't also have `data-selected=true`.

That's just an off the top of my head possibility, though. Taker's choice on how to handle.

JS heavy, so tagging frontend. Put it in the space underneath the select bar.
