### ISSUE TITLE
Autocheck 'Fulfilled' checkbox when entering stuff in any fulfillment field

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#983]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
In this fulfillment form, there's a boolean checkbox for 'Fulfilled' that's easy to miss -- we should make it so it autochecks if you enter any fields in the fulfillment form.

* **What feature or behavior is this required for?**
Make sure our data entry vols don't accidentally mark someone as not fulfilled. 

* **How could we solve this issue? (Not knowing is okay!)**
The code to this partial is in `app/views/patients/_fulfillment.html.erb`. Any js should go in `app/assets/javascripts/patients.coffee`. 

Here's a screenshot of the partial in action:
![image](https://cloud.githubusercontent.com/assets/3866868/24735714/389a3688-1a52-11e7-9580-f35af9403a26.png)

I'm agnostic as to the best way to do this, so taker's choice. Probably the most straightforward way to do this is to just check the box if any fields in the form aren't blank or empty. 

* **Anything else?**
There's a patient created from `rake db:seed` that you should use, since the Fulfillment tab doesn't show up until a patient's marked pledge sent. (Name: `Pledge Submitted - 3`)

Stems from #864 .

Reserving for Jon, who needs a js issue to hammer on!

**Comment by electricflannel** [comment]
I'm taking this bad boy
