### ISSUE TITLE
Clean up Rails 5.1 deprecation warnings

### ISSUE THREAD

**Issue by DarthHater** [DCAFEngineering/dcaf_case_management#984]
In moving to Rails 5.0.2 we cleaned up a lot of deprecations, but some remain.

When you run `rails test` you should see the following warnings:

```
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> at /code/dcaf_case_management/config/environment.rb:5)
DEPRECATION WARNING: after_filter is deprecated and will be removed in Rails 5.1. Use after_action instead. (called from <top (required)> at /code/dcaf_case_management/config/environment.rb:5)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> at /code/dcaf_case_management/config/environment.rb:5)
DEPRECATION WARNING: after_filter is deprecated and will be removed in Rails 5.1. Use after_action instead. (called from <top (required)> at /code/dcaf_case_management/config/environment.rb:5)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /code/dcaf_case_management/config/environment.rb:5)
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:7)
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:8)
```

Most of these are likely in gems since a cursory grep turned up no results, so we will have to figure out which gems they are in, update them, or figure out another alternative. This is currently causing no issues, but will prevent us from moving to Rails 5.1 if the time comes.

**Comment by cmacaulay** [comment]
@colinxfleming does this still need addressing?

**Comment by DarthHater** [comment]
Casey, it totally does. I think most of the warnings are now in gems we
import, and not in our codebase but it would be good to affirm that/list
them (it's a bit obtuse at first glance right now), and also to see which
we can update gems to remove the warnings. Also might be worth floating PRs
to the upstream repos if the change isn't onerous.

**Comment by colinxfleming** [comment]
@cmacaulay echoing what @DarthHater said.

I think the offending libraries are `turbolinks` (my enemy turbolinks, at it again), `puma`, and `better_errors`. It looks like turbolinks is being poked at, but could I trouble you to bump puma and better_errors, and confirm that things still flow cleanly?

**Comment by colinxfleming** [comment]
@cmacaulay just wanted to check in and make sure all was well! Let me know if there's anything we can be helpful with!

**Comment by colinxfleming** [comment]
Our remaining depreciation warnings are:

```
DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /Users/colin/repos/dcaf_case_management/config/initializers/new_framework_defaults.rb:23)
```

I'll get this resolved.
