### ISSUE TITLE
Rails5 Technical Debt: Figure out if we need mongoid_userstamp

### ISSUE THREAD

**Issue by DarthHater** [DCAFEngineering/dcaf_case_management#987]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

What are we trying to do?

We are relying on a Mongo library that has essentially gone into deep hibernation, and had to fork it to: https://github.com/DarthHater/mongoid_userstamp.git

Upstream when submitting changes we were asked to take over the library: https://github.com/tbpro/mongoid_userstamp/pull/35

What feature or behavior is this required for?

We want to make sure to use libs that are seeing active development, and won't be abandoned

If we don't do this we will probably be decently mad at ourselves when Rails 5.1 or 6 or something else comes along

How should we solve this issue?

We may need to figure out another way to do what this gem does, unfortunately not as simple as some of our other issues, or keep maintaining the forked library.

**Comment by colinxfleming** [comment]
a quick programming note: since we're our own github org now, may be a good idea to fork these libraries in and draw from them there, rather than personal githubs.

**Comment by colinxfleming** [comment]
An update here, this has a new maintainer (yay) and we can hopefully ditch our fork soon (double yay)

**Comment by colinxfleming** [comment]
marking this futuretech since this hasn't moved in six months and the dude hasn't merged our PR yet.

**Comment by xmunoz** [comment]
No longer relevant
