### ISSUE TITLE
New Contributor Security Onboarding 

### ISSUE THREAD

**Issue by mccabe615** [DCAFEngineering/dcaf_case_management#994]
* **What are we trying to do?**
Create a short introduction to security for new contributors to the project to review before submitting PRs.

* **What feature or behavior is this required for?**
Update to the contributing file or maybe a issue template that can be assigned to new contributors to complete. @colinxfleming it's your preference

* **How could we solve this issue? (Not knowing is okay!)**
See below.

* **Anything else?**

Here's the template I was thinking would work. It covers a lot of the basics of Ruby and Rails security.

## Security

Please read the following resources to get an overview of Ruby and Rails security before opening PRs.

[Ruby on Rails Security Cheatsheet](https://www.owasp.org/index.php/Ruby_on_Rails_Cheatsheet)

Get familiar with Brakeman and run it often. It runs as part of the build but it is easier to run it before opening your PR and fixing it there.

[Brakeman Scanner](http://brakemanscanner.org/)

### Cryptography
If you need to encrypt, sign or hash something here are the recommended libraries. Do not roll your own library and use only libraries that have been reviewed by the community.

#### Hashing
Ruby has built in hash function that can be used. MD5 and SHA1 are considered broken and should not be used. SHA2 is still considered secure.

Example:
```
> require 'digest'
> Digest::SHA2.hexdigest 'abc'
> "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
```

#### Password hashing
Bcrypt or Scrypt are the preferred methods for hashing passwords. More details are here:

[Bcrypt](https://github.com/codahale/bcrypt-ruby)

#### Encryption
RbNaCl is a great library that makes encryption in Ruby relatively easy. Be cautious when deciding to use encryption, there are a million ways to make a mistake and they're often overlooked.

[RbNaCl](https://github.com/cryptosphere/rbnacl)

#### Signing
Rails has a built in method to sign messages.

[Message Verifier](http://api.rubyonrails.org/classes/ActiveSupport/MessageVerifier.html)

#### Random Token
If you need to generate a random token, for a reset password email for example, use SecureRandom that is built into Ruby.

[SecureRandom](https://ruby-doc.org/stdlib-2.3.0/libdoc/securerandom/rdoc/SecureRandom.html)

#### More reading:

[Ruby on Rails Security Guide](http://guides.rubyonrails.org/security.html)

[An Overview of Cryptography](http://www.garykessler.net/library/crypto.html)

[Password Hashing](https://crackstation.net/hashing-security.htm)

**Comment by colinxfleming** [comment]
@mccabe615 love this. My inclination is to put the full doc in `docs/SECURITY_INTRO.md` or something like that, and link to it in `docs/SETUP.md` and `.github/CONTRIBUTING`.

If you want to knock it out, go for it, otherwise I've tagged it as a first timer issue.

Sound like a plan?

**Comment by colinxfleming** [comment]
Marking active, this is a good one for someone who's interested in getting a feel for the github pull request system and markdown!

Steps to complete:

* Put @mccabe615 's template above in a file at `docs/SECURITY_INTRO_FOR_DEVELOPERS.md`
* Add a link to `docs/SECURITY_INTRO_FOR_DEVELOPERS.md` with some explanatory text in the `New and looking to dive in?` section of `.github/CONTRIBUTING`

**Comment by SamuelLangenfeld** [comment]
Hey @colinxfleming I'm going to jump on this one. We're wrapping up here but I should have it done tomorrow.

**Comment by SamuelLangenfeld** [comment]
Submitted a PR for this issue.
