### ISSUE TITLE
Abstract DCAF specific stuff out of app

### ISSUE THREAD

**Issue by colinxfleming** [DCAFEngineering/dcaf_case_management#999]
There's some DCAF specific stuff in the app that we need to abstract out. Here's our general ticket to log, for squashing in other tickets. 

Stuff to generalize off the top of my head:

- [x] the pledge attribute is called `dcaf_soft_pledge`
- [x] PDF generation is hardcoded to dcaf's needs -- I have an example of the form but this is going to be pretty involved. In the short term we should just shut it off for Baltimore I think and aim to have it in place when they start it up in June.

**Comment by cfinucane** [comment]
This is something I'm particularly interested in, given that I'm hoping to use this for another fund. Let me know when you feel like we're in a good place to move on this, as I'd be happy to tackle it.

**Comment by colinxfleming** [comment]
Other stuff to do:

* change `DCAF_GOOGLE_KEY` and `DCAF_GOOGLE_SECRET` to `DARIA_GOOGLE_KEY` and `DARIA_GOOGLE_SECRET` in `web_variables.env`
* in `app/mailers/application_mailer.rb`, change the domain to be a) a real domain and b) an env var with a default
* rename apps in New Relic to use env vars (something like `DARIA ['FUND'] (Development)
* rename db in dev and test envs in `config/mongoid.yml`
* Change `Team DCAF` to `Team DARIA and ['FUND']` in `app/views/mailers/user_mailer/*`
* update docker remote location and then bump `docker-compose.yml`
* adjust status helper to say `resolved without fund`

**Comment by colinxfleming** [comment]
* Change welcome message in `app/views/lines/new.html.erb`
* Change instances of `resolved_without_dcaf` in forms and pregnancy model to be `resolved_without_fund`
* Bump `civic.json`
* Rename `DCAF Data Center` to just `Data Center` in `app/views/reports/index.html.erb`

That's a good starter kit, I think.

**Comment by colinxfleming** [comment]
- [ ] Not sure 'select your line' in `app/views/lines/new` makes sense for single-line funds. Should do something like autoselect if there's only one line. Can spin this into its own ticket, so mark this off when it's its own issue.

**Comment by colinxfleming** [comment]
Remaining spots:

- [] Patients helper
- [] Pledgeable concern
- [] Ext pledge controller (in a comment)
- [] Pledge form (probably its own huge deal)

**Comment by colinxfleming** [comment]
- [] User model, password restrictions (probably its own PR)
- [] app/views/patients/_pledge

That, I think, is the end of it!

**Comment by colinxfleming** [comment]
Good to go, closing!
